### ISSUE TITLE
Quote displaying with double quotes on CNX

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1047]
# Scenario
A quote with the tagging displayed below results in double quotes being generated in CNX and REX. The first set of quotes cannot be highlighted or interacted with. 

`<para id="fs-idm196041856"><quote id="fs-idm208597392">&#8220;Engaging our diverse stakeholders in long-term dialogue provides important input that informs our decision making, and helps us continuously improve and make progress toward our 2020 sustainability goals . . . We are committed to ongoing stakeholder engagement as a core component of our business and sustainability strategies, our annual reporting process, and our activities around the world. As active members of the communities where we live and work, we want to strengthen the fabric of our communities so that we can prosper together.&#8221; <cite id="rf-004-a" target-id="rf-004"><note class="delete-me" display="inline"/></cite></quote></para>`

# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ X] Yes  [ ] No  (_attach below_)
This CNXML results in this on CNX: 
![Screen Shot 2019-05-03 at 1.54.43 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/34bcfcfb-98b2-4c1e-bdde-f6a9a27c99d9)

And this in the PDF:
![Screen Shot 2019-05-03 at 1.44.20 PM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/9bbe3568-fdf8-4b9f-b691-e2db73652efb)

# Environment:

* **Medium**: [ X] REX [ ] PDF  [ X] cnx.org  
* **Instance**: [ X] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [X ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ X] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [X ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by brittweinstein** [comment]
assigning to @openstaxalina  for prio and assignment into future sprint.

**Comment by openstaxalina** [comment]
@yblock this is a fun one, but I believe we can resolve this in markup.

&#8220 and &#8221 are placed directly into the conent, causing the quotation marks to appear in the PDF -- but this makes them occur twice in webview

After taking a look at https://github.com/openstax/cnx-recipes/issues/669 and https://github.com/openstax/cnx-recipes/issues/800 I would advise switching the order of the `quote` and `para` tags so that para is nested within quote.

@yblock could you try this?  I think the result will be a grey bar in webview instead of the additional quotes, which is acceptable.  And the PDF should not change 🤞

**Comment by yblock** [comment]
That did have the desired effect!

![Screen Shot 2019-05-06 at 12 18 28 PM](https://user-images.githubusercontent.com/5865292/57242433-17e60080-6ff9-11e9-93bd-35ee2c3ed048.png)
