### ISSUE TITLE
Organizational Behavior: Figure, Table callout and caption in Appendix

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1050]
**Appendix A – m11024**

**WEB View**

![image](https://user-images.githubusercontent.com/39794953/57178083-26150f00-6e89-11e9-93ec-a1b74696439f.png)

**Comments:** In WEB view, Exhibit view as Exhibit A1 for the callout (period missing between A and 1), same applicable for the caption. This needs to be modified similar to chapters.

![image](https://user-images.githubusercontent.com/39794953/57178096-5fe61580-6e89-11e9-8cd6-22a37f702b96.png)

**Comments:** In WEB view, Table view as Table A1 for the callout, (period missing between A and 1), same applicable for the caption. This needs to be modified similar to chapters.

**Comment by openstaxalina** [comment]
Propose leaving as-is.  
Exhibits and tables in Appendices are an exception to the #.# schema, since they are a letter followed by a number.

_Introduction to Business_ was approved for publication with tables such as A1 in the appendices:
<img width="576" alt="Screen Shot 2019-05-06 at 10 41 52 AM" src="https://user-images.githubusercontent.com/7863733/57236949-bc614600-6feb-11e9-9fb5-7b16f03d5fa3.png">

(There were no exhibits in the appendices in _Introduction to Business_.)

Will discuss with Mike Roche on May 7 call.

**Comment by openstaxalina** [comment]
Mike Roche confirms this is okay as-is.  Closing.
