### ISSUE TITLE
Organizational Behavior: Header size in appendix

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1051]
**Appendix B – m11025**

**WEB**

![image](https://user-images.githubusercontent.com/39794953/57178106-8a37d300-6e89-11e9-86e7-2dc3fe72e158.png)

**Comments:** We tried to build the book collection with these partial chapters to see the outcome of Preface and Appendix and from Appendix in WEB view, the section title seems to be in larger font, while compared to the chapter sections. Same applicable for Appendix A.

**Comment by openstaxalina** [comment]
This seems to be occurring because the first section title in an Appendix gets h2, whereas the first section title in a chapter section gets h3.  It is likely related to https://github.com/openstax/webview/issues/1943.  

We will likely not be able to fix this before Organizational Behavior is published, but this will be resolved via a more global fix in a future quarter.

**Comment by brittweinstein** [comment]
@lwtchu do you know if this is still an issue?

**Comment by brittweinstein** [comment]
Discussed w/ Alina and Larissa--we will close.
