### ISSUE TITLE
carnival theme: end of chapter specifications

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1085]
TOP LEVEL HEADERS
Font: IBM Plex Sans, bold, all caps
Size: 2.074rem 
Color: book specific

KEY TERMS
Font: Base font style
Treatment: bold the key term, leave the definition unbolded
Hanging indents?: YES

KEY EQUATIONS
Should be a table `unnumbered unstyled` see #1084 for styling

SECTION SUMMARIES
#.# Section title format: Muli Extrabold 1.44rem, black
Body text: base font size/font

Any assessments and sections that need subsection, the section title and number should be formatted as such: Muli Extrabold 1.44rem, black

**Comment by openstaxalina** [comment]
@brittany-johnson confirming status with Richelle - ready for code review or still in progress?

**Comment by richelleyy** [comment]
The pdf should look like this:
<img width="931" alt="Screen Shot 2019-07-15 at 2 05 44 PM" src="https://user-images.githubusercontent.com/50836449/61241754-c7320880-a709-11e9-81c4-1c8f516aefcd.png">
<img width="931" alt="Screen Shot 2019-07-15 at 2 05 52 PM" src="https://user-images.githubusercontent.com/50836449/61241755-c7320880-a709-11e9-94a1-ae25a005c73d.png">
<img width="944" alt="Screen Shot 2019-07-15 at 2 06 00 PM" src="https://user-images.githubusercontent.com/50836449/61241756-c7320880-a709-11e9-9cea-944803f2bb97.png">
<img width="546" alt="Screen Shot 2019-07-15 at 2 06 10 PM" src="https://user-images.githubusercontent.com/50836449/61241757-c7320880-a709-11e9-8d20-5ae62fe6dac7.png">

**Comment by Stackblocks** [comment]
# QA Breakdown

## Pass
- Key Terms
- Section Summary titles presenting at correct size

## Fail
- `KEY EQUATIONS
Should be a table unnumbered unstyled see #1084 for styling`
- Section Summary titles presenting in Times New Roman instead of Muli Extrabold
- Assessment section titles are 14pt font instead of 1.44rem (~10pt)


## Notes
- If the Key Equations being a table is presenting correctly please let me know and I will adjust the comment to reflect that.
- Section Summaries being TNR instead of Muli may be related to ongoing font issues.

## Screenshots
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/18a8bcbf-ebe6-45b3-b6b4-5155eed1c789)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5acb8f45-d0e0-4364-97de-434810b36a6c)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d642d029-cc6e-413c-8782-ea5028563e57)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/92609a4b-7d58-4eb9-aef4-b3e53968fd46)

**Comment by richelleyy** [comment]
The pdf looks like this on my laptop:
![Screen Shot 2019-07-17 at 3.56.05 PM.png](https://images.zenhubusercontent.com/5ce40ed4f65f484031c4e603/2bc6ee4b-effb-480e-bf2b-6aa58bad075e)

**Comment by Stackblocks** [comment]
Assessment section titles now showing at correct size.

Still need to resolve Section Summary titles being Times New Roman instead of Muli Extrabold.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9adfd827-a820-4cbc-9102-d0db73b63cd8)

**Comment by richelleyy** [comment]
@Stackblocks I merged the issue to m.m [https://github.com/openstax/cnx-recipes/pull/1218] since I've merged this PR. Now, the fonts should be displaying correctly once Chris merged his PR https://github.com/openstax/cnx-recipes/pull/1217.
<img width="978" alt="Screen Shot 2019-07-19 at 11 33 40 AM" src="https://user-images.githubusercontent.com/50836449/61551039-bc34ec00-aa19-11e9-803f-f6b7300d223a.png">
<img width="1005" alt="Screen Shot 2019-07-19 at 11 33 49 AM" src="https://user-images.githubusercontent.com/50836449/61551040-bc34ec00-aa19-11e9-8b36-f86edb210475.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

**Comment by Stackblocks** [comment]
Reopening for cleanup / review

**Comment by helenemccarron** [comment]
![2019-08-13_13-07-11](https://user-images.githubusercontent.com/8514591/62965841-71fe1b00-bdcb-11e9-91e5-c9f214ffedf3.png)
![2019-08-13_13-06-38](https://user-images.githubusercontent.com/8514591/62965845-732f4800-bdcb-11e9-824d-195528069b9e.png)

![2019-08-13_13-04-53](https://user-images.githubusercontent.com/8514591/62965851-7591a200-bdcb-11e9-85b7-c6d2236dfb2d.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![2019-08-15_14-34-28.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5ffd811f-062f-416f-acd9-07f8a075a4b7)
---
![2019-08-15_14-34-09.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ea841177-c67f-485a-8ca6-61595aef63ca)
---
![2019-08-15_14-37-52.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/11afd8f5-7a3b-47c0-9fa1-fbfe9f34b0f1)
---
![2019-08-15_14-35-38.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/299aab84-89df-482b-bc4c-fbeb88ab56c8)
---
![2019-08-15_14-35-52.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d8870abe-9c22-4c39-9874-cbebe87a163f)
