### ISSUE TITLE
biology for ap courses: iconned features

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1190]
See #1088 for specifications

Uses a lot from Biology (#1156) such as:
- Evolution Connection (`class="evolution"`)
- Link to Learning (`class="interactive"` * need to change to `link-to-learning`
- Career Connection (`class="career"`)
- Visual Connection (`class="visual-connection"`)
- ~~Everyday Connection (`class="everyday"`)~~
- Scientific Method Connection (`class="experiment"` * need to change to `scientific` to match Biology)

NEW NEW In the AP Biology:
Title: Science Practices Connection for AP® Courses
Class: `ap-science-practices`
Color: #B10069
Icon: https://drive.google.com/open?id=1PwE4qo0vEusOcgOq2KB7L4IGfym96DMc

**Comment by tomjw64** [comment]
Increasing estimate because icon notes did not match spec and I'm accounting for the extra work there.

**Comment by Stackblocks** [comment]
A couple of issues with this one.


# Failing
1. ![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/120bb329-d873-4a81-ab8e-dc79752add0a)
2. Should Everyday Connection be removed from this since it is a boxed feature instead of an iconned feature?


# Passing
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6da4aaea-3094-4f5d-9690-ff4a8cfc2829)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8486ac89-d8dd-42f6-b771-1bcda8081bfd)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f3df5aad-8c32-46e1-bc17-f63682d14416)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f0ffc11c-5b8f-4dab-b528-77a661d825ca)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/dfba7ac6-1337-42b2-a3d8-f738fdbea601)

**Comment by Stackblocks** [comment]
Link to Learning will be handled in https://github.com/openstax/cnx-recipes/issues/1425.
