### ISSUE TITLE
microbiology: color palette & general notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1280]
![Screen Shot 2019-08-23 at 11 10 08 AM](https://user-images.githubusercontent.com/11299125/63606830-978edf80-c596-11e9-932b-0f8dc58b48a8.png)

*** THE BLUE IS FROM THE SIGMA XI LOGO FOR PARTNERSHIP REASONS ***

Theme: Carnival
Chapter title, chapter number, H1, H2, H3, etc: #0074BC
Splash image bar, chapter outline, box color: #0074BC 
Learning objectives text color: #0074BC 

End of Chapter Sections
Contains the following: 
Summary (`class="summary"`) separated by chapter 
Review questions which contain the following: multiple choice (`multiple-choice` - two column), True/False (`true-false` - one column), Matching (`matching` - contains unnumbered unstyled tables), Fill in the Blank (`fill-in-the-blank` - one column),  Short Answer (`short-answer`), Critical Thinking (`critical-thinking` - one column) 
Exercises: Continuous numbering, might contain images or lists or tables, numbering resets after each chapter

End of Book
Appendices
Index

**Comment by Stackblocks** [comment]
Colors and styling are good but we may want to revisit the breaking in the Multiple Choice EoC questions since having disjointed answer choices at the top of the second column can be confusing. (e.g. C & D in the screenshot below.)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cff29e62-dc2a-457e-8017-406098381818)
