### ISSUE TITLE
Rework the key equations

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1333]
Rework the key equations to target a `table` markup structure rather than a `ul` https://github.com/openstax/cnx-recipes/blob/master/styles/designs/carnival/parts/_eoc-components.scss#L63

See https://github.com/openstax/cnx-recipes/issues/1085 and https://github.com/openstax/content-managers/issues/897 for markup

**Comment by brittany-johnson** [comment]
Content is on staging.cnx.org
Search for chemistry 2e and then click on the link to the book so that you are not redirected to Rex

**Comment by brittany-johnson** [comment]
Update: 

The updated content where the key equations are in tables instead of lists is viewable in webview, but not in rex. 

It also seems that when fetching content `docker-compose run --rm fetch-book -e HOST=staging.cnx.org --with-resources chemistry` which is required before baking a book, we are getting the version of the content that is on rex, not on webview. 

So we are not able to test if the styling on key equations is appearing properly when in a table at this time.

**Comment by openstaxalina** [comment]
@brittany-johnson does `So we are not able to test if the styling on key equations is appearing properly when in a table at this time.` apply to the baked PDF or just the web display?

**Comment by brittany-johnson** [comment]
@openstaxalina the baked PDF!

**Comment by brittany-johnson** [comment]
<img width="598" alt="Screen Shot 2019-10-11 at 1 34 10 PM" src="https://user-images.githubusercontent.com/24909007/66675865-db63a400-ec2b-11e9-9819-b94599c83f0d.png">

appearing as a unnumbered unstyled table

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/9a70e55b-fd70-48f5-99d2-66e1cba05747)
