### ISSUE TITLE
college success: icon notes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1415]
### General information
FOLDER FOR ALL ICONS: https://drive.google.com/drive/u/0/folders/19aQqJYvdG3BQssTR3py-EbMzGhbUtcAA

Reference #1348 for design card

### Specs for NEW icon notes
Title: What Students Say
Class: `what-students-say`
Color of the bar: #D34D32
Color of the text for feature title: #000000
Color of the box: #D6D9DD
Icon description: 3 people with a with a lightbulb
Link to Icon: https://drive.google.com/open?id=1cVNMwtvflHmSD0KwbhmZGUPur0SJiniz

Title: Activity
Class: `activity` 
Color of the bar: #D34D32
Color of the text for the feature title: #000000
Color of the box: #D6D9DD
Icon description: woman with paper behind her and she's saying a recycle symbol
Link to icon: https://drive.google.com/open?id=1_Tq-b-YfNiNtZoVvOJnYmtVw0e_KxfPM

### Tweaks to existing features for _College Success_
Title: Get Connected
Class: `get-connected`
Existing business feature: `expanding-around-globe`
Icon description: globe 
Link to icon if you need it: https://drive.google.com/open?id=1Lx-xt_fATDmu2CbY0w0ZIeZeXpht79DU

Title: Analysis Question
Class: `analysis-question`
Existing business feature: `ethics-in-practice`
Icon description: man at a forked road
Link to icon if you need it: https://drive.google.com/open?id=1uOmSGM3ocVpYm7egdszd3rj8wQjdvNm6

Title: Application
Class: `application` 
Existing business feature: `concept-check`
Icon description: a checkmark in a circle
Link to icon if you need it: https://drive.google.com/open?id=1K6aMpeEg0i_KxtVvu4NoEi2_VROXCI7V

**Comment by brittany-johnson** [comment]
Application note: 
![Screen Shot 2019-10-18 at 1 17 54 PM](https://user-images.githubusercontent.com/24909007/67118059-c053df80-f1a9-11e9-9d63-e774c9535b1f.png)

Analyasis note: 
![Screen Shot 2019-10-18 at 1 17 17 PM](https://user-images.githubusercontent.com/24909007/67118060-c053df80-f1a9-11e9-8c6c-51d7740811ee.png)

Get Connected note:
![Screen Shot 2019-10-18 at 1 16 39 PM](https://user-images.githubusercontent.com/24909007/67118061-c053df80-f1a9-11e9-9dca-a7431eb67175.png)

Activity note: 
![Screen Shot 2019-10-18 at 1 16 01 PM](https://user-images.githubusercontent.com/24909007/67118062-c053df80-f1a9-11e9-9085-4178834dc278.png)

What Students Say note: 
![Screen Shot 2019-10-18 at 1 14 00 PM](https://user-images.githubusercontent.com/24909007/67118063-c053df80-f1a9-11e9-922b-1a832adb03be.png)

**Comment by brittany-johnson** [comment]
covered in pr https://github.com/openstax/cnx-recipes/pull/1478

**Comment by Stackblocks** [comment]
The scope of this issue is the establishment of the notes, the styling will occur in a separate issue down the road. 

# What Students Say
![2019-10-21_16-26-45.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/53714d97-42a6-4ed8-b86f-f71aa6553a35)
# Activity
![2019-10-21_16-27-33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8c7380f1-a44d-43ac-b57b-116336e29bcb)
# Get Connected
![2019-10-21_16-29-58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5672f22f-8b0e-41fe-b736-6d28c228170a)
# Analysis Question
![2019-10-21_16-28-33.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ece64bb7-6571-4da2-bea6-cf6a251ca0bc)
# Application
![2019-10-21_16-29-12.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3cdb93df-3d40-48e3-92b1-5a0b47f0a747)
