### ISSUE TITLE
Style Intoduction Page in Biology & AP Biology

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1530]
The Chapter Outline should be styled in order to specs from this issue: https://github.com/openstax/cnx-recipes/issues/1076
The Splash image should be styled related to this issue: https://github.com/openstax/cnx-recipes/issues/1075

**Comment by Stackblocks** [comment]
# Splash Images
The captions beneath splash images in Biology are unstyled and Figures are left-aligned instead of centered.

### Biology
![2019-11-07_13-08-10.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ef4b7a98-6a70-4dec-8c47-7433d94efabd)

### AP Biology
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d011c939-4d0d-4e31-993d-d8bc0a6d7a03)

# Image Alignment
![2019-11-07_13-08-22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/45b7784b-7b2f-4b94-a5a8-a5a06d16ec46)

**Comment by Stackblocks** [comment]
Displaying OK in Biology, but not in AP Biolgy

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2c6a5b64-b3d9-4fb6-90e0-eea4f8600e73)o

**Comment by helenemccarron** [comment]
For AP Biology, the feature flag needs to be enabled for this to work. This will be fixed when we enable all feature flags for v.v.

**Comment by helenemccarron** [comment]
Please regression test the biology part then send back to v.v and backlog

**Comment by MartaSztuka** [comment]
Displaying good i AP Biology
![Screenshot from 2019-11-26 17-07-50](https://user-images.githubusercontent.com/47241114/69650775-64fdf280-106f-11ea-9d7d-719d504097a3.png)
