### ISSUE TITLE
apbiology & biology: add style to links

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1543]
Style links in Biology and AP Biology with specs from #1360

**Comment by Stackblocks** [comment]
The links are Blue #0000FF instead of #027eb5. I've changed the "view content" color in the screenshot to #027eb5 for comparison.

![2019-11-07_13-21-54.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/24055077-ee42-4b18-a240-814b24fd5fc2)

**Comment by Stackblocks** [comment]
Link color is #017DB4 instead of #027eb5, but when I change the hex value for part of the word "figure" there is little to no visible difference so it may be an artifact of conversion.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ea601000-e2b8-416c-8c5e-5dc890756b84)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8966a756-72ec-4555-943a-842dc946e0c3)
