### ISSUE TITLE
Biology: add styles to figures 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#1568]
The Figures should be styled according to specs included in issue: #1081.

**Comment by Stackblocks** [comment]
# Splash Images
The captions beneath splash images in Biology are unstyled and Figures are left-aligned instead of centered.

### Biology
![2019-11-07_13-08-10.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ef4b7a98-6a70-4dec-8c47-7433d94efabd)

### AP Biology
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d011c939-4d0d-4e31-993d-d8bc0a6d7a03)

# Image Alignment
![2019-11-07_13-08-22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/45b7784b-7b2f-4b94-a5a8-a5a06d16ec46)

**Comment by MartaSztuka** [comment]
Styles added to figures.
![Screenshot from 2019-11-22 15-41-56](https://user-images.githubusercontent.com/47241114/69434840-b7bd6e80-0d3e-11ea-931e-ac8610e43ac3.png)
