### ISSUE TITLE
Math Hat Too Flat

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1597]
# Scenario
Math font's got a real flat hat. Might need a taller font hat.
# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [x
<img width="1062" alt="Screen Shot 2019-11-14 at 3 42 39 PM" src="https://user-images.githubusercontent.com/1895432/68898650-7e10b600-06f5-11ea-9661-3d33d9368d5a.png">
] Yes  [ ] No  (_attach below_)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org  
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by helenemccarron** [comment]
Which book is this in, I am not able to find it in College Physics

**Comment by oscryan** [comment]
chem 2e module 6.3

**Comment by helenemccarron** [comment]
This is how it looks now that I changed the font to STIX-web and unbolded the math:
![2020-01-08_17-06-00](https://user-images.githubusercontent.com/8514591/72023842-80951500-3239-11ea-82de-b5a47f5e2b82.png)

Is this acceptable? For reference, this is a screenshot from wikipedia as comparison (when in doubt, go to wikipedia! I have no clue what is right).
![2020-01-08_17-08-05](https://user-images.githubusercontent.com/8514591/72023892-a1f60100-3239-11ea-81cf-b5f5adff2e47.png)

CC @oscryan and @openstaxalina

**Comment by openstaxalina** [comment]
@helenemccarron thank you for sending this our way for review!  [This website](http://mathworld.wolfram.com/Hat.html) indicates the math hat should be like a caret or circonflexe/circumflex.  I'm not sure how exactly it's marked up.  But is it possible via styling to make it sit higher above the letter (like it does in the right side of Ryan's screenshot and also in Wikipedia) and also taller and narrower?

If this is going to be a ton of work, please let me know so that I can talk with Anthony about the existing display and prioritize any changes.  (With these special characters, we need not only design review but also editorial/pedagogical review.)

**Comment by oscryan** [comment]
@lwtchu had some ideas about the font for the hat iirc

**Comment by helenemccarron** [comment]
From a mathify stand point, I don't think I can do anything other than change the font, if there are other options, I'd like to investigate those first

**Comment by openstaxalina** [comment]
Mathify only takes certain fonts - the only STIX font we can use with Mathify is **STIX-web** as Hélène implemented above.  If we were to change the font, this would apply to all math everywhere.  Documentation does show that STIX is the most comprehensive math font, so we likely need to continue to use that.  We need to confirm with Anthony that the display Hélène pasted above is acceptable.

**Comment by brittweinstein** [comment]
Anthony approves, we can close!
