### ISSUE TITLE
Features have no distinguishing formatting

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1741]
# Scenario
Concepts of Biology features just look like black headers

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

<img width="584" alt="Screen Shot 2020-01-06 at 2 13 08 PM" src="https://user-images.githubusercontent.com/1895432/71845822-c661aa00-308e-11ea-9db6-871dabcd90fb.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by wilkus27** [comment]
It displays in this way because in Biology 2e such note is styled:

![image](https://user-images.githubusercontent.com/40228854/75143774-f4aa5000-56f5-11ea-9a7b-187984148cf1.png)

But in Concepts Biology note from this issue has `non majors` class:

![image](https://user-images.githubusercontent.com/40228854/75143893-36d39180-56f6-11ea-80f4-590bb578224f.png)

@lwtchu what should be done in this case? Are there different specs for notes with class interactive **and** non-major?

**Comment by wilkus27** [comment]
By Larissa: it will be created new design for this note.

**Comment by lwtchu** [comment]
@wilkus27 we can add this to the biology template 

Design: please use condensed icon note (link to learning) 
Title: Concepts in Action

**Comment by MartaSztuka** [comment]
tested on carnival100 branch![Screenshot from 2020-04-02 13-58-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7f7b264b-caf7-4a87-b845-6093546827dd)
