### ISSUE TITLE
equations need spacing after and to be centered

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#1809]
When Marc regression tested math fixes in Bio2e, he noted that the spacing was impacted, as seen in the image below. ![Screen Shot 2020-01-24 at 8.54.07 AM.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/cbf5c223-6ad1-415c-a1d6-d74ddf9e4901)

**Comment by helenemccarron** [comment]
This might be related to styles in equations, I don't think there is anything in mathify that would impact this.

**Comment by lwtchu** [comment]
@brittweinstein i think we can re-title this to fixing `<equations>`  needing spacing after and to be centered.

**Comment by brittweinstein** [comment]
@wilkus27 @ajluk could you please verify this? I know a lot of work has been done on equations recently and want to confirm that this is still an issue. Thanks!

**Comment by ajluk** [comment]
Yes, this is still an issue, because equations in Biology 2e are unnumbered curently but they are missing of specific class (`unnumbered`) to let the styles cover them. They were numbered originally but the numbers have been removed by recipes. I was asking about this issue on the katalyst-devs2 channel here: https://katalysteducation.slack.com/archives/CBW9DFKGF/p1580394488158900

**Comment by lwtchu** [comment]
Will need to do a content fix. Please remove the forced unnumbered. 

We will add a `class="unnumbered"` to the `<equation>`

Corresponding content change: https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/1426

**Comment by ajluk** [comment]
The content on katalyst01.org hasn't changed: 
![image](https://user-images.githubusercontent.com/55203598/74728585-5294ee80-5243-11ea-86c7-5a8c6fabd07a.png)

**Comment by lwtchu** [comment]
i tested this with alan since the batch changes didnt take on katalyst01

![image.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/4db4e941-d3ae-4151-bd7f-7fb2c905025b)

the content change is in the ATP module - and it looks right. i'm going to close this since this is fixable with content.
