### ISSUE TITLE
Symmetry Feedback: Extra Line at end of module

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1998]
# Scenario

![Screen Shot 2020-03-02 at 4 49 27 PM](https://user-images.githubusercontent.com/7863733/75725370-f51e8a00-5ca5-11ea-8cb8-e28231d37d49.png)

cc @lwtchu 

# Acceptance Criteria (required)
- [ ] extra line does not appear

# Test Plan

**Comment by brittany-johnson** [comment]
In the latest physics PDF this issue is no longer occurring, but I added a new page break rule to avoid it happening again in the future
<img width="816" alt="Screen Shot 2020-03-09 at 11 04 40 AM" src="https://user-images.githubusercontent.com/24909007/76235866-b9317a80-61f9-11ea-964b-3c054abe2223.png">

**Comment by MartaSztuka** [comment]
Tested, footnote line appears only with footnote.
![Screenshot from 2020-03-16 11-49-49](https://user-images.githubusercontent.com/47241114/76749128-4afe3200-677c-11ea-8334-bfb2a447407f.png)
![Screenshot from 2020-03-16 11-44-01](https://user-images.githubusercontent.com/47241114/76749141-505b7c80-677c-11ea-8d72-82a5dd6b691b.png)
