### ISSUE TITLE
Symmetry Feedback: Ch. 10, 16, 23 Outline Boxes Too Long

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2025]
# Scenario

![Screen Shot 2020-03-05 at 11 40 41 AM](https://user-images.githubusercontent.com/7863733/76009065-385f3f80-5ed6-11ea-9cfb-3ba5c126a4d4.png)

![Screen Shot 2020-03-05 at 1 20 23 PM](https://user-images.githubusercontent.com/7863733/76017373-18cf1380-5ee4-11ea-9271-4a2260554724.png)

![Screen Shot 2020-03-05 at 3 39 06 PM](https://user-images.githubusercontent.com/7863733/76028116-82a4e880-5ef7-11ea-9b5c-514e649532d8.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
I think this is because of the intro paragraphs. This book might be a good candidate to use option 2 for the chapter outline

**Comment by lwtchu** [comment]
Before we go with that option @helenemccarron there's definitely no way to shrink it right? cause it's basically a table?

**Comment by wilkus27** [comment]
@helenemccarron for explanation, it displays in this way because of my changes from https://github.com/openstax/cnx-recipes/pull/1931/files. 

Previously we had such settings for Chapter Outline: 

![image](https://user-images.githubusercontent.com/40228854/76197879-43271680-61ed-11ea-918d-6ddbd15a0aaf.png)

But then, when intro-text was short and Chapter Outline long, the whole intro-body didn't jump to the second page, but left on the first page and cut Chapter Outline box on the bottom.

What I did is, I moved whole intro-body (which contains intro-text and Chapter Outline):

![image](https://user-images.githubusercontent.com/40228854/76198187-e7a95880-61ed-11ea-8056-0d59c5ae2880.png)

So now it jumps to the second page either if intro-text is long or if Chapter Outline is long. But side effect of this solution is issue described by Alina.

**Comment by brittweinstein** [comment]
Decision: we will go with the full-width chapter outline.

**Comment by ajluk** [comment]
Changes in TDS:
These **FullWidthChapterIntro** shape components properties need to be added as a book specific specs colors to HS Physics:
    **SplashFigureBg** M 126
       background-color: B5
    **OutlineTitle** M.137
      color: B5
    **Outline** M 138
       border-bottom-color': B5
    **OutlineTitleBottomBorder** M139
       border-bottom-color: B5
@lwtchu I have also noticed that the book specific color for college physics isn't set for book in these cells (only in element properties), so I guess the color (B5) need to be set there instead for the same components as above in cells: I 126, I 137, I 138, I 139.
The same for Chemistry (color: B4 cells: E 126, E137, E138) and removed from E153 (Chemistry isn't using that shape anymore).

**Comment by MartaSztuka** [comment]
tested![Screenshot from 2020-03-11 11-07-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0484a4f7-9d21-421c-8257-7662988069b3)
