### ISSUE TITLE
Symmetry Feedback: Weird Extra Box with Equation

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2026]
# Scenario

![Screen Shot 2020-03-05 at 1 23 38 PM](https://user-images.githubusercontent.com/7863733/76017732-b3c7ed80-5ee4-11ea-903e-5fcd9695eacc.png)

![Screen Shot 2020-03-05 at 3 12 05 PM](https://user-images.githubusercontent.com/7863733/76026067-b3831e80-5ef3-11ea-91d2-23080ffad74d.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment]
This equation is nested in a paragraph - would that be why?

**Comment by wilkus27** [comment]
@helenemccarron This is related to https://github.com/openstax/cnx-recipes/issues/1956 and https://github.com/openstax/cnx-recipes/issues/1870. This problem appears in exercises, probably because of conflict between `display: flex`, `display: table` and positioning. That is, `[data-type="problem"]` has property `display: table`, `.os-problem-container` - `display: table-cell` and its child `[data-type="equation"]` - `display: flex`. What is more equation number has property `position: absolute`.

Probably work on point:

![image](https://user-images.githubusercontent.com/40228854/76203660-4fb06c80-61f7-11ea-916c-b25cf2626a6d.png)

from epic https://github.com/openstax/cnx-recipes/issues/2015 will have impact on this problem.

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-03-23 13-18-52](https://user-images.githubusercontent.com/47241114/77316061-f6712e80-6d08-11ea-8ba6-83ff9019bdd5.png)
![Screenshot from 2020-03-23 13-17-46](https://user-images.githubusercontent.com/47241114/77316064-f7a25b80-6d08-11ea-95aa-cd5ef7a2533f.png)
