### ISSUE TITLE
Figures in EoC not centered. 

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2034]
Some figures are not aligned to center.
![Screenshot from 2020-03-10 12-00-51](https://user-images.githubusercontent.com/47241114/76307158-97eb8f80-62c8-11ea-964b-37ba965052aa.png)

**Comment by wilkus27** [comment]
Related with https://github.com/openstax/cnx-recipes/issues/1870. 

The problem is that those figures are children of `.os-problem-container` which has property `display: table-cell` and then width of this container is equal to width of the widest child. So figures display at the center of the widest sibling.

**Comment by MartaSztuka** [comment]
tested
![Screenshot from 2020-03-23 13-26-04](https://user-images.githubusercontent.com/47241114/77316545-e4dc5680-6d09-11ea-8cfc-021f26a50d13.png)
