### ISSUE TITLE
Explore viability of a Javascript only solution for Speed Up Baking

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/cnx-recipes#2035]
# Description
Explore the performance characteristics of a pure Javascript solution for performing selections and applying "recipes".

# Acceptance Criteria
Create minimal test, and get performance metrics for comparison against other potential solutions. We will also write a report detailing the outcomes.

**Comment by tomjw64** [comment]
## Report
JP suggested we take a look at reducing complexity by using a single language to run all steps. Since we plan to leverage JSX for an interface into baking, the choice of language must be JavaScript (NodeJS).
NodeJS does not support any shared memory paradigms, so the only way to take advantage of multiple cores is with multithreading (via the Worker api) or multiprocessing (via fork()) and parsing a book multiple times for selection, once per each thread/process.
### Libraries
We tried 3 alternatives for parsing xml and resolving xpath selectors. 

1. libxmljs - It worked, but it seemed to hang on a single selector and never resolve it. I quit the process after 5 minutes
2. wicked-good-xpath - Couldn't even get it running
3. JSDOM - works, but resolving a single xpath selector in our tests took 22 seconds.
4. xmldom w/ xpath library for selection - Works. On my machine, we were able to resolve around 100 selectors in around 65 seconds without multiprocessing, and in around 23 seconds at best with multiprocessing (4 workers on a 12 core machine - adding more workers beyond this did not improve performance). Seems the most promising out of all the options in the NodeJS ecosystem. Not incredibly impressive though. Since we run around 800 selectors for baking currently, we estimate baking times on the order of 3-5 minutes, which is not necessarily an improvement on today.
