### ISSUE TITLE
Footnote in note that breaks across pages

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2114]
# What happened?
When a footnote call out appears within a paragraph or table that breaks across pages - it gets pushed to the second page even if it's on the first page.

Also when there's no more room at the bottom, it breaks.

~- within a note~
~- the note breaks across two pages~
~- it appears before the page break~

TO SEARCH: look for the word `swine farms` 🐷 , `ecosystem environment`, `a study in jordan`
 
<img width="715" alt="Screen Shot 2020-03-26 at 9 47 17 AM" src="https://user-images.githubusercontent.com/11299125/77660402-450c0c00-6f47-11ea-8b2b-2ca67ba1a1a5.png">
<img width="598" alt="Screen Shot 2020-03-26 at 9 47 12 AM" src="https://user-images.githubusercontent.com/11299125/77660409-45a4a280-6f47-11ea-84e3-c975448b60ab.png">

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**:
- **URL/Server**: 
- **Location (page number, chapter/section)**:
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

(_attach here (please clearly label what environment each screenshot came from)_)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by lwtchu** [comment]
frog scream: i found a case where it's working
<img width="553" alt="Screen Shot 2020-03-26 at 10 56 04 AM" src="https://user-images.githubusercontent.com/11299125/77667594-6de4cf00-6f50-11ea-9820-60dca460b2de.png">

**Comment by lwtchu** [comment]
<img width="554" alt="Screen Shot 2020-03-26 at 10 56 59 AM" src="https://user-images.githubusercontent.com/11299125/77667687-894fda00-6f50-11ea-90a9-c1a54cf33a2f.png">
found this instance. 

i think it's more of when the paragraph breaks

**Comment by lwtchu** [comment]
<img width="590" alt="Screen Shot 2020-03-26 at 11 02 22 AM" src="https://user-images.githubusercontent.com/11299125/77668659-ae911800-6f51-11ea-9344-38009f653357.png">
also footnotes get pushed if there's no room

**Comment by brittweinstein** [comment]
@lwtchu, @andymuddimer suggested maybe editing this in the content -- Larissa would you or a CM have time to take a look at this?

**Comment by lwtchu** [comment]
@brittweinstein since we can't control where page breaks happen, editing content means every time we generate the PDF, we'll have to check all the foot notes and edit them. I don't think this is a good idea. And if we were to edit them, footnotes are such a targeted specific place, I"m not sure I can put the call out anywhere else.

**Comment by wilkus27** [comment]
@brittweinstein I look into it as you asked, and probably it can be resolved with property `prince-footnote-policy: keep-with-line`, but for now I can't try to apply this. First we need to merge Phil's changes https://github.com/openstax/rhaptos.cnxmlutils/pull/169 and add again BrittneyJ's work from https://github.com/openstax/cnx-recipes/pull/2076 which was reverted.

**Comment by brittany-johnson** [comment]
I will begin working on this again, but the PDF to test it cannot be generated (easily) until the footnote work is merged

**Comment by brittany-johnson** [comment]
Still investigating without any success. Adding a comment to document solutions I've tried.
![Screen Shot 2020-05-12 at 3 49 04 PM](https://user-images.githubusercontent.com/24909007/81744280-9e34ee00-9468-11ea-87a9-c6701ff78ca7.png)

**Comment by brittany-johnson** [comment]
This card requires a recipe fix. Will hold until footnote recipe and transform work is on production

**Comment by wilkus27** [comment]
## TO SUM UP

This is how markup looks now in baked xhtml with the newest recipes changes:

![image](https://user-images.githubusercontent.com/40228854/112172914-66a0e180-8bf5-11eb-950f-b70ab83699c0.png)

With Prince we are moving text from `<aside>` to the footnote:

![image](https://user-images.githubusercontent.com/40228854/112173307-baabc600-8bf5-11eb-86e5-d473ecdb60bc.png)

Prince adds autogenerated footnotes reference in place where the our `aside` tag is. We are hiding it in styles, because we are using our own references (`<a>` with `[role="doc-noteref"]` - look on the first screenshot). But Prince puts footnotes on the page where its autogenerated references are (so right under the paragraph with our footnote reference). 

Within work on issue https://github.com/openstax/cnx-recipes/issues/3315 I added class `has-noteref` to paragraphs which contain our references.

To fix issue from this card I added `page-break-inside: avoid` property to these paragraphs. In that way (in most cases) our references should be on the same page where are references autogenerated by Prince, so on the same page where are footnotes.

### NOTE
**These changes (https://github.com/openstax/cnx-recipes/pull/3732) affect all books from all themes.**

**Comment by lwtchu** [comment]
@wilkus27 :O interesting! i will meet with alina about this to figure out how to approach testing.

**Comment by lwtchu** [comment]
@wilkus27 for testing, the CMs can do a more robust regression testing for high priority titles when this merges and goes to staging - @MartaSztuka do you have time before code freeze to verify https://github.com/openstax/cnx-recipes/issues/3548#issuecomment-805689262 and then check the polish books?

**Comment by MartaSztuka** [comment]
@lwtchu probably I do.
##### PASSED![Screenshot from 2021-03-24 17-48-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e809276b-cb84-407e-b161-3ca60feb6ed5)![Screenshot from 2021-03-24 17-50-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/314d81fb-8a3c-4ac0-a7aa-73c8a24c5ce8)![Screenshot from 2021-03-24 17-50-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/97b1e4da-3aba-4ded-9199-71bfc08c132d)
