### ISSUE TITLE
Create Polish Psychology Recipe

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2163]
# Scenario

Natalia and/or Anna will create the Polish version of the Psychology recipe, to support publishing the Polish translation ~August 2020.

# Acceptance Criteria (required)

# Test Plan

**Comment by wilkus27** [comment]
Informations for tester
-------
Known issues related with current content (https://katalyst01.cnx.org/contents/84JIUkA_@1.103:rs_ilJom@4/1-1-Wprowadzenie) not recipes.

### I. Missing elements

#### 1. Preface
#### 2. Learning Objectives

### II. Modules with wrong display

#### 1. Introduction page

All introduction pages are numbered for now:

![image](https://user-images.githubusercontent.com/40228854/88153990-78fdf200-cc06-11ea-92d7-f37012d1f965.png)

It is caused because they are missing `introduction` class.

#### 2. Indexes

For now, all terms are inside one module `Skorowidz rzeczowy`. When proper attributes be added to content, there will be three indexes: `Skorowidz rzeczowy`, `Skorowidz nazwisk`, `Skorowidz terminów obcojęzycznych`.

### III. Elements with wrong display

#### 1. Notes

Notes contain additional para with english name of note, and para with subtitle:

![image](https://user-images.githubusercontent.com/40228854/88155376-4e149d80-cc08-11ea-9cc3-748d6bbf7130.png)

First para will be removed, and the second one will be changed to div with `[data-type="title"]`.

#### 2. EOC exercises

Actually it's not content related, but I put this here for information. For now solutions to exercises from EOC are placed below them:

![image](https://user-images.githubusercontent.com/40228854/88156035-283bc880-cc09-11ea-8673-25fef0335d2e.png)

We haven't made a decision yet what to do with them. They will be moved to Answer Key or suppressed.

**Comment by MartaSztuka** [comment]
## Tests results
### 1. Full stop is missing and there is random 'Psychologia' in italic.![Screenshot from 2020-08-26 14-51-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1b7fd51c-35ef-4d2b-82ab-6aee5dbde3a2)
### 2. This Figure is removed in english version which affects further numbering![Screenshot from 2020-08-26 15-34-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bf4e8bd4-26a8-42e8-9d81-32b999d303a7)
### 3. Translation can be edited out![Screenshot from 2020-08-26 15-39-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b3aba9aa-7bd4-44f6-8122-43862477a19b)
### 4. Typo![Screenshot from 2020-08-26 15-44-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/75ea5235-ebff-43d4-9a57-b6b7e4d5887c)
### 5. Missing space![Screenshot from 2020-08-26 15-48-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd2abf8c-93a5-46e4-a1e3-327618fff578)
### 6. Figure doesn't show![Screenshot from 2020-08-26 16-05-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6acf398e-388d-4ec3-9cf1-02921fbac498)
### 7. Missing illustration (1.5 Kariera zawodowa psychologa)![Screenshot from 2020-08-26 16-08-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6cad295f-fdcf-452d-b9ce-b205b5b9760e)
### 8. Missing table (1.5 Kariera zawodowa psychologa)![Screenshot from 2020-08-26 16-10-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3cb13480-bf8a-4f96-a968-27fe882fd3d9)
### 9. Term '-logia' probably should be with 'L' terms![Screenshot from 2020-08-26 16-12-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8cea0905-ebe0-4732-b987-77b74e513f93)
### 10. Bracket isn't complete, content might be missing too![Screenshot from 2020-08-26 16-14-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a3bf0ae-912c-4c73-8f58-f1b004163c92)
### 11. Bullets instead of ABCs![Screenshot from 2020-08-26 16-52-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cb88d30d-3343-4d70-b6c1-0ba0be6152a1)
### 12. One review question is missing![Screenshot from 2020-08-26 16-22-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b297eaf5-52d7-40c3-9bcf-0c9308f128b7)

**Comment by wilkus27** [comment]
@MartaSztuka I created issues for these problems in Polish content repo https://github.com/openstax-poland/content/issues. Also there is one issue for recipes: https://github.com/openstax/cnx-recipes/issues/2739 for problems **9** and **15**.

I'm closing this issue.
