### ISSUE TITLE
developmental math - review exercises structure (eoc section)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2164]
<img width="586" alt="Screen Shot 2020-04-06 at 5 09 37 PM" src="https://user-images.githubusercontent.com/11299125/78609926-6b745600-7829-11ea-824d-b8b5d9736521.png">

This section is a little more complicated than most EOC sections. I will have a list of requirements here to make it easier to test. 

This is ONLY for EOC Secions with class
- [ ] `class="review-exercises"` - broken up by sub section 
 - [ ] `class="practice-test"` - NOT broken up by sub section

### Checklist
- [ ] Paragraph specs
- [ ] 3 column `<exercises>`
- [ ] Implementation of `<exercise class=”material-set-2”> ` 

### Paragraph specs
All `<para>` that are NOT nested in exercises are styled like the following
Font: Noto Sans
Treatment: Italics
Font size: font scale(0)
Color: B2:   `#1E7E91`

### `material-set-2` class
The `material-set-2` class sets the `<exercise>` in a two column format. This is used on things that might be too wide for a 3 column setting.

This is a sample from chapter 7 review exercises of the `material-set-2` class in action
<img width="636" alt="Screen Shot 2020-04-08 at 12 12 07 PM" src="https://user-images.githubusercontent.com/11299125/78813160-36cfde00-7992-11ea-880d-d5f34d0b0722.png">

**Comment by ajluk** [comment]
Hi @lwtchu I was styling Review Exercises today and noticed there is a problem with section link titles (with current markup they are appearing as h5): 
![image](https://user-images.githubusercontent.com/55203598/86145887-cac7c680-baf7-11ea-8016-3489a33e8e16.png)

It is because they are added in the content (assemble file):
![image](https://user-images.githubusercontent.com/55203598/86143553-db2a7200-baf4-11ea-92e8-eb295074362e.png)
and after changes in recipes (moving Review Exercises to Exercises composite chapter they land in the h5 title tag).

In the carnival theme the section link titles were added and counted via recipes. As you can see on the screenshot below there was no section title in the content there (screenshot from University Physics): 
![image](https://user-images.githubusercontent.com/55203598/86144139-94894780-baf5-11ea-9cdd-3b534ff70cb8.png)
And the sections with exercises were placed at the end of each module in every chapter: 
![image](https://user-images.githubusercontent.com/55203598/86144699-4aed2c80-baf6-11ea-953c-3179e9f42a84.png)

But in the corn theme books (dev-math, precalculus) the exercises are placed  in the content only at the end of the last module in every chapter: 
![image](https://user-images.githubusercontent.com/55203598/86145386-28a7de80-baf7-11ea-843d-e7d565660a25.png)

Will it be very complicated/time consuming to move the exercises from the last module to the end of the corresponding each module in every chapter in the content? 
Otherwise we need to do rather complicated changes in the recipes. The content change needs to be done in all 6 dev-math and precalculus books and maybe in calculus (but that we don't know yet). Let me know which solution you think will be better here?

**Comment by lwtchu** [comment]
Let's leave the content as is and remove the numbering.

Let's style that title as a H5 and leave it as is. I can update the screenshot once it's implemented

**Comment by ajluk** [comment]
@lwtchu This is how it looks now in pdf with the h5 section link title with basic styles for h5: 
![image](https://user-images.githubusercontent.com/55203598/86225099-11660100-bb8a-11ea-8827-46b7e07ed047.png)
Shoud I change something?

**Comment by ajluk** [comment]
@lwtchu This how the exercises look now in pdf after styling (the h5 section link is pointed): 
![image](https://user-images.githubusercontent.com/55203598/86227634-9acb0280-bb8d-11ea-9d2a-d6a058643a3c.png)
![image](https://user-images.githubusercontent.com/55203598/86227664-a74f5b00-bb8d-11ea-98a7-ba4f80f0c04c.png)
![image](https://user-images.githubusercontent.com/55203598/86227706-b930fe00-bb8d-11ea-8aab-b3228a2e3a48.png)
Should I change something?

**Comment by ajluk** [comment]
Specs added: 
![image](https://user-images.githubusercontent.com/55203598/86228140-4f652400-bb8e-11ea-857f-aa163cb9c9f0.png)
**H5 Link title**
font-family: Roboto Slab, serif, StixGeneral;
font-size: 1rem;
line-height: 1.5rem;

![image](https://user-images.githubusercontent.com/55203598/86228276-7885b480-bb8e-11ea-841c-c1f99a40cb5d.png)
ExercisesModuleContainer 
margin-bottom: 1.4rem;
width: 100%;
display: table;

![image](https://user-images.githubusercontent.com/55203598/86228928-4cb6fe80-bb8f-11ea-80a1-eb836cc31ee2.png)
ExercisesParagraphTitle
color: #1E7E91;
font-family: Noto Sans, sans-serif, StixGeneral;
font-size: 1rem;
line-height: 1.5rem;
margin-top: 0.7rem;
font-style: normal;
display: block;
break-after: avoid;
break-inside: avoid;

![image](https://user-images.githubusercontent.com/55203598/86228975-5c364780-bb8f-11ea-832d-cc5ff191759e.png)
ExercisesParagraphTitleItalic
color: #1E7E91;
font-family: Noto Sans, sans-serif, StixGeneral;
font-size: 1rem;
line-height: 1.5rem;
font-style: italic;
margin-top: 0.7rem;
width: 100%;
break-after: avoid;
break-inside: avoid;

![image](https://user-images.githubusercontent.com/55203598/86229118-8a1b8c00-bb8f-11ea-9011-b2f4df841023.png)
ExerciseContainer
    margin-bottom: 1.4rem;
    display: inline-block;
    vertical-align: top;
    width: 33%;
    padding-right: 0.7rem;

![image](https://user-images.githubusercontent.com/55203598/86229303-ccdd6400-bb8f-11ea-972e-d67ab9a9b81f.png)
ProblemContainer
    display: table-cell;
    width: 100%;

![image](https://user-images.githubusercontent.com/55203598/86229435-fe562f80-bb8f-11ea-9508-760d16cade5d.png)
ProblemContainerWithImageOnTop
display: table-cell;
vertical-align: bottom;
padding-top: 0.7rem;
width: 100%;

![image](https://user-images.githubusercontent.com/55203598/86229596-3fe6da80-bb90-11ea-9dfa-c955d2729e75.png)
Image
max-width: 100%;

**Comment by brittweinstein** [comment]
@lwtchu I just wanted to confirm that the screenshots above are what you expect to see?

**Comment by lwtchu** [comment]
This is fine. We can move on with testing for this
