### ISSUE TITLE
corn theme: figure/table number and caption styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2185]
<img width="799" alt="Screen Shot 2020-04-09 at 10 20 25 AM" src="https://user-images.githubusercontent.com/11299125/78911658-3562ec00-7a4c-11ea-98f5-477648a81af8.png">

Font: Noto Sans
Color: B1:   `#093D4C`
Figure/table number treatment: bold
Figure/table title (if any) treatment: bold
Font size: font-scale(0)

Note: FOR ALL figure captions, including splash images.

**Comment by ajluk** [comment]
@lwtchu are the specs for caption in the Splash Figure the same?

**Comment by lwtchu** [comment]
@ajluk yes

**Comment by ajluk** [comment]
@lwtchu could you provide the specs for Caption Text as well (especially color, is fon-family and size the same as in the title and number from above?): 
![image](https://user-images.githubusercontent.com/55203598/82571959-0465f300-9b84-11ea-856c-21d1ab19dd50.png)

**Comment by lwtchu** [comment]
@ajluk it's the same color and font family and size. only difference is it's not bold.

**Comment by ajluk** [comment]
Added Specs in Introduction Page:

![image](https://user-images.githubusercontent.com/55203598/84178410-ac385780-aa84-11ea-86b7-3d29a632e554.png)
**CaptionContainer**
padding-top: 1rem;
padding-bottom: 2rem;

![image](https://user-images.githubusercontent.com/55203598/84178497-ceca7080-aa84-11ea-89af-d84344607836.png)
**CaptionTitleLabel**
font-family: Noto Sans, sans-serif;
font-weight: bold;
font-size: 1rem;
color: #093D4C;

![image](https://user-images.githubusercontent.com/55203598/84178626-00433c00-aa85-11ea-907c-3d3f70dd7e5e.png)
**CaptionNumber**
font-family: Noto Sans, sans-serif;
font-weight: bold;
font-size: 1rem;
color: #093D4C;
margin-right: 8px;

![image](https://user-images.githubusercontent.com/55203598/84178726-31237100-aa85-11ea-8d35-2c2b7bc459eb.png)
**CaptionText**
font-family: Noto Sans, sans-serif;
font-size: 1rem;
color: #093D4C;

**CaptionTitle**
font-family: Noto Sans, sans-serif;
font-weight: bold;
font-size: 1rem;
color: #093D4C;

**CaptionDivider**
  margin: 0,

**Comment by lwtchu** [comment]
thanks! this looks good

**Comment by ajluk** [comment]
@lwtchu I've been working on styling figures in Prealgebra 2e and this how they look now: 
![image](https://user-images.githubusercontent.com/55203598/86478377-77998200-bd4a-11ea-9b06-551e2b325ca9.png)
![image](https://user-images.githubusercontent.com/55203598/86478467-939d2380-bd4a-11ea-9c77-b58242513828.png)
![image](https://user-images.githubusercontent.com/55203598/86478697-f1317000-bd4a-11ea-8a6c-00d1be779178.png)
Should there something should be changed?

Specs added:
![image](https://user-images.githubusercontent.com/55203598/86479111-d01d4f00-bd4b-11ea-87a0-076b0346a929.png)
**Figure**
display: table;
margin-left: auto;
margin-right: auto;
![image](https://user-images.githubusercontent.com/55203598/86479209-00fd8400-bd4c-11ea-8f5d-8f0de8432709.png)
**CaptionContainer**
display: table;
margin-left: auto;
margin-right: auto;
margin-bottom: 0.7rem;
![image](https://user-images.githubusercontent.com/55203598/86479295-27bbba80-bd4c-11ea-8ab0-32db2ad25b6b.png)
**CaptionTitleLabel**
font-family: Noto Sans, sans-serif, StixGeneral;
font-weight: bold;
font-size: 1rem;
color: #093D4C;
![image](https://user-images.githubusercontent.com/55203598/86479403-618cc100-bd4c-11ea-9003-e1f9755164de.png)
**CaptionNumber**
font-family: Noto Sans, sans-serif, StixGeneral;
font-weight: bold;
font-size: 1rem;
color: #093D4C;
margin-right: 8px;
![Uploading image.png…]()
**CaptionText**
font-family: Noto Sans, sans-serif, StixGeneral;
font-size: 1rem;
color: #093D4C;
**CaptionTitle**
ont-family: Noto Sans, sans-serif, StixGeneral;
font-weight: bold;
font-size: 1rem;
color: #093D4C;

I have removed 
**CaptionDivider**
margin: 0,
from caption properties, because it is not needed here, Chapter Intro or Tables.

**Comment by lwtchu** [comment]
@ajluk one of the images is broken, but i think it looks good from what you've shown

**Comment by ajluk** [comment]
@lwtchu I have added properties to **Caption Container** for Tables in general (during working on Formula Review):
            display: table-caption,
            caption-side: bottom,
            prince-caption-page: all,
