### ISSUE TITLE
corn theme - table design

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2204]
<img width="648" alt="Screen Shot 2020-04-10 at 4 25 55 PM" src="https://user-images.githubusercontent.com/11299125/79024267-0f227680-7b48-11ea-9265-0e5bd2cd28fa.png">
<img width="836" alt="Screen Shot 2020-04-10 at 4 25 37 PM" src="https://user-images.githubusercontent.com/11299125/79024268-0fbb0d00-7b48-11ea-8611-1415be2eeb3e.png">
<img width="665" alt="Screen Shot 2020-04-10 at 4 25 24 PM" src="https://user-images.githubusercontent.com/11299125/79024269-1053a380-7b48-11ea-8b99-7dbc1fdfeeec.png">

## Alignment
These tables are centered on the page. 

### Cell borders
Cell border color: Grey1   `#F1F1F1`
Cell border width: 1px (0.09 rem)
Applies to border-left, right, top, bottom

### Cell fill
Color: `#FFFFFF`

### Font
Font: Noto Sans
Size: font-scale(0)
Color: B1:   `#093D4C`
Alignment should be controlled by the content

### Header row
No border
Fill color: B1:   `#093D4C`
Font weight: bold
Color: `#FFFFFF`

## Header column/row `class="column-header"`
Same as above but this will apply the header row specs to the first column as well.
See Table 1.4 in example screenshot

## Padding
padding-top: table-v-spacing(1), (0.7rem) 
padding-bottom: table-v-spacing(1), (0.7rem) 
padding-right: table-h-spacing(1), (0.7rem) 
padding-left: table-h-spacing(1), (0.7rem)

margin-bottom: table-v-spacing(2), (1.4rem)

border-top-right-radius: 0.25rem,
border-top-right-radius: 0.25rem,
border-bottom-right-radius: 0.25rem,
border-bottom-left-radius: 0.25rem,

### Alignment
vertical-align: top,

**Comment by ajluk** [comment]
@lwtchu I have added padding which we have used in the previous theme to th and td elements: 
` padding-top: table-v-spacing(1),
        padding-bottom: table-v-spacing(1),
        padding-right: table-h-spacing(1),
        padding-left: table-h-spacing(1),`

**Comment by ajluk** [comment]
@lwtchu I have added paddings which we have used in the previous theme to th (table head cell)  and td (table data) elements: 
` padding-top: table-v-spacing(1), (0.7rem)
        padding-bottom: table-v-spacing(1), (0.7rem)
        padding-right: table-h-spacing(1), (0.7rem)
        padding-left: table-h-spacing(1),` (0.7rem)
and margin-bottom to the table container (`.os-table`) - also used in the previous theme
` margin-bottom: table-v-spacing(2),` (1.4rem)
I have also added the border radiuses for:
first th (table head cell) (`thead>tr>th:firstchild`)
` border-top-right-radius: 0.25rem,`
last th (table head cell )(`thead>tr>th:lastchild`)
` border-top-right-radius: 0.25rem,`
last td (table data) child in the last tr (`tr:last-of-type > td:lastchild`)
` border-bottom-right-radius: 0.25rem,` 
first td (table data) child in the last tr  (`tr:last-of-type > td:lastchild`)
` border-bottom-left-radius: 0.25rem,`
and added `vertical-align: top,` to td elements because otherwise as you can see in the first column in table above the text it alligned in the middle in pdf:
![image](https://user-images.githubusercontent.com/55203598/82671336-f7f2a080-9c3e-11ea-9d81-d6f869f3e3fa.png)

**Now the table looks like this, let me know if it is acceptable:** 

![image](https://user-images.githubusercontent.com/55203598/82676479-bfef5b80-9c46-11ea-8886-316b96bf8645.png)
or the space between the table and the table caption should be wider like on the screenshot you pasted above: 
![image](https://user-images.githubusercontent.com/55203598/82671457-2cfef300-9c3f-11ea-82b2-a67a1e021e24.png)

**Comment by lwtchu** [comment]
@ajluk i think what you have is fine. i think it's good to keep it consistent with the other padding/spacing.

**Comment by brittweinstein** [comment]
@ajluk please put points on this card

**Comment by ajluk** [comment]
@lwtchu the specs for Column Header Tables are the same as above except I have changed the left and righ padding for Td:

**Comment by lwtchu** [comment]
@ajluk looks good thanks!
