### ISSUE TITLE
CLEANUP: Section Key Terms

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2221]
[Cleanup doc](https://docs.google.com/document/d/10qrKjBt3sGoZR8KaW1xwUSApVZiRPtFxce2WkRP2LJ0/edit#)

- [x] Investigate if this can be made to use the table components to simplify

- [ ] Replace the ones that match existing table components to reduce uniques

**Comment by ajluk** [comment]
After conversation with Larissa (https://katalysteducation.slack.com/archives/CBW9DFKGF/p1589456742238300) I have removed all the section key terms files, because right now after tables cleaning it is using the Unnumbered Unstyled table shape and the look of the table isn't much different than when we have separate styles for it before the tables cleaning. The only differences were margin-bottom of the table which previously was set to 0 and padding-left of the table data which previously was set to 0 as well. Previously the styles of the tables after cleaning overwrites it as you can see in the output files (there is no change). This is how it looks now in the html file:
![image](https://user-images.githubusercontent.com/55203598/81954539-45508b80-9609-11ea-89e1-cd8c5e0d4f11.png)
and in pdf file:
![image](https://user-images.githubusercontent.com/55203598/81954586-51d4e400-9609-11ea-98ab-2f44b521b00f.png)
How it looked before:
![image](https://user-images.githubusercontent.com/55203598/81954647-64e7b400-9609-11ea-981b-0fd64f5a7aea.png)

**Comment by ajluk** [comment]
@MartaSztuka >> Information for testing purposes: 
Now this par should look like this: 
![image](https://user-images.githubusercontent.com/55203598/82457579-de721d00-9ab5-11ea-9189-9e55bc2d8093.png)

**Comment by MartaSztuka** [comment]
![Screenshot from 2020-05-20 16-58-51](https://user-images.githubusercontent.com/47241114/82463135-bcc86400-9abc-11ea-8b32-6e0d74ef01cb.png)
