### ISSUE TITLE
Symbols in Index

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2265]
Words that start with polish letter in Index shouldn't be under `Symbols` header at the beginning, but segregated by polish alphabet.
![Screenshot from 2020-04-29 16-43-29](https://user-images.githubusercontent.com/47241114/80609623-9b81d400-8a38-11ea-904e-f41ddeb35024.png)

**Comment by wilkus27** [comment]
This problem was investigated here: https://github.com/openstax/cnx-recipes/issues/1042. It still appears. What is more, previously issue was resolved locally. It didn't work on webview. At this moment it doesn't work locally as well.

@brittany-johnson do you think it might be related with issues: https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/924 and https://github.com/openstax/cnx/wiki/Character-encoding-bug-(Polish-books)?

Should we wait, and test it after those changes will be done?

**Comment by brittany-johnson** [comment]
@ckline-tryptic Hello! Can you confirm if this issue is related to the work being done on these two issues: 
https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/924 

https://github.com/openstax/cnx/wiki/Character-encoding-bug-(Polish-books)

Thank you!

**Comment by MartaSztuka** [comment]
# PASSED
## Diacritics in Index
### Fizyka 1![Screenshot from 2020-08-05 17-42-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0bc9cf80-4163-499f-b4df-438c9ff542ec)![Screenshot from 2020-08-05 17-42-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/384ed70b-ab58-4b3b-9e96-9f02d4e23c3a)
### Fizyka 2![Screenshot from 2020-08-05 17-49-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/330ac9a9-d765-4cbd-8001-8e1ccc00d9a5)![Screenshot from 2020-08-05 17-49-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0f492a0a-3a27-497e-8592-004f4bebd0b6)
### Fizyka 3![Screenshot from 2020-08-05 18-25-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f375f33e-bb0e-431a-821c-c27bba3498f3)![Screenshot from 2020-08-05 18-25-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57ae9e98-9941-4566-9000-ea400628c9c3)![Screenshot from 2020-08-05 18-24-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e14ba175-2fc9-4389-9dc4-6e34cb0fdb9c)
