### ISSUE TITLE
statistics - stats lab feature (full page section note feature)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2273]
<img width="752" alt="Screen Shot 2020-05-04 at 11 20 36 AM" src="https://user-images.githubusercontent.com/11299125/80988583-4e677e80-8df9-11ea-92b9-68388104e82d.png">

`class="statistics lab"` on a `<note>`

# Color bar
height: 25px/2.27 rem 
color: `#C6CE33`
spans edge to edge - please include 0.125in bleed

# Feature name
Stats Lab
Font: Roboto Slab
Color: B1:   `#093D4C`
style: bold
size: font-scale(1)

# Title from `<title>`
Goes under the bar
Font: Noto Sans
Style: Bold
Size: font-scale(1)

# Line at end of feature
thickness: 1px
color: `#C6CE33`

# Icon
https://drive.google.com/open?id=1QNbOWVYNrAljoLrF4yDNtGsNTLf15xzH

**Comment by ajluk** [comment]
Hi @lwtchu! This is how the note looks like after styling in pdf: 

![image](https://user-images.githubusercontent.com/55203598/89816383-ca830800-db46-11ea-84a2-e3892a0c49c4.png)
The module title header above the note is black, because I'm on different branch, where the titles aren't styled yet.

Here is the screenshot with line at the end:
![image](https://user-images.githubusercontent.com/55203598/89816458-e5ee1300-db46-11ea-903a-3689a83706e1.png)

Let me know if it looks ok or I should change something?

Here are the specs I have added:

![image](https://user-images.githubusercontent.com/55203598/89819931-7549f500-db4c-11ea-8166-7582082ac38b.png)

Container:
    margin-bottom: 2.1rem;
    margin-top: 2.1rem;

![image](https://user-images.githubusercontent.com/55203598/89820564-81828200-db4d-11ea-93ec-d87d4276c017.png)

Title (includes bleeds)
font-size: 1.2rem;
line-height: 1.5rem;
margin-bottom: 1.4rem;
background-color: #C6CE33;
margin-right: -9.2rem;
padding-right: 9.2rem;
margin-left: -9.2rem;
padding-left: 9.2rem;
display: flex;
justify-content: start;
height: 3rem;

![image](https://user-images.githubusercontent.com/55203598/89820687-af67c680-db4d-11ea-9416-58e7474c1ddb.png)

Icon

    background-size: contain;
    height: 4rem;
    width: 4rem;
    margin-right: 8px;
    content: '';
    display: inline-block;
    position: relative;
    bottom: 1rem;

![image](https://user-images.githubusercontent.com/55203598/89820864-f35acb80-db4d-11ea-8ef2-1dd57444d80f.png)

TitleLabel
    color: #093D4C;
    font-family: Roboto Slab, serif, StixGeneral;
    font-weight: bold;
    padding-right: 8px;
    padding-top: 8px;
    display: inline-block;
    float: left;

![image](https://user-images.githubusercontent.com/55203598/89820968-1e451f80-db4e-11ea-8bab-9427c4d275ac.png)

TitleNumber

**Comment by lwtchu** [comment]
@ajluk could you remove the numbering? other than that, the feature looks good 🤩

**Comment by ajluk** [comment]
@lwtchu I have removed the numbering in the recipes: 
![image](https://user-images.githubusercontent.com/55203598/89825089-6109f600-db54-11ea-8855-1d221f66feab.png)

**Comment by lwtchu** [comment]
nice nice looks good ~

**Comment by ajluk** [comment]
@lwtchu I have found this note in HS Statistics, so I have added the label for this book and ask Marta to test it there as well.
