### ISSUE TITLE
Problem with letter spacing

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2389]
In some places letters stick to each other. What is odd, the same words look different in different places.

![image](https://user-images.githubusercontent.com/40228854/83521188-2abe5380-a4df-11ea-9db6-513aa32f2b39.png)

**Comment by brittweinstein** [comment]
@wilkus27 what books does this occur in?

**Comment by wilkus27** [comment]
@brittweinstein It was noticed in Prealgebra 2e. Other books were not checked yet.

**Comment by Stackblocks** [comment]
Unable to replicate the issue in the mathified xhtml or the PDF of Prealgebra 2e baked on Q.Q. Screenshots below at 75% and 120% zoom for comparison. 

I believe this was just a rendering issue with Adobe, since i've seen similar things in the past with elements moving at various zoom levels.

Going to run a couple more tests and then close this out if I can't find anything.

![2020-08-13_09-43-10.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/4f7588df-bdbf-466a-a10f-f3c2750be696)
