### ISSUE TITLE
issue: baked styles math - fractions look really squished 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2506]
# What happened?

![image](https://user-images.githubusercontent.com/11299125/87974063-18987480-ca8f-11ea-8b49-31013e774b3a.png)

This is from the College Algebra with Coreq collection.

Is there a way to better optimize math and the way they render in line? Sometimes they get squished to fit within the line but before they used to just expand in text:

![Screen Shot 2020-07-20 at 1 45 50 PM](https://user-images.githubusercontent.com/11299125/87974246-5e553d00-ca8f-11ea-9418-88bbf8e0db04.png)
(example from existing prealgebra pdf)

**Comment by lwtchu** [comment]
marking as high priority since the really small math compromises accessibility

**Comment by lwtchu** [comment]
Closer comparison:

This you can see the fractions are trying to stay within the confines of the line height.
![Screen Shot 2020-07-20 at 1 48 36 PM](https://user-images.githubusercontent.com/11299125/87974454-bab85c80-ca8f-11ea-97c8-52ed560b9f32.png)

This one it retains the base font size for the fraction and is able to expand past the line height.
![Screen Shot 2020-07-20 at 1 48 29 PM](https://user-images.githubusercontent.com/11299125/87974457-bb50f300-ca8f-11ea-99ab-6fcc8eee6ffe.png)

**Comment by brittany-johnson** [comment]
Currently having issues creating a mathified PDF on my computer. Moving to another high priority issue and unassigning myself in the meantime. Will come back to this after if it has not been picked up after I've finished the unnumbered splash issue

**Comment by Stackblocks** [comment]
## Update
We’ve tried a variety of solutions to either give the equations more room to expand (they didn’t) or make them bigger (their peers also expanded) so we’re running a little thin on standard solutions. We’ll try and find more esoteric stuff but we may want to examine content solutions as well, since it’s only the multi-stack fractions (or fractions with exponents) that behave like this. There’s nothing unique to these particular fractions that lets us isolate them from other math SVGs in paragraphs so any programmatic fixes we’ve tried have been applied too broadly.

Brittany J mentioned that there may be a way for something to be done in Mathify, but that’ll involve ce-tech who she’s meeting with today.

## Screenshots
![image](https://user-images.githubusercontent.com/12678235/88932765-2050d980-d244-11ea-9971-ff36539b71e1.png)
![image](https://user-images.githubusercontent.com/12678235/88932716-1202bd80-d244-11ea-987a-db06cfbfbdf0.png)
![image](https://user-images.githubusercontent.com/12678235/88932733-16c77180-d244-11ea-9959-d973f12a0a0e.png)
![image](https://user-images.githubusercontent.com/12678235/88932744-1af38f00-d244-11ea-8daa-1f85e2d0ded1.png)

## PS
Here's an example of math inline conforming to the line height, and being standard-sized when standalone. 

![image](https://user-images.githubusercontent.com/12678235/88932942-61e18480-d244-11ea-82c5-133aa25c047b.png)

**Comment by philschatz** [comment]
A cleaner option was suggested by the MathJax creator. This fix allows us to set a minimum font size so that no matter what, the text would never be too small:

https://gist.github.com/dpvc/15c2f7a1234e01a898c1a8127f1156e3#file-script-size-v2-html-L12

The change would likely need to occur around here: https://github.com/openstax/mathify/blob/master/typeset/mjnode.js

**Comment by lwtchu** [comment]
@philschatz if that's the case, i would suggest around 8.5 pt as that's a happy medium between all the base font sizes in the library (8.25-9)

**Comment by brittany-johnson** [comment]
Issue resolved, closing
