### ISSUE TITLE
bug? baked styles corn theme: image resolution 150ppi isn't working

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2507]
So the default is set to 200ppi and auto. However, I'm not sure if the auto thing..is working? OR the 200 is overriding it since the images look smaller and not true to size.

In the screenshot below, the image is about 2.20inches wide when it should be 2.94 (closer to 3 inches) wide. The small difference leads me to believe that the 150ppi images are being shrunken a bit to accomodate the 200ppi nature of the rest of the pdf. 
![Screen Shot 2020-07-20 at 2 50 01 PM](https://user-images.githubusercontent.com/11299125/87980263-ee4bb480-ca98-11ea-8af9-ee499d3a5282.png)
![Screen Shot 2020-07-20 at 2 50 06 PM](https://user-images.githubusercontent.com/11299125/87980271-f277d200-ca98-11ea-8c40-a1ff1ccbafbd.png)

Higher priority since this is... not a good thing and I really dont want to re-export some art.

**Comment by brittany-johnson** [comment]
A summary of my investigation: 

NOVEL IN PROGRESS. Still need to add images and a quick summary at the top to spare souls 

- Currently, the image resolution is set to `auto, 200dpi`
  - This means that first, Prince will use the image resolution on the image. Then if no image resolution is found or readable by Prince, it will default to 200dpi. 

In the first series of tests, I used Figure 3 in Example 11 from Chapter 1. Content used from [content01](https://content01.cnx.org/contents/18243ac9-49df-433d-b0dc-66531a7ea14e)

**Investigation details:** 
-  With the current image resolution in the CSS, `auto, 200dpi`,  the image is 1.641 x 1.399 in
-  I removed the image resolution CSS value and the image is 41.021 x 34.979 in
-  I then set the image resolution to `200dpi`. The image was very large. 
-  PrinceXML also has a value called `normal` which sets a 96dpi. The image was still very large. 
-  If an image has width and height values set manually in the CSS, this can override the dpi value. I only found one instance of the image height being set in the CSS, but it is not being used on all images. I removed the property anyway just to see what would happen, and there was no effect. 
- I then tried `200dpi, auto` because I wanted to confirm that the image would still be oversized. This also would confirm that the first value is being taken. The image was still oversized. 
- I then tried a `300dpi` and `50dpi` because I wanted to use ridiculous values to see what the effect would be. With both values, the image was still very large. I then began to suspect that we may need an additional selector. The current selector is `:root` and I added `book` 
- I kept it at `50dpi`, and the image looked larger than before. This is good because that means there was some sort of change. 
- I then changed it back to `200dpi`. `200dpi` rendered an image that was smaller than the image rendered at `50dpi`, but the image is still too large. I then tried `300dpi`. `300dpi` is smaller, but still not small enough. 
- I'd been looking at the first two images this whole time for testing, and after scrolling down a bit to around page 109 I see that other images are actually smaller, closer to normal size. 
- I then changed the dpi back to `auto` dpi. On figure 1 in chapter 2, the image looked close to the correct size, 3.245 x 3.005 in. At `200dpi`, it is the same size. 
- This lead me to believe that the images that are extremely big at the beginning of the book do not have an original resolution set on the image, have a resolution that is not consistent with other images in the book, or the resolution set is not readable by Prince.
//other images like, figure 4 in example 3, chapter 4 are too small. this one is 2.435 x 1.830 in

**Comment by lwtchu** [comment]
Let's leave everything at `auto` and the `200ppi` as a backup. I'll have to look at those specific images and see what's wrong.

**Comment by lwtchu** [comment]
I will close since nothing is changing.

**Comment by lwtchu** [comment]
Recently discovered an issue with image resolution in some images. PPI was not included in the metadata. (This probably happened when Wisewire stripped the ICC color profiles from these files.) PrinceXML "defaults" to 200, but the images are actually 150 so they are small/grainy

Can we set the default to `150ppi` JUST for the CORN THEME instead of `200ppi`? Like have it be `auto, 150ppi`

**Comment by brittany-johnson** [comment]
Update for board review: 
Sent PDF w/ `auto, 150ppi` to @lwtchu on Friday

**Comment by lwtchu** [comment]
![Screen Shot 2020-07-28 at 11.09.12 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/7bc3bed5-acd9-45a8-b3fe-3c407815a33f)
it works but for some reason...the image won't render the way that iw ant so that's another deep soul searching crushing thing to ponder. BUT i think it's okay to go with the change!

**Comment by philschatz** [comment]
A cleaner option was suggested by the MathJax creator. This fix allows us to set a minimum font size so that no matter what, the text would never be too small:

https://gist.github.com/dpvc/15c2f7a1234e01a898c1a8127f1156e3

The change would likely need to occur around here: https://github.com/openstax/mathify/blob/master/typeset/mjnode.js

**Comment by brittany-johnson** [comment]
@lwtchu How would you like this to be tested? (If at all)

**Comment by lwtchu** [comment]
@brittany-johnson um...i dont think there will be an easy way for marta to test since they dont have paid version of adobe. if you feel ok with teh test i did with the locally generated pdf we can merge/close/etc
