### ISSUE TITLE
Calculus vol1,2,3: Style Introduction Page 

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#2546]
Related issues with specs: #2314

**Comment by ajluk** [comment]
@MartaSztuka >>> Information for testing purposes: In Calculus splash images have different sizes in different chapters which causes the chapter title to appear in different places (https://github.com/openstax/cnx-recipes/issues/2314#issuecomment-665067016). Per Larissa it will be standardized in the content: https://github.com/openstax/cnx-recipes/issues/2314#issuecomment-665073157.

**Comment by MartaSztuka** [comment]
# PASSED
## Introduction page
Splash images and title display will be fixed in the future.
### Calculus 1
![Screenshot from 2020-08-04 15-43-19](https://user-images.githubusercontent.com/47241114/89300928-4376f100-d669-11ea-886f-f3ae2b955770.png)
### Calculus 2
![Screenshot from 2020-08-04 15-44-38](https://user-images.githubusercontent.com/47241114/89301063-715c3580-d669-11ea-906b-d13f1d272dc2.png)
### Calculus 3
![Screenshot from 2020-08-04 15-45-31](https://user-images.githubusercontent.com/47241114/89301131-8cc74080-d669-11ea-9f4d-bb986b1ad04b.png)
