### ISSUE TITLE
statistics: references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2631]
![Screen Shot 2020-08-17 at 12 55 39 PM](https://user-images.githubusercontent.com/11299125/90428220-44584b80-e089-11ea-978f-26972618763b.png)
- headers will follow sizing of whatever was set for all titles/header hierarchy #2144
- sections are broken up and labeled with the section number and title
- please do an indentation for lines that are not the first line for each reference (see carnival theme)

**Comment by ajluk** [comment]
@lwtchu Here is how the Refences look in Statistics: 
![image](https://user-images.githubusercontent.com/55203598/90492135-1fbfaa80-e141-11ea-8d9e-1c1ca3fb9c72.png)
The links aren't colored as they were in Anatomy from carnival theme, because the are not actual links (there is no `a` tag in the paragraph, just text in the content):
![image](https://user-images.githubusercontent.com/55203598/90492363-66ada000-e141-11ea-95a3-5bb60baed7cc.png)

**Comment by lwtchu** [comment]
links not colored is expected. thank you it looks great!
