### ISSUE TITLE
cardboard theme: splash images

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2642]
![Screen Shot 2020-08-31 at 11 12 53 AM](https://user-images.githubusercontent.com/11299125/91741884-f78d6e00-eb7a-11ea-932d-79ac0e8248c3.png)

![image](https://user-images.githubusercontent.com/11299125/90661394-c58c1b80-e20c-11ea-83dc-eded3ddff5cb.png)

# Splash Figure
All splash images in this theme are 8.75in x 3.59in. The image has a 0.125in (1/8in) bleed on the page. See screenshot below. Should be centered on the page.

![image](https://user-images.githubusercontent.com/11299125/90661615-08e68a00-e20d-11ea-8cdd-4f2dc35430d0.png)

# Line under splash figure
width: 0.25rem (3px)
color: P2: `#772949` for Astronomy; B2: `#344456` for other titles

# Chapter number
font-family: noto sans
font-weight: bold
font-size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: P2: `#772949` for Astronomy; B2: `#344456` for other titles

# White circle around number
height: 2.75rem
width: 2.75 rem
color: `#FFFFFF`

# Icon doodad
Astronomy: https://drive.google.com/file/d/1C4fs6R-cP0UwIMnp7WrakCwlBjsWOc4d/view?usp=sharing
Business series: https://drive.google.com/file/d/1G9MnkDQ_4hi5Eh-KaYgaNBDru--PHbHM/view?usp=sharing

# Chapter title
font-family: Dosis for Astronomy, Roboto Condensed for all other titles
font-weight: bold
font-size: font-scale(2): 12.96pt, 16.8px, 1.4rem
color: P1: `#3B2746` for Astronomy; white `#FFFFFF` for other titles

# Figure number & caption
font family: noto sans
size: font-scale(-1): 7.5pt, 9.6px, 0.8rem
caption: Grey2: `#757474`
(Should be same as #2643)

**Comment by ajluk** [comment]
Hi @andymuddimer I have a question about folio for cardboard theme. There are two kinds of folios: separate for carnival and corn theme. This is how they look:
**Carnival theme**
Introduction Page: we didn't add folio there in this theme: 
![image](https://user-images.githubusercontent.com/55203598/94679765-ede55a80-0320-11eb-8bb2-f345df9383e9.png)
Rest of the pages (there is a chapter word on the left page):
![image](https://user-images.githubusercontent.com/55203598/94680138-8e3b7f00-0321-11eb-84b7-693d5d6f8736.png)
![image](https://user-images.githubusercontent.com/55203598/94680097-7ebc3600-0321-11eb-9ba1-d87efbcaeab5.png)


**Corn theme**
Introduction page (white font color, lack of chapter word, just number): 
![image](https://user-images.githubusercontent.com/55203598/94679922-2f760580-0321-11eb-874f-3a4f48681856.png)
Rest of the pages (lack of chapter word, just the number): 
![image](https://user-images.githubusercontent.com/55203598/94679978-4a487a00-0321-11eb-9dc2-a499e584c43e.png)
![image](https://user-images.githubusercontent.com/55203598/94679997-53d1e200-0321-11eb-9bca-cf5c7a6d798e.png)

Which of these two types of folios we would like to have in cardboard theme? I'm asking because there is some difference in the screenshots from above: on the first screenshot from business series there is no folio presented on the Intro page, but in the screenshot from Astronomy there is one (white font on the left side). Do we want to support folio on the Introduction page (like we did in the corn theme) or skip it on this page only as it was done in the carnival theme? I guess it should be standardized for Business series and Astronomy because these books will be both in the same theme. 
I have asked Larissa about it earlier in this issue: https://github.com/openstax/cnx-recipes/issues/2712 but she's on vacation now and I didn't want to bother her about it. Maybe you can advise?

**Comment by lwtchu** [comment]
@ajluk for the cardboard theme can we have it match the corn theme. i don't want to add the word chapter in it if we can help it for right now.

**Comment by ajluk** [comment]
Hi @lwtchu Here is how the Introduction page looks like coded: 
![image](https://user-images.githubusercontent.com/55203598/95884652-a7f6b080-0d7c-11eb-8ab2-c88560c7448f.png)
As you can see on the screenshot above the chapter number is not in the same line as figure caption. Should I move the number in the same line. Then it will be a little bit diffrent than in the screenshot you provided.
I have also put chapter title (whole blue bar) on the image, because I have some problem with styling figure caption if the bar is under image? What do you think about it.  
How other pages look like: 
![image](https://user-images.githubusercontent.com/55203598/95888370-4edd4b80-0d81-11eb-9121-313e9fad4a24.png)
![image](https://user-images.githubusercontent.com/55203598/95888630-9ebc1280-0d81-11eb-9cb0-d4c8ce18c516.png)
![image](https://user-images.githubusercontent.com/55203598/95888510-73d1be80-0d81-11eb-8c91-0a849e18c65d.png)

**Comment by lwtchu** [comment]
![Screen Shot 2020-10-13 at 12 00 10 PM](https://user-images.githubusercontent.com/11299125/95892163-b5e00d80-0d4b-11eb-9b27-718eafa59846.png)
![Screen Shot 2020-10-13 at 11 56 34 AM](https://user-images.githubusercontent.com/11299125/95892318-f93a7c00-0d4b-11eb-8701-435638113f68.png)
![Screen Shot 2020-10-13 at 11 56 40 AM](https://user-images.githubusercontent.com/11299125/95892326-fb9cd600-0d4b-11eb-831a-925413bc9ca8.png)


There are a few issues.

- First is the image itself isn't centered and I think it's being stretch out too far on both sides. We should try to keep them centered and only stretch out the small bit for the bleed 
- The blue bar is going a few inches too far to the right. 
- I think the city scape placement looks good though.

**Comment by ajluk** [comment]
@lwtchu These are the specs I added:
![image](https://user-images.githubusercontent.com/55203598/96259579-19717180-0fbe-11eb-9ab3-3241b3384006.png)
**SplashImg**
    width: 8.75in;
    height: 3.58in;
    display: inline;
![image](https://user-images.githubusercontent.com/55203598/96259267-a36d0a80-0fbd-11eb-88ff-d7c8e69aeff4.png)
**SplashImgMediaBar**
    width: 100%;
    content: '';
    display: block;
    position: absolute;
    bottom: 0;
    right: 0;
    height: 5.83rem;
    background-color: #24739E;
    border-top-width: 0.25rem;
    border-top-style: solid;
    border-top-color: #344456;
    z-index: 1;
![image](https://user-images.githubusercontent.com/55203598/96259192-8cc6b380-0fbd-11eb-9865-d5a1866b3c1e.png) 
**SplashImgMedia**
    display: flex;
    width: 8.75in;
    border-left: none;
    height: 4.3in;
    position: relative;

![image](https://user-images.githubusercontent.com/55203598/96260827-db754d00-0fbf-11eb-8561-d6782b49b827.png)
**SplashFigure**
   position: relative;
    width: 8.75in;
    transform: translate3d(-1in, 0, 0);
    margin-left: -1.2rem;
    padding-bottom: 0;
    margin-bottom: 1.25rem;

![image](https://user-images.githubusercontent.com/55203598/96259676-3ad25d80-0fbe-11eb-98bf-23136c01d841.png)
**H1TitleNumber**
    padding: 0.6rem 0;
    width: 2.75rem;
    height: 2.75rem;
    display: inline-block;
    text-align: center;
    background-color: #FFFFFF;
    position: relative;
    bottom: 5.3rem;
    color: #24739E;
    border-radius: 50%;
    left: 0.5rem;
    z-index: 2;
    font-weight: bold;
![image](https://user-images.githubusercontent.com/55203598/96259972-a3213f00-0fbe-11eb-81e8-23811f0c371b.png)
**H1Numbered** (whole title)
    display: flex;
    color: #FFFFFF;
    font-family: Roboto Condensed, StixGeneral;
    font-size: 1.44rem;
    line-height: 1.5rem;
    margin-bottom: -1.2rem;
    position: relative;
    top: 34rem;
    font-weight: normal;
    flex-direction: row;
    z-index: 2;
    width: 8.75in;
    left: 0;
    margin-top: -1.2rem;

![image](https://user-images.githubusercontent.com/55203598/96260074-cba93900-0fbe-11eb-86d0-f96f2e8a8e46.png)
**H1TitleText**
    display: inline-block;
    position: relative;
    margin-left: 4rem;
    top: -2.5rem;

![image](https://user-images.githubusercontent.com/55203598/96260150-e7acda80-0fbe-11eb-858c-8b8928257b13.png)
**H1Icon**
    background: url(toDataUri("svg+xml", "designs/cardboard/resources/cardboard-intro2.svg")) no-repeat top left,
    background-size: contain;
    content: '';
    display: inline-block;
    width: 14.2rem;
    height: 6.1rem;
    position: absolute;
    bottom: 0.1rem;
    left: 0;
    right: 0;
    z-index: 2;
    transform: translate3d(-1in, 0, 0);

**Comment by lwtchu** [comment]
@ajluk specs look good thank you ~

**Comment by ajluk** [comment]
@lwtchu  I have also needed to add one property to SplashFigureWrapper: margin-top: -1.15in and change the `top` property value for H1Numbered (whole title) to 26rem. It looks exactly the same now: 
![image](https://user-images.githubusercontent.com/55203598/96599932-b4d15200-12f0-11eb-8d8e-dc7601f9d0a3.png)
This change resolves the the same issue for cardboard books as Alan described here for corn ones: #2877

**Comment by lwtchu** [comment]
@ajluk cool. thank you for the thorough documentation~

**Comment by ajluk** [comment]
@lwtchu This is how the Introduction looks styled within the specs: 
![image](https://user-images.githubusercontent.com/55203598/101936201-8a10c500-3be0-11eb-8d8d-f7601c2e5333.png)
Should the color for Chapter number and title be darker?
Now it's set to P2 (#772949) as in the specs above.
I have also question about the Chapter title background color: I couldn't find the spec for it. I have chosen  O1 (#CB634E) is it correct?
![image](https://user-images.githubusercontent.com/55203598/101936554-f986b480-3be0-11eb-8f9b-27f07cf4f447.png)

**Comment by lwtchu** [comment]
@ajluk good question - i set it to P1: `#3B2746` in the specs. That should be the darker purple.

**Comment by ajluk** [comment]
@lwtchu Here is how the darker P2 color looks like on chapter title: 
![image](https://user-images.githubusercontent.com/55203598/102218433-3bb03e80-3ede-11eb-8b3a-8d3fe63cbda5.png)
Do you want me to change also the chapter number (in the circle) and line under the splash image to this color as well? Or should it stay as it is (I'm asking because not they are the same as the icon): 
![image](https://user-images.githubusercontent.com/55203598/102218661-977ac780-3ede-11eb-8bcb-ecfd771f600c.png)

**Comment by lwtchu** [comment]
@ajluk as is is fine. thank you :)
