### ISSUE TITLE
Test Elem Alg 2e at 80%

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2653]
# Testing Instructions 
elementary algebra 2e - production - dev math recipe

**Comment by MartaSztuka** [comment]
## Tests results
### Learning Objectives unstyled https://github.com/openstax/cnx-recipes/issues/2695
### Everyday Math paragraphs need margine https://github.com/openstax/cnx-recipes/issues/2696
### Images in example is blurred and probably too big https://github.com/openstax/cnx-recipes/issues/2697
### Token lists https://github.com/openstax/cnx-recipes/issues/2694
### Stepwise lists https://github.com/openstax/cnx-recipes/issues/2699
### Paragraph is unstyled https://github.com/openstax/cnx-recipes/issues/2700
### "Solve' is normal, should be bold https://github.com/openstax/cnx-recipes/issues/2701
### There is singe dot above 'In the following exercise (...)` https://github.com/openstax/cnx-recipes/issues/2702
### Leading between `Solve a System (...)` and  'In the following exercise (...)` is smaller than usually https://github.com/openstax/cnx-recipes/issues/2703
### Examples of polynomials paragraph is unstyled https://github.com/openstax/cnx-recipes/issues/2704
### Content in the last row should be left-aligned https://github.com/openstax/cnx-recipes/issues/2705
### Terms should be bold? https://github.com/openstax/cnx-recipes/issues/2706
### Space is too big https://github.com/openstax/cnx-recipes/issues/2707
### No bottom margin https://github.com/openstax/cnx-recipes/issues/2714
### Example https://github.com/openstax/cnx-recipes/issues/2715
### Bullet list instead of Stepwise list in 'How to' https://github.com/openstax/cnx-recipes/issues/2716
### Answer Key, two columns in thee columns layout https://github.com/openstax/cnx-recipes/issues/2717
