### ISSUE TITLE
HS Statistics - Blurred images

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2681]
### Images in Appendix is blurred ![Screenshot from 2020-08-24 14-36-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/564471bf-7668-41d3-bc79-aa4c3299df9b)

**Comment by lwtchu** [comment]
it might be the default ppi setting is inflating them since they are rendered at 72ppi....i think a while back we had some issues with this in... #2507 
![Screen Shot 2020-08-24 at 9 22 45 AM](https://user-images.githubusercontent.com/11299125/91056298-6c94fc80-e5eb-11ea-91ce-1e2bab30df71.png)

they should only be 1/2 an inch wide but are rendering almost a full inch (i'm assuming)? which makes me think they're being doubled in size (forced into a 150ppi resolution). 

anyway - to whichever dev that decides to pick this up, you can message me about options? if any?? like should we set all things to auto?

**Comment by ajluk** [comment]
@lwtchu I have checked hot it will look with the  `prince-image-resolution: "auto"` images we still big and blurred. So I I have tried  `normal` just to check and this I guess gave me the expected result: 
![image](https://user-images.githubusercontent.com/55203598/91541185-38d41280-e91c-11ea-9ede-b34cf6ad53d7.png)
![image](https://user-images.githubusercontent.com/55203598/91541122-21952500-e91c-11ea-9c6d-6bfc12aa683e.png)
I have checked other images and there is now visible negative change. But it appear to be not a good solution for every image in corn theme books based on the @brittany-johnson investigation comment on related issue (https://github.com/openstax/cnx-recipes/issues/2507#issuecomment-662652001).
![image](https://user-images.githubusercontent.com/55203598/91541605-df201800-e91c-11ea-9e5a-b586d83d237d.png)

**Comment by lwtchu** [comment]
hmm this is strange. i might need to run a few tests on the content side to see if it might be an incompatibility with the way these images were exported for these books.... 

i don't really have time to investigate this week but after coreq gets published and i get a few books prepped for cardboard....i can double check the images and we can get back to it based on my findings? 

would it be alright for everyone if we move this down to the next sprint or two?  @ajluk @brittany-johnson @brittweinstein

**Comment by brittweinstein** [comment]
Closing as this is a duplicate. BrittanyJ is working on the solution.
