### ISSUE TITLE
Elementary Algebra - ABC Tokens

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2694]

**Comment by lwtchu** [comment]
3 6 & 7 are probably content issues

to the dev who will work on this should we break these up? message me when you get to this :)

**Comment by wilkus27** [comment]
@lwtchu I will be investigating these problems one by one and add comments about that. 

**1.** I have found that in other places this problem doesn't exist because after numbers there is hard coded space:

![image](https://user-images.githubusercontent.com/40228854/93098250-ef6b1d80-f6a6-11ea-89e6-ee518aed11d5.png)

So this one it's a content issue.

**Comment by wilkus27** [comment]
**2.** It is also content issue. There are additional spans with `data-type="newline"` : 

![image](https://user-images.githubusercontent.com/40228854/93100295-4a057900-f6a9-11ea-86f1-7476a8b57e5c.png)

**Comment by wilkus27** [comment]
**3.** The same here. Additional newline:

![image](https://user-images.githubusercontent.com/40228854/93100761-d44ddd00-f6a9-11ea-8545-7851286cc0a1.png)

**Comment by lwtchu** [comment]
@wilkus27 that's fine. i think the main concern i have is to make sure if anything does have `<span class="token">` that it gets styled.

**Comment by wilkus27** [comment]
@lwtchu So in this issue it's not styled only in problem **7.**. I created PR for this problem. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/93216302-db3b2500-f767-11ea-9be8-ce06a3aca91c.png)

**Comment by lwtchu** [comment]
@wilkus27 i think we need to look at instances 8. maybe for 8 we can put a rule that if the content goes more than 50% of the container (be it page or exercise box), it does not pull the next item into the line? 
 

i can double check 9. i suspect there might be some line breaks in there

**Comment by wilkus27** [comment]
@lwtchu About **8.** it acts weirdly because of newline:

![image](https://user-images.githubusercontent.com/40228854/93224599-90260f80-f771-11ea-9359-b2cd0ba24250.png)

Is it necessary to display text under the equation? Also second sentence (for B) is out of the list in separate paragraph. 


The same situation is for problem **9.**:

![image](https://user-images.githubusercontent.com/40228854/93225282-530e4d00-f772-11ea-9730-691ae44b7b18.png)

Hmm :thinking: I'm wondering how we should handle this.
Let me try to style tokens from this problem https://github.com/openstax/cnx-recipes/issues/2760#issuecomment-692206953. If it works maybe we can try to apply similar markup for lists from problem 8 and 9?

**Comment by lwtchu** [comment]
@wilkus27 yes i think it might be best to try the labeled list for some of these instances. i'm trying to think of why it was never an issue in the first place when we did this feature in oer.exports 🤔  but either way i think it'll be best to go with #2760

**Comment by wilkus27** [comment]
@lwtchu styling tokens in labeled lists is working as I mentioned in #2760 . So we can use this solution here as well.

Also I checked how examples from problem 8 and 9 look on production in old PDF and this issue occurs there as well:

![image](https://user-images.githubusercontent.com/40228854/93305230-80a0d800-f7fe-11ea-9ab2-4bd7fa12ced4.png)

![image](https://user-images.githubusercontent.com/40228854/93305397-c067bf80-f7fe-11ea-9304-7d507370481a.png)

(Actually this one looks better but it is because of margin on the left, this is the reason why B jumped to the next line)

**Comment by lwtchu** [comment]
@wilkus27 ah okay makes sense. we can make the change later...i'm not sure if this card included any fixes 

should we close?

**Comment by wilkus27** [comment]
I made a fix for problem 7. It's ready for testing.

**Comment by MartaSztuka** [comment]
## PASSED
### 7. Tokens look ok, there's no numbers
![Screenshot from 2020-09-18 10-44-55](https://user-images.githubusercontent.com/47241114/93577400-4a00c400-f99c-11ea-98e0-f409e2690072.png)
