### ISSUE TITLE
coreq math - token and list classes are not working in try it features

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2736]
related to #2732 

the classes are not working within the try its
![image](https://user-images.githubusercontent.com/11299125/91875624-59b0a680-ec41-11ea-9e0a-f1c01efe97f7.png)

made a content change on production to accomodate for publication but  this needs to fixed for other titles within the theme and for this title later

screenshot from 7.6 in college algebra coreq

**Comment by lwtchu** [comment]
![Screen Shot 2020-09-01 at 2 45 14 PM](https://user-images.githubusercontent.com/11299125/91898721-c5a30700-ec61-11ea-9b2d-88ead7dd7f79.png)
still persists in pdf 389 - can do a lil content stuff to make it less noticeable. but should be fixed before we take this to print

**Comment by ajluk** [comment]
@lwtchu I was trying to find the note from the screenshot you posted and couldn't do that. Natalia told me we don't have updated the content in chapter 7 in College Algebra Coreq on katalyst01. Only chapter 1 and 4 were updated. Could it be updated so we can checkk it out?

**Comment by brittweinstein** [comment]
@lwtchu is there any update on this?

**Comment by lwtchu** [comment]
@brittweinstein @ajluk oops i thought i updated the card here. but i migrated all the coreq content over last week.

**Comment by ajluk** [comment]
@lwtchu Oh, Thank you!

**Comment by ajluk** [comment]
@lwtchu This is how the lists look now: 
![image](https://user-images.githubusercontent.com/55203598/93339620-156dfa80-f82c-11ea-956c-9084613bad07.png)

**Comment by lwtchu** [comment]
@ajluk yes this si fine thanks!

**Comment by ajluk** [comment]
Hi @lwtchu Natalia has noticed that Try It notes have exercises inside of them and this one from above doesn't have it in the content, so the markup is different there. I didn't know about this, so I have added the styles for lists in the notes, but I think in this case a content change is needed because if the markup will be correct the lists will be styled without my changes using shape for exercises. 
The markup in the note from above: 
![image](https://user-images.githubusercontent.com/55203598/93461123-95f03200-f8e4-11ea-9de8-a63959b4ed38.png)
The correct markup from another Try It note:
![image](https://user-images.githubusercontent.com/55203598/93461350-eff0f780-f8e4-11ea-850b-84e99b2494ba.png)
Invalid markup in the assembled file of the note:
![image](https://user-images.githubusercontent.com/55203598/93462080-064b8300-f8e6-11ea-8666-140f7da48aea.png)
The correct markup in the assembled file:
![image](https://user-images.githubusercontent.com/55203598/93461739-7a395b80-f8e5-11ea-8716-7bc29bf4807c.png)
Please let me know if the change will be added in the content and I will then close my PR.

**Comment by lwtchu** [comment]
@ajluk ah okay thank youf or catching. i'll change it in katalyst01 and check production also today

**Comment by ajluk** [comment]
@lwtchu Thank you! Let me know if I should check it on katalyst01 as well?

**Comment by lwtchu** [comment]
@ajluk i just fixed it...publishing now :)

**Comment by ajluk** [comment]
@lwtchu Ok. I will close my PR then.Thank you! :)

**Comment by lwtchu** [comment]
@ajluk should i close this card? :eyes:

**Comment by ajluk** [comment]
@lwtchu I thought that you will after your previous comment :) But I can fetch the fresh content from katalyst01 if the changes are there too and check it out first and the close. Let me know if it will be better this way.

**Comment by lwtchu** [comment]
@ajluk :joy: sorry yes that will work.

**Comment by ajluk** [comment]
@lwtchu I have checked this note after fetching new content and it looks good now: 
![image](https://user-images.githubusercontent.com/55203598/93758787-59387980-fc09-11ea-86ab-28653697ebfc.png)
Can I close this issue?

**Comment by brittweinstein** [comment]
@ajluk we reviewed this, this morning, and we can close!
