### ISSUE TITLE
precalculus prod recipe does not suppress coreq material

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2740]
https://vendor.cnx.org/contents/mwjClAV_@24.24:0KhpF2RH@41/1-1-Real-Numbers-Algebra-Essentials

This version is baked with Precalculus Prod (recipe) and it still has the corequisite section showing. We need the precalculus prod recipe re-lock on whatever is the latest now (Precalculus (Prod)) in case we do more fixes in the future.

Not super urgent. Can be done later.

**Comment by brittweinstein** [comment]
@Stackblocks this is already there in the dropdown, hopefully this will be super quick! @brittany-johnson will provide more info.

**Comment by brittany-johnson** [comment]
Hello! Yes, I believe that since this book has already been added to the dropdown, the prod recipe just needs to be updated. To do this you can delete the current prod recipe, regenerate the precalc recipe (making sure that it is up to date with master), duplicate the recipe file, and name one to prod. (or you could also do it another way, the main idea is to make sure that the precalc recipe named prod is up to date with master)

**Comment by meeragovindaraju** [comment]
College Algebra on talking.teller looks good

![Screen Shot 2020-09-24 at 2 12 16 PM](https://user-images.githubusercontent.com/33066187/94189147-fc8ac800-fe6f-11ea-9dc4-1cc25b27e07c.png)

**Comment by meeragovindaraju** [comment]
Precalculus looks good

![Screen Shot 2020-09-24 at 5 23 45 PM](https://user-images.githubusercontent.com/33066187/94206304-be4ed200-fe8a-11ea-8faf-9adfd08eff4e.png)

**Comment by meeragovindaraju** [comment]
Algebra and Trig looks good

![Screen Shot 2020-09-24 at 5 25 12 PM](https://user-images.githubusercontent.com/33066187/94206412-fa823280-fe8a-11ea-8fa5-79a42c13c991.png)
