### ISSUE TITLE
business ethics - footnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2747]
![Screen Shot 2020-09-02 at 8 15 30 PM](https://user-images.githubusercontent.com/11299125/92060354-1f3a2d00-ed59-11ea-9dcc-444b7fbb7e7a.png)
Like the carnival theme, let's have footnotes be separated from the main text with a 1px black line.

Font style: noto sans
Color: Grey2: `#757474`
Size: font-scale(-1): 6.89pt, 9.17px, 0.8rem

**IMPORTANT** THE NUMBERING SHOULD BE LOWER CASE ROMAN NUMBERALS (i, ii, iii, iv...)

**Comment by ajluk** [comment]
Hi @andymuddimer! Could you advise if the footnote link (first arrow pointing) should be also lower-roman and styled within properties from above? This is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/94942103-1cf0fd00-04d6-11eb-9285-437a3fd1cd5d.png)
I have checked in the old pdf that the footnote link is lower roman and grey as well and in square brackets:
![image](https://user-images.githubusercontent.com/55203598/94942350-73f6d200-04d6-11eb-853b-34028ba05580.png)
Let me know if should be implemented this way in corn theme too.

**Comment by lwtchu** [comment]
@ajluk can we have it be lower roman numerals also. we can keep it a link (without the underline) if it's clickable

**Comment by ajluk** [comment]
@lwtchu This how ot looks now:
![image](https://user-images.githubusercontent.com/55203598/95175881-65e9cf80-07bc-11eb-83f2-358d8d68a007.png)
Yes, the link is clickable, so I have left the color, just removed the underline. Is this what you had in mind(the link color will be added within another PR)?
I have one more additional question, this footnotes styling isn't theme wide right? Only business ethics should have this numbering style? And Business Law I guess, because they are using the same recipe. I'm asking because I needed to add some changes in the recipe for these two books. Please correct me if I'm wrong. Thank you!

**Comment by lwtchu** [comment]
@ajluk I think it's okay for the change to permeate to business law. it's currently like that in the PDF for the oer.exports generated pdf. this can apply to all titles using the business ethics recipe.

**Comment by brittweinstein** [comment]
Anna has made this fix.

**Comment by brittweinstein** [comment]
@lwtchu I'm closing this because the work for this title is done and we can use the documentation by searching the label.
