### ISSUE TITLE
Supress answers in Polish Psychology

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2754]
Answers to EOC exercises should be supressed:

![image](https://user-images.githubusercontent.com/40228854/92594431-0d014700-f2a3-11ea-9df5-ec0d596a36ba.png)
https://katalyst01.cnx.org/contents/84JIUkA_@1.117:6eTo0Vl5@1.117/Sprawd%C5%BA-wiedz%C4%99

**Comment by meeragovindaraju** [comment]
@wilkus27 Should I be testing this on suspicious.sting branch?

**Comment by wilkus27** [comment]
@meeragovindaraju Yes, changes are merged to milestone branch. Since we don't have styles for this book yet it is hard to test it locally. Do you have an informations how to bake content on the server to be able to test it on katalyst01.cnx.org?

**Comment by meeragovindaraju** [comment]
@wilkus27 What recipe would you like for me to use while baking this title?

**Comment by Stackblocks** [comment]
Appears to be working correctly with the injected style, @wilkus27 please double check to make sure I'm not missing anything. The change is visible at the link you provided in the initial comment.

![image](https://user-images.githubusercontent.com/12678235/92963670-75cdf800-f438-11ea-946a-bb38eb23d63d.png)

@meeragovindaraju We can set up a training session next week to go over testing this kind of issue, since it's something we didn't spend a lot of time on before and you haven't had much exposure to.

**Comment by wilkus27** [comment]
Thank you @Stackblocks ! It looks good :relaxed: I'm closing the issue.
