### ISSUE TITLE
coreq - unnumbered tables are counting in the coreq section

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2781]
![Screen Shot 2020-09-18 at 4 49 19 PM](https://user-images.githubusercontent.com/11299125/93647906-1d19d480-f9cf-11ea-95b9-d03f98056be1.png)

Location: https://katalyst01.cnx.org/contents/mwjClAV_@20.98:4BfLAtSU@23/5-2-Power-Functions-and-Polynomial-Functions (I added an additional empty table to test numbering.)

But ideally, the circled Table number should be table 1 & 2 since the unnumbered class is on the previous 4 tables. Can we make sure the unnumbered class is not secretly counting the tables?

**Comment by wilkus27** [comment]
@lwtchu Is it necessary to number figures inside table? Because we don't support such case in the recipe. That's why it displays wrong. I mean table caption is inside the table, not below. I think first I should fix that problem then look into the numbering, because it could have an impact. Please let know what we want to do in this case. To support numbered figures inside numbered tables or to change figures to be unnumbered?

**Comment by lwtchu** [comment]
@wilkus27 that's..interesting 🤔  let me make them unnumbered and do a test real quick. if it solves the problem i'll open a card on the content side and close this one~

**Comment by lwtchu** [comment]
![Screen Shot 2020-09-25 at 1 30 32 PM](https://user-images.githubusercontent.com/11299125/94303384-51434700-ff33-11ea-8c30-994a56c35854.png)
I made the change and the table numbers still say 5 & 6 therefore the unnumbered ones ar estill counting

**Comment by wilkus27** [comment]
Thank you @lwtchu for checking that! I made a fix for numbering.

**Comment by MartaSztuka** [comment]
## PASSED
![Screenshot from 2020-09-30 11-19-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/57bb2532-1962-4222-b2b1-3b0981b74307)
