### ISSUE TITLE
Corn Theme: Key Term Header Collision

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#2877]
# Brief Description of Scenario and Screenshots
Key Terms in the Corn theme are ignoring page margins and colliding with the folio. This appears to have been working correctly as recently as last month, so that narrows down the possibility space some.

# What kind of issue is this? 
- [ ] recipe 
- [ ] styles 
- [ ] both 
- [x] i don't know

# Screenshots

## Current State

![2020-10-16_15-47-33](https://user-images.githubusercontent.com/12678235/96307282-0020f300-0fc7-11eb-96f0-6e8e3af49ceb.png)
---
![2020-10-16_15-46-34](https://user-images.githubusercontent.com/12678235/96307287-01522000-0fc7-11eb-9815-a47bbf76b481.png)
---
![2020-10-16_15-45-44](https://user-images.githubusercontent.com/12678235/96307295-02834d00-0fc7-11eb-94f8-35813246822f.png)

## Previous State
![image](https://user-images.githubusercontent.com/12678235/96308511-25aefc00-0fc9-11eb-9524-cc7ae7791b9a.png)

# Acceptance Criteria
Key Terms respect the top-of-page spacing and sit below the folio like all of the other pages.

# Bug Location(s)
collection ID:11667, 30309, etc.
server: katalyst01.cnx.org
chapter/section: Key Terms (EoC)
surrounding text: n/a

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by ajluk** [comment]
I have investigated that that this collision is caused by negative margin which I have added to the chapter to resolve the problem with bookmarks. I have removed it and added it to the os-figure container instead. Here is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/96476137-277cf780-1235-11eb-9e16-dc31dbe62567.png)
![image](https://user-images.githubusercontent.com/55203598/96476196-3499e680-1235-11eb-9955-10002872d8e6.png)

**Comment by MartaSztuka** [comment]
## PASSED
### HS Statistics![Screenshot from 2020-10-21 17-54-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/20fee82b-5d50-4a52-ab93-42cfdb00f502)
### Precalculus ![Screenshot from 2020-10-22 10-20-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5a274548-7208-436a-9959-0987979a09c3)
