### ISSUE TITLE
Accounting: Tables

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2939]
Should follow: https://github.com/openstax/cnx-recipes/issues/2741

**Comment by kswanson33** [comment]
Specs #2741

Changes applied to tables in accounting

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/5316bfa8-9fee-4c3a-a879-79354777af1c)

[Link to PR](https://github.com/openstax/cnx-recipes/pull/3118)

accounting is on katalyst01 with col25448

**Comment by meeragovindaraju** [comment]
**Test Passed**

![Screen Shot 2020-12-08 at 11 48 43 AM](https://user-images.githubusercontent.com/33066187/101521844-f626cb00-394b-11eb-9005-d274fdbac428.png)

![Screen Shot 2020-12-08 at 11 49 39 AM](https://user-images.githubusercontent.com/33066187/101521846-f6bf6180-394b-11eb-8cb6-e99eec210037.png)

**Comment by kswanson33** [comment]
Tables with selector `.os-unstyled-container` remain unstyled. Reopening

**Comment by kswanson33** [comment]
![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/0c4f6797-9fe2-4313-bb62-e0862dea3106)

Right now, I'm using the unstyled tables from college-success outlined in #3136. However, I can't actually find documentation of this style for accounting. What do you think @lwtchu ?

**Comment by ajluk** [comment]
@kswanson33 I have noticed that you're going to use these unstyled tables styles. I was actually on it and wanted to update the documentation but it appears that the styles for the container has been overwritten: 
![image](https://user-images.githubusercontent.com/55203598/102525111-22ec8800-409a-11eb-9108-f3ee16427716.png)
There is a need to add another selector (`.os-unstyled-container`) to Default Tables selectors in the `table-settings-scss` file:not pseudo element. If you would like to fix this within your PR, feel free to do it! Otherwise I will fix it later on.
