### ISSUE TITLE
Entrepreneurship: Review Questions

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2969]
Should follow https://github.com/openstax/cnx-recipes/issues/2744 
`class="review-questions"`

**Comment by ajluk** [comment]
Screenshot for reference: 
![image](https://user-images.githubusercontent.com/55203598/100439618-0b763c80-30a4-11eb-9656-2a0fde173fc9.png)
@lwtchu I have used the same icon as it was used in Assessment Questions, I assumed it should be the same, because it wasn't specified, but let me know if there should be used different one for these exercises.

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-03 10-39-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/da5cbf4b-be25-4098-84b1-df9643f058f5)

**Comment by lwtchu** [comment]
@ajluk just noting here that the icon is correct in case we come wandering into the issue six months later
