### ISSUE TITLE
College Success: Splash Image

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3001]
Should follow https://github.com/openstax/cnx-recipes/issues/2642

splash intro icon is the campus icon: https://drive.google.com/file/d/1M7YKIHVgQY5BAdaalZPK6IP5ausLFxjj/view?usp=sharing

**Comment by ajluk** [comment]
Hi @andymuddimer! The icon provided in the description from above is different that the one we used for cardboard theme so far and when I have applied styles I have created for the previous one it looks like this in the PDF reader in the bleed: 
![image](https://user-images.githubusercontent.com/55203598/101189963-0858ee80-3658-11eb-966e-49a15b01df81.png)
As you can see above the red tree on the left side is missing then, I'm not sure what is causing this behavior, but when I have added prince crop, trim, mark properties it is visible in the bleed: 
![image](https://user-images.githubusercontent.com/55203598/101191909-9635d900-365a-11eb-95f0-c9325fa58688.png)
Should I leave it this way? Could you check in the Acrobat how the icon looks in the bleed, because we don't have the version with editing? I have sent the pdf file with bleed marks and without it in the thread in the katalyst-devs2 channel.

**Comment by ajluk** [comment]
I have also checked the pdf from production and there the whole icon is visible on the page: 
![image](https://user-images.githubusercontent.com/55203598/101193314-aea6f300-365c-11eb-8f71-eadf7282e682.png)
so it is not moved to the edge of the bleed. Should I style it rather this way then?

**Comment by andymuddimer** [comment]
Yes please style so that the left red tree is showing - thank you

**Comment by ajluk** [comment]
@andymuddimer I have styled the icon similarly like it was in the old pdf. This how it looks now in pdf: 
![image](https://user-images.githubusercontent.com/55203598/101348410-e34cc180-388b-11eb-9833-e5d1ea50168a.png) Is that what you have in mind? I'm asking just to confirm.

**Comment by lwtchu** [comment]
@ajluk we discussed this on the call today - it looks good. thank you ~

**Comment by MartaSztuka** [comment]
#### PASSED![Screenshot from 2020-12-09 15-26-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8f7c3b94-b1ed-43f3-92b5-8cdf350a6cbf)
