### ISSUE TITLE
Standardize the underline under page links in the Key Terms section

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/cnx-recipes#3137]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [X] styles [ ] both [ ] i don't know

![Screen Shot 2020-12-07 at 4.47.09 PM.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/5824d2c4-908f-4419-9588-0d8d221d4c80)

# Acceptance Criteria

# Bug Location(s)
collection ID: col25448
server: katalyst01
chapter/section: Key terms
surrounding text: Key Terms

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by meeragovindaraju** [comment]
collection ID: col25448
server: katalyst01
chapter/section: Summary sections
surrounding text: Summary sections

![Screen Shot 2020-12-07 at 6 07 17 PM](https://user-images.githubusercontent.com/33066187/101420557-14db8200-38b8-11eb-8e56-d1206297344a.png)

**Comment by lwtchu** [comment]
When someone has the time - can they look into why some of the underlines fall further from the number in some instances? i thought it was because of the comma, but ...it doesn't seem the case for all fo them.

also why "account" falls on the same line as "abnormal balance"

**Comment by ajluk** [comment]
@lwtchu I have checked this book out locally and and it looks better now: 
![image](https://user-images.githubusercontent.com/55203598/102098405-786d2e80-3e27-11eb-84df-b891a5171405.png)
Is the underline still need some fixes? The difference is almost invisible. I'm asking because Prince doesn't support the `text-underline-offset` css property within which we can set the space between text and the line manually, so I'm not sure if it's even possible to standardize.

**Comment by lwtchu** [comment]
@ajluk if it looks better now - I think we can close this card.

if i want bands in this book - and the others, should i make a card?

**Comment by ajluk** [comment]
@lwtchu Other books already have it except Astronomy, which I was asking under the epic for this book about the color, so I can ask Marta to check it out when I will add it, but for Accounting maybe it is a good idea, because @LostMojo  and @kswanson33 were working on this book, so it will be easier for them to reley on separate one I suppose if they pick the card.

**Comment by lwtchu** [comment]
@ajluk ah you're right. let me whip up a card for them. i'll close out this card though since the underline is good.
