### ISSUE TITLE
Sim works on prod and not on test

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#3168]
Some PheT sims do not load their page in the test environment for the College Physics book:
![Screen Shot 2020-12-11 at 2.01.27 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/ef7f76bd-1512-4dbc-9d69-3fc84b9463f8)

But some do:
![Screen Shot 2020-12-11 at 2.03.46 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/6a038e61-3f0b-4a02-bfdd-0bff3881fa69)

**Comment by lwtchu** [comment]
@oscryan i think this is the java one where we embedded the website. i think phet doesn't allow that anymore cause it's broken on vendor.cnx. i'll park this with alina tomorrow

**Comment by lwtchu** [comment]
Needs more investigation need to figure out why this is broken and the others aren't. I don't think this is related to the rex view since it's broken on legacy as well. I'll move this to a later milestone since I cannot get to this rn.


Back up - if a user wants to use it there's a link directly to the page above the embed box.

**Comment by lwtchu** [comment]
I think...this was fixed?? https://openstax.org/books/college-physics/pages/6-1-rotation-angle-and-angular-velocity
