### ISSUE TITLE
Extra spacing after some PDF paragraphs

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3315]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

In the business-ethics style.
As you can see in the screenshot below, some paragraphs like the first and second in this example have extra space after them. I do not see a reason for this in the cnxml. It seems to only happen when a paragraph contains a footnote inside of it.
![Screen Shot 2021-01-06 at 11.28.58 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/59eb9c15-5111-44ba-aac8-507120e84c39)

# Acceptance Criteria

# Bug Location(s)
collection ID: col10001
server: content02
chapter/section: 1.1
surrounding text: Indeed, the Founders viewed intellectual property rights

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
I think this might be due to the reference being moved. Adding this to b.b I don't think it's a super complicated fix and shouldn't be a deal breaker for publishing.

**Comment by lwtchu** [comment]
Moving to c.c. since it's still chillin in the backlog

**Comment by lwtchu** [comment]
@wilkus27 @ajluk can y'all take a look at this one - it should be p simple. if it's not, please let me know.

**Comment by wilkus27** [comment]
@lwtchu I did an investigation and found similar problem here: https://www.princexml.com/forum/topic/860/hiding-footnote-call-footnote-markers. Additional space appears because we hide footnote calls autogenerated by Prince and we are using our own tags. As you can read on the page from the link:

![image](https://user-images.githubusercontent.com/40228854/106608291-80626880-6564-11eb-854c-c9b3f7d262ae.png)

There are three advices how this problem could be resolved, but it might be complicated and time consuming. In this case, do we want to fix this problem? If yes, what is the priority and when we should start working on that?

**Comment by lwtchu** [comment]
Interesting - I don't think this warrants that big of an effort right now. I'll put this in the backlog for right now. It's not ideal...but we have a bunch of higher priority things to do. Thank you for looking into this :)

**Comment by yblock** [comment]
This will be an issue in every book with footnotes. Here is an example from Microbiology 22.1, searchable text "The lower respiratory tract, by contrast, is scantily populated with microbes"

![Screen Shot 2021-02-08 at 11.09.22 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/87a2b390-2f90-4b66-9775-7d8870a38d89)

**Comment by wilkus27** [comment]
@lwtchu I fixed that. I tagged paragraphs which contain footnotes references and applied for them negative margin `-0.7rem`. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/108690079-34b73500-74fa-11eb-83c4-6ee033d03f17.png)

As @yblock noticed this was an issue in every book with footnotes, so I made a library wide change. Can you recommend how many books should we test and which ones?

**Comment by lwtchu** [comment]
Testing location discussion on PR: https://github.com/openstax/cnx-recipes/pull/3540#issuecomment-783446543

**Comment by MartaSztuka** [comment]
#### PASSED
##### @lwtchu Since Intellectual Property will be tested on staging I'm closing this issue.
##### Microbiology![Screenshot from 2021-02-24 16-46-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3b4f6724-df83-4056-a2f5-9ccae88e578d)![Screenshot from 2021-02-24 16-53-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e803194c-135a-4206-b2d2-39bba0bdcef0)![Screenshot from 2021-02-24 16-57-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/de5f910b-422a-4424-b1f0-00aa150eb66c)
##### Business Ethics (footnotes are only in Appendices, checked Endnotes as well)![Screenshot from 2021-02-24 17-07-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/52acf2e1-f270-4927-84db-8150b663ba5e)![Screenshot from 2021-02-24 17-04-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a52280b0-99ef-4586-9a85-41ecea98a2ae)![Screenshot from 2021-02-24 17-10-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d022f804-0d0d-4f70-9048-c3a2b6c21ef6)![Screenshot from 2021-02-24 17-11-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92982dab-35ef-4542-a5d4-44fe2eaef7a3)

**Comment by lwtchu** [comment]
![Screen Shot 2021-03-01 at 6 22 26 PM](https://user-images.githubusercontent.com/11299125/109577412-1aadc180-7abb-11eb-9349-b5302997579a.png)
looks fixed in IP couldn't find other parts where it's bad.
