### ISSUE TITLE
economics - introduction

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3360]
The introduction for Economics is a little bit different so here's a card to capture what might be happening in the introduction of Economics. This will deviate from the cosmos theme a little, but still uses same specs for each piece.

### Splash image
- [x] #3357 

### Bring It Home note
- [x] #3359 

### Introduction title
Introduction title follows the SAME header styling in #3164 for module titles
font style: Archivo
weight: semi-bold, 600
font-size: font-scale(3): 15.55pt, 20.4px, 1.7rem
color: R1: `#C31427`

### Chapter Objectives
- [x] #3361

### Other regular content
Other regular content might follow Chapter Objectives, be it:
- another note (Link it Up in ch 3, 17, 32)
- Figure (chapter 7, 17, 19, 25)
- list (chapter 13, 19)
- sub sections (chapter 19)
- quote (ch 33)

**Comment by ajluk** [comment]
@lwtchu Should the quote in chapter 33 be styled similarly to blockquote?: 
![image](https://user-images.githubusercontent.com/55203598/107340724-607bf900-6abe-11eb-8669-44fb59721871.png)

**Comment by ajluk** [comment]
@lwtchu This how looks Introduction page styled in principles of Economics: 
![image](https://user-images.githubusercontent.com/55203598/107361951-6b438780-6ad8-11eb-9cc7-f9ab1683943d.png)
I have styled these headers as regular h3 from the schema: 
![image](https://user-images.githubusercontent.com/55203598/107362057-8ca47380-6ad8-11eb-9ce6-2b161e149cca.png)
Here is the markup for them: 
![image](https://user-images.githubusercontent.com/55203598/107362201-bc537b80-6ad8-11eb-9d9b-87d924b075fc.png)

Should I change something?
I have also left a question about quotes for you here: https://github.com/openstax/cnx-recipes/issues/3364#issuecomment-775784074 because I wasn't sure if the should be styled the same way as blockquotes with (they have different tag: `q`).

**Comment by lwtchu** [comment]
@ajluk h3's are fine. i'll take a look at the blockquotes and comment on the issue

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-02-24 10-45-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ba58d2d4-acb6-4a2a-8bd5-7219d919c85e)![Screenshot from 2021-02-24 10-44-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/464f2a0c-f8e0-4b51-a15b-a11ee0c56d45)
