### ISSUE TITLE
sociology - blockquotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3404]
Documentation #3276

**Comment by MartaSztuka** [comment]
##### @lwtchu Do we want to add bottom margines? When there's none and blockquote is not one paragraph it look's like this:
 ![Screenshot from 2021-01-27 10-20-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/48680869-17b4-40ee-835e-4396ba2e7485)
##### PDF![Screenshot from 2021-01-27 10-21-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4ce212fe-8d71-4514-9a2d-e826670b5fc5)

**Comment by ajluk** [comment]
@lwtchu I have checked the example from above that Marta posted and I'm also wondering if should add some top/bottom margins to blockquotes (I have reset them - set the to 0, they had set 1em top/bottom default margins before), because in cases like this when in `blockquote` tag there is just some text (not a paragraph or a list) it will look like this? What do you think?

**Comment by lwtchu** [comment]
@ajluk if it's set to 0 does that mean it's just the normal line-height? if so, that's ok cause in the documentation i don't see any significant spacing.

**Comment by ajluk** [comment]
@lwtchu Yes, that's right, it is just the normal line-height under the blockquote. Above it is the margin from paragraph before it.

**Comment by lwtchu** [comment]
@ajluk i think so. i can close it. please reopen if there's any issues.
