### ISSUE TITLE
MathML fonts in baked styles

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#3455]
In Fizyka PDFs, in equations some elements appears to have different font than others.
![image (1)](https://user-images.githubusercontent.com/47241114/106623951-6ed58c80-6575-11eb-851e-938c3fa1bb67.png)
![image (2)](https://user-images.githubusercontent.com/47241114/106623956-7006b980-6575-11eb-88d7-987a3c6068f5.png)
![image (3)](https://user-images.githubusercontent.com/47241114/106623963-709f5000-6575-11eb-8c36-482ef112e32c.png)

**Comment by lwtchu** [comment]
@MartaSztuka do you have the chapter/section that this is in.

**Comment by MartaSztuka** [comment]
@lwtchu There is one in vol 3, Chapter 7.3 Równanie Schrodingera, but the problem with letters occurs in random places as well.
![Screenshot from 2021-02-02 17-21-55](https://user-images.githubusercontent.com/47241114/106629523-38027500-657b-11eb-977c-292b2923df42.png)

**Comment by Stackblocks** [comment]
These are MathML converted to SVG, so i'm not sure there are any fonts to work directly with. it may be an issue of the specific character used being displayed in a particular fashion but I don't see any irregularity between the instances of these characters aside from where the upper and lower-case versions of a symbol are used in close proximity. 

Not sure what the next steps on this are, or if there are any.

![2021-02-03_11-53-52](https://user-images.githubusercontent.com/12678235/106907311-ba964c00-66c3-11eb-88d3-d5d8d7daaf8f.png)

![2021-02-03_12-13-02](https://user-images.githubusercontent.com/12678235/106907317-bb2ee280-66c3-11eb-93a4-4aff726ac283.png)

**Comment by lwtchu** [comment]
@Stackblocks is the mathify rendered svg there what you have in the PDF? cause the one that i got off of corgi (in my screenshot) has a different h symbol 🤔 i wonder if it's something in corgi then

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/106910236-a43dbf80-66c6-11eb-93b2-8d477627743f.png)


This is what it looks like in the PDF generated with the Bakery CLI, which matches up with the mathified.xhtml

**Comment by ajluk** [comment]
@lwtchu @Stackblocks I have regenerated the PDF on current `c.c` branch using the old pipeline and then the straightened ħ  looks good:
![image](https://user-images.githubusercontent.com/55203598/107055461-9f196700-67d1-11eb-8068-85d639f2b92d.png)
I have also asked Marta to test these symbols once again using the new pipeline (bakery CLI) (because I had only old content) and CORGI and there it looks bad again.
I have also tried the bakery-cli and got the same result even after updating the bakery CLI and add Stix General as a fallback font to the carnival theme locally : 
traightened ħ
![image](https://user-images.githubusercontent.com/55203598/107055705-d9830400-67d1-11eb-9a55-245c5da34f0f.png)
three dots
![image](https://user-images.githubusercontent.com/55203598/107056061-3bdc0480-67d2-11eb-8952-ada2d88dc974.png)
So my guess is that the reason this is happening is that the bakery-cli somehow doesn't support some math fonts. 
This is the list of unrecognized symbols, which has been listed in the stderr file: 
- Unicode Character “…” (U+2026)
- Unicode Character “∞” (U+221E)
- Unicode Character “℃” (U+2103)
- Unicode Character “ ” (U+200A)
- Unicode Character “ℏ” (U+210F)
Sample of the error: 
SVG - Unknown character: U+2009 in STIXMathJax_Main,STIXMathJax_Monospace,STIXMathJax_Latin,STIXMathJax_Alphabets,STIXMathJax_Marks,STIXMathJax_Arrows,STIXMathJax_Operators,STIXMathJax_Symbols,STIXMathJax_Shapes,STIXMathJax_Misc,STIXMathJax_Variants,STIXMathJax_Size1

**Comment by lwtchu** [comment]
@ajluk let me know if the problem still persists. i can move this over to the CE team for them to take a look

**Comment by ajluk** [comment]
@lwtchu Do suggest I should check again? I'm asking because I have checked it out last friday, have anything changed in the new pipleine since then?

**Comment by lwtchu** [comment]
@ajluk i don't think so - if you want I can bring this to Bey and her team to look at. This is strictly a CLI problem, correct?

**Comment by lwtchu** [comment]
Issue moved to [openstax/cnx #1431](https://github.com/openstax/cnx/issues/1431) via [**ZenHub**](https://www.zenhub.com/)
