### ISSUE TITLE
odd arrangement in 3-column glossary

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3480]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [x] styles [ ] both [ ] i don't know

![Screen Shot 2021-02-08 at 10.33.26 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/c12efe44-56a9-4bde-9f4b-ebbd97639e15)

![Screen Shot 2021-02-08 at 10.33.17 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/4e0af40c-7ff9-4d3b-8053-f1a36460064a)

# Acceptance Criteria
LC: I think we might've fixed this in the other themes. can we make sure it's going down then to the right?

# Bug Location(s)
collection ID: col12087
server: production
chapter/section:  glossary 
surrounding text: a next generation sequencing technique

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by wilkus27** [comment]
@lwtchu This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/108213876-c6582880-712f-11eb-8be3-f2a58c62af86.png)

For some reason it displays wrong because of `section` tag with class `column-container`. It should be changed in the content to `div`. I did it locally:

![image](https://user-images.githubusercontent.com/40228854/108214252-3ebee980-7130-11eb-94ad-cfffaa663e42.png)

Also I had to change a little bit shape for appendix because of a new markup. It has an impact on all books. Do you know if any other book from Carnival has glossary in appendix? If yes, we have to make the same content change for it and I have to set the proper color for header in styles for this book.

**Comment by lwtchu** [comment]
@wilkus27 do you know what changed? from what i understand in the content side we didn't really mess with the mark up.

**Comment by wilkus27** [comment]
@lwtchu I think it always looked like that. We just didn't notice that it displays wrong. Also it's not a common element. In most of books Glossary is a separate EOC section. I don't know if any other book has Glossaries from entire book in one Appendix. 

For example there is no problem with columns in Index. There are only `divs` not `sections`.

**Comment by lwtchu** [comment]
@wilkus27 interesting 🤔  i will have to investigate a bit before I move this card. need to figure out what the div/section stuff is in CNXML. thank you!

**Comment by lwtchu** [comment]
@wilkus27 i think ...this is nested in a section with a class to set it to flow into columns
![Screen Shot 2021-02-22 at 3 37 08 PM](https://user-images.githubusercontent.com/11299125/108773381-e28b0980-7523-11eb-9d74-ae17854c5fbf.png)

Should i remove the parent `<section>`? And just have it be free flowing sections?

**Comment by wilkus27** [comment]
@lwtchu I checked and we don't use divs in CNXML. Sorry for the confusion. It's something that has to changed by recipes. I created release flag for that and applied it to all books from Carnival theme for now. 

Do you know which of these books have class `column-container`? I think it will be ok to test only them. If not, should Marta test all books from Carnival?

**Comment by lwtchu** [comment]
@wilkus27 i think only microbiology has it. 🤔

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-25 10-46-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8af79fe4-431c-4877-867e-a5b73d06faf9)
