### ISSUE TITLE
footnote links are very close 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3481]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

Multiple footnote links are so close they appear to be a single object. In this case 1, 2, and 3 looks like 123. 

![Screen Shot 2021-02-08 at 10.44.09 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/640414c1-93bd-4b40-adfc-240b3d644149)

# Acceptance Criteria
LC: can we add some padding to the right of the number? 

# Bug Location(s)
collection ID: col12087
server: production
chapter/section: 21.1
surrounding text: the most common residents in the healthy

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by yblock** [comment]
In this same example, footnote 3 is pushed to the next page. I'm not sure if that is intended, as it seems they usually live on the same page they are referenced on.

**Comment by ajluk** [comment]
![Uploading image.png…]()

**Comment by ajluk** [comment]
@lwtchu Regarding the second comment (https://github.com/openstax/cnx-recipes/issues/3481#issuecomment-775289750) added to this issue I have checked locally if this problem can be fixed with our current footnotes markup and the property which Prince uses to force to fit footnotes on the same page as the line/paragraph with footnotecall (`prince-footnote-policy`) can be only added to the paragraph which contains footnotes inside it. It can't be done in the current footnote markup we use, because the footnote element (`aside[role="doc-footnote"]`) is placed outside the paragraph: 
![image](https://user-images.githubusercontent.com/55203598/108360646-c0c31700-71f1-11eb-9ef4-a047032ef7fa.png)
I have tried to add this property to paragraph which contains footnote call, but it doesn't work.

**Comment by lwtchu** [comment]
@ajluk i'm not completely sure what is happening 😂  can we discuss on teh call tomorrow

**Comment by ajluk** [comment]
@lwtchu can we create separate issue for this problem - https://github.com/openstax/cnx-recipes/issues/3481#issuecomment-775289750 and link it ? I'm asking because I have approved PR with changes adding padding to separate footnotes links?

**Comment by ajluk** [comment]
@MartaSztuka during testing this issue all you need to check is if the footnote links have some space between them if there more than one line in the screenshot from above: https://github.com/openstax/cnx-recipes/issues/3481#issuecomment-781294629 . I have created separate issue for based on Colby's comment about ffotnotes jumping to the next page here #3548.

**Comment by MartaSztuka** [comment]
##### PASSED![Screenshot from 2021-02-24 12-40-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e2b7f05-ecc8-439e-87cd-2d8fe82c8031)
