### ISSUE TITLE
"glossary" not supported in business-ethics style

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3515]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [x] both [ ] i don't know

The glossary section is not being styled and navigation anchor is not being made in the corgi pdf, however it does appear to be supported in web. 

# Acceptance Criteria

# Bug Location(s)
collection ID: col32642
server: production
chapter/section: Glossary
surrounding text: 

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
Can we have the business ethics recipe also target the `<glossary>` but if it's not there it doesn't show up? Headers can follow regular EOC sections. Title can be `Glossary`. If it's not possible, please let me know.

**Comment by wilkus27** [comment]
@lwtchu @yblock The problem is with collection number. On katalyst01 there is a content with `col25722`. And locally everything looks good. I generated PDF in CORGI for this number with content from production and it also displays properly. Here is the link: https://openstax-cops-artifacts.s3.amazonaws.com/col25722-latest-production-241.pdf .

![image](https://user-images.githubusercontent.com/40228854/108694873-e9078a00-74ff-11eb-841a-2a6ae7fad02f.png)


![image](https://user-images.githubusercontent.com/40228854/108694911-f4f34c00-74ff-11eb-8a88-bb9a440a73db.png)

**Comment by lwtchu** [comment]
@wilkus27 actually i see the problem - sorry i thought it was marked up the same

@yblock we'd have to make this an appendix actually 😬

**Comment by lwtchu** [comment]
@yblock i'm gonna park this tomorrow

**Comment by lwtchu** [comment]
this needs appendix class :eyes: on document tag. will figure out when to reimport this
