### ISSUE TITLE
anthropology - enable tutor exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3588]
Books moving forward will be using tutor exercises for assessments. This will be using the nickname functionality (used in APUSH/LLPH)

range of exercises is 25098-25101 (numbers in case we need to look it up)

They are on production so make sure you're pointing to exercises.openstax.org

**Comment by ajluk** [comment]
@lwtchu as we discussed on the call I'm closing this one, because it appeared that the exercises has been fetched properly into the Anthropology book: 
![image](https://user-images.githubusercontent.com/55203598/110513924-0b57f500-8107-11eb-9ed3-8e3366deae3e.png)
Link to the eoc exercises issue:
https://github.com/openstax/cnx-recipes/issues/3590
