### ISSUE TITLE
BCA - section number treatment

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3788]
Documentation #2710 (blue version)

**Comment by ajluk** [comment]
@lwtchu The first section has a very long title and because of that the number in a box looks like it is too long: 
![image](https://user-images.githubusercontent.com/55203598/114055204-d8815800-9890-11eb-9a6e-4015556a66e9.png). I guess we didn't have such case previously in cardboard theme. Should it be fixed within working on BCA now?

**Comment by lwtchu** [comment]
@ajluk 😬 okay i'll make a note. i think theyre testing the length of the titles. - are there alternative solutions like making it smaller and vertically centering? (we don't have to implement right now - just wonderiing if there's a fix)

**Comment by ajluk** [comment]
@lwtchu I think it is possible to fix it similarly as we did for appendices or toc, but I need to check off course.

**Comment by lwtchu** [comment]
@ajluk okay - i think it's fine for now since it's test content. i'll make a note that if they plan on having long titles, we will need to make a slight change to accomodate.

**Comment by lwtchu** [comment]
big card was closed out, closing these little ones too
