### ISSUE TITLE
BCA - table middle row styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3792]
Similar functionality to #3665
The row has a class on it `<row class="header-row">`

Uses #2741 specs for Second Header row (if present)

**Comment by ajluk** [comment]
@lwtchu I couldn't find `header-row` class in all BCA book.

**Comment by ajluk** [comment]
@lwtchu Here is how it looks in text-heavy tables (grey bg, no borders):
![image](https://user-images.githubusercontent.com/55203598/114596899-7362a380-9c90-11eb-90b4-f2def9f8a21c.png)
Do you want also border bottom added to the middle row header as it is present in the first header, I skipped it because I thought it could be too much, but let me know if it is needed there as well.

**Comment by lwtchu** [comment]
@ajluk can we also add the border-bottom line 😬  it'd be good to keep it consistent with the header row specs - i edited the documentation card to say it should basically match :)

**Comment by ajluk** [comment]
Sure! :slightly_smiling_face:

**Comment by ajluk** [comment]
@lwtchu Thank you! It is how the middle row looks in text heavy tables: 
![image](https://user-images.githubusercontent.com/55203598/114694130-8621ba80-9d1a-11eb-90a2-d76d6dd0a58b.png)
And in default and top titled tables: 
![image](https://user-images.githubusercontent.com/55203598/114694452-d26cfa80-9d1a-11eb-8d96-a6964ef1750b.png)
I needed there to add additional top and bottom borders to the middle header row td's to to cover the borders that are added to td's before and after the middle header row: 
![image](https://user-images.githubusercontent.com/55203598/114694614-00523f00-9d1b-11eb-9fa6-accc5ea54fab.png)
Additional borders:
border-bottom-style: solid,
        border-bottom-color: #24739E;
        border-bottom-width: 0.08rem, //1px converted to rem
        border-top-style: solid,
        border-top-color: #24739E;
        border-top-width: 0.10rem, //1px converted to rem
And I have additional question, should I also do this trick to first header row, because how it is done now cause problem when tables don't have `thead`. See https://github.com/openstax/cnx-recipes/issues/3790#issuecomment-816777531. Let me know if there will be some tables present withoud a `thead` in the cardboard theme books and if need a fix?

**Comment by lwtchu** [comment]
@ajluk this looks good - i think it might be better practice to do this trick to the first header row. it'll make the table look more complete if it doesn't have a thead (which we might encounter...but I can't think of any right now)

**Comment by ajluk** [comment]
Ok, no problem, I will rework the shape. Should it be done within bca PR (styles and recipes) or rather later on when current PR will be already reviewed and merged? I'm asking because if the the recipe and styles are needed faster I can open a separate card for the first header row and td under it borders.

**Comment by ajluk** [comment]
@lwtchu As we discussed I have opened a separate card for first header rows tds without top borders: #3816

**Comment by lwtchu** [comment]
big card was closed out, closing these little ones too
