### ISSUE TITLE
BCA - eoc assessment sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3794]
There are 7 sections that all basically look the same.
![image](https://user-images.githubusercontent.com/11299125/112520529-83f6bc80-8d69-11eb-9b23-4cc3cbbed802.png)

- standard multiple choice exercise and will be pulled from exercises.tutor.org
- exercise number is bolded with period
- spacing between each exercise is the same as business ethics: 0.7rem
- numbering resets after every composite page

# Review Questions `review-questions`
icon: https://drive.google.com/file/d/1Ltc0whfkE49KScYfgJ_72T7f99_T7Brk/view?usp=sharing
title: Review Questions

# Conceptual Questions `conceptual-questions`
icon: https://drive.google.com/file/d/1lVezUadPa780bzW-XuOYTP_kbmi0_UmO/view?usp=sharing
title: Conceptual Questions

# Now You Try It `you-try`
icon: https://drive.google.com/file/d/1Oz3Ej81o-JVLC75amloQ3m-YPDH-hoCN/view?usp=sharing
title: Now You Try It

# Practice Exercises 
icon: https://drive.google.com/file/d/1LxWsRljZtkKxBDxQQOgFbrvtDRevOc2D/view?usp=sharing
title: Practice Exercises

# Written Exercises
icon: https://drive.google.com/file/d/1vcm1CNvUjMIXogG_ceitE4-I_wiAKdJl/view?usp=sharing
title: Written Exercises

# Case Exercises
icon: https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing
title: Case Exercises

# Extension Exercises
icon: https://drive.google.com/file/d/1-IA4Gbm1OlPC2bg8lSedIUUIrjvZdBrB/view?usp=sharing
title: Extension Exercises

**Comment by ajluk** [comment]
@lwtchu should the exercise numbering reset after every section/composite-page or chapter?
I reset it first  after every composite page/section:
![image](https://user-images.githubusercontent.com/55203598/114222367-cf66b880-996e-11eb-9eb3-c4a5d66e2141.png)
I'm asking because above you wrote: "numbering is 1, 2, 3, etc and continuous for the chapter" and I'm not sure if I understood it correctly and the numbering should rather continue through every section and reset after chapter like this: 
![image](https://user-images.githubusercontent.com/55203598/114223199-d17d4700-996f-11eb-9a85-242b854507e2.png)

**Comment by lwtchu** [comment]
@ajluk i looked at the prototype again and i think it resets every composite page. i rewrote the spec line - what you have initially is correct. thank you for checking :sob:

**Comment by lwtchu** [comment]
note: @ajluk went on leave before the comment above can be implemented. since it's already gone to the vendor, I would prefer that we wait for t heir feedback and implement changes if they request it. I'll close out this card and if they want a change I'll open a new card~
