### ISSUE TITLE
english composition - unit opener 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3936]
![Screen Shot 2021-06-24 at 12 14 04 PM](https://user-images.githubusercontent.com/11299125/123305481-c30de880-d4e5-11eb-880c-106392423209.png)

done a long long long time ago in the old pipeline so prince can do it, but not sure how to do in baked styles https://github.com/openstax/oer.exports/issues/2693 

Specs for screenshot above

## Unit number
font style: Archivo Black
color: R2: `#8B1504`
weight: regular, 400
size: font-scale(7): 32.25pt, 43.2px, 3.6rem

## Unit title
font style: Archivo Black
weight: regular, 400
color: black `#000000`
size: font-scale(7): 32.25pt, 43.2px, 3.6rem

## Paragraph text 
class: `<section class="unit-opener">` in the `introduction` module.
font style: Archivo
weight: regular, 400
color: black
size: font-scale(1): 10.8pt, 14.4px, 1.2rem

## Block colors
background: R2: `#8B1504`
light box: R3: `#FFE5E5`
radius round corner: 135

**Comment by lwtchu** [comment]
Comment for stuff left to do: https://openstax.slack.com/archives/C022NETP39N/p1624645350115500

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-07-01 14-21-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/839f2145-9776-43f5-be77-39425eb5f1d7)

**Comment by wilkus27** [comment]
@lwtchu As I write here https://github.com/openstax/cnx-recipes/pull/3955#pullrequestreview-696166969 Anna just put unit opener section into the H1 for now, to achieve quick solution, since we need English Composition be ready as soon as possible. I'm trying to rework this now. What I wanted to do was moving section under the H1. And I found solution how to do this but then I realized that all changes in recipes that we make have inpact on webview. We can't move section just in PDF. So my question is, where text from unit opener section should be displayed on cnx/rex? I guess we need to create a whole new module with header and metadata before chapters. I mean collection for unit should contain single module, something like Introduction, and then collections of chapters:

![image](https://user-images.githubusercontent.com/40228854/124426042-bf8e2300-dd69-11eb-8c6e-53856b55d45b.png)

Because on webview each module is a separate webpage. When we do that we have to think about styles in PDF. There will be additional header created for unit introduction module, so we will need new design for that.

**Comment by lwtchu** [comment]
@wilkus27 we need to test with the recipe. The webview on CNX shouldn't be relevant anymore since we're no longer releasing things there. Is it removed from teh TOC on the recipe?

**Comment by wilkus27** [comment]
There will be the same problem on rex:

![image](https://user-images.githubusercontent.com/40228854/124488191-db1c1c80-ddaf-11eb-80b4-6a421715beb5.png)

I mean, any text has to be in some module, because on the website (rex and cnx) each module is the separate page. Unit is not a module, similar as chapter. They are just collections of modules. So there are no pages for units and chapters, we can see just their titles in the TOC, and when we click on it, we have list of modules, that we can open. So about your question, there is still title of the unit in the toc, but what we need to do is to create some module, which will be visible in the TOC right under the unit title, and when we click on it we go to the website with text from unit opener section.

**Comment by lwtchu** [comment]
@wilkus27 ah okay 🤔  do you have a fix in mind. i think anna couldn't find another way to avoid it

**Comment by wilkus27** [comment]
The best solution will be to create module in legacy and nest it directly inside the unit, like we nest modules in chapters. It should be doable, but Legacy is Legacy, so who knows :smile: . Actually I can create similar structure by recipe. I mean something like that:

```
div[data-type="unit"]
  |-- div[data-type="metadata"]
  |--h1
  |--div[data-type="page"]
     |--h2
     |--section.unit-opener
  |--div[data-type="chapter"]
```
but this page under the unit title wouldn't have id and metadata, because they should be added in the content. I can't generate it by recipe. So this solution might be not enough for other projects (rex/tutor/corgi).

If Legacy fail, we can try to use Adaptarr. We can make such nesting there.

**Comment by lwtchu** [comment]
@wilkus27 i think i can do that... 🤔  do you want me to try?

**Comment by wilkus27** [comment]
@lwtchu This is how it looks after content changes:

![image](https://user-images.githubusercontent.com/40228854/125077818-d44c1d00-e0c1-11eb-83aa-3f704eed4dba.png)

How unit page title (pointed by arrow) should be styled? It is styled now like regular H2 from Cosmos theme. Should I change something?

And this is how it displays when text jumps to the second page:

![image](https://user-images.githubusercontent.com/40228854/125078007-1aa17c00-e0c2-11eb-8101-fddad2fd821e.png)

**Comment by wilkus27** [comment]
And this is how it looks in TOC:

![image](https://user-images.githubusercontent.com/40228854/125078190-59373680-e0c2-11eb-9bc3-7b2b084bbe77.png)

I styled it like chapter modules links. Is that ok?

**Comment by lwtchu** [comment]
@wilkus27 🤩  can we make the text area wider by maybe 1 more inch so that we can fit more text 😬  also is it possible to remove the page in the TOC? it's a bit redundant

**Comment by wilkus27** [comment]
Yes sure, I can decrease paddings :slightly_smiling_face: 

About title, it has to be there, because on the webview there should be a title that you can click on and then it opens a page with unit content. So it has to be named differently than unit title. This is what I was talking about here: https://github.com/openstax/cnx-recipes/issues/3936#issuecomment-874169373

**Comment by lwtchu** [comment]
@wilkus27 ooooh okay i will let them know 🤔  maybe we can come up with something thank you ⭐  it looks so great

**Comment by wilkus27** [comment]
@lwtchu This is how it looks with smaller paddings:

![image](https://user-images.githubusercontent.com/40228854/125101485-8abbfc00-e0da-11eb-955a-df37e2cc0e0b.png)

**Comment by lwtchu** [comment]
@wilkus27 beautiful 🤩  moved this into the n.n. milestone also

**Comment by lwtchu** [comment]
![Screen Shot 2021-07-22 at 2 15 08 PM](https://user-images.githubusercontent.com/11299125/126696648-d181801c-aa5c-4fe2-8e4c-70369609afc0.png)
present adn verified on corgi
