### ISSUE TITLE
Need to Translate "Access for free at openstax.org" to Spanish for PDFs

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#3959]
# Brief Description of Change and Screenshots
What kind of change is this? [ ] recipe [ ] styles [x] i don't know

![Screen Shot 2021-06-28 at 9 50 06 AM](https://user-images.githubusercontent.com/7863733/123657254-41c09980-d7f6-11eb-8bb8-6a1b7aacd7b6.png)

Please let me know if you need JR Language to provide and/or verify the translation. Thank you!

# Acceptance Criteria

# Content Location(s)
collection ID:
server:
chapter/section: 
surrounding text:

**Comment by lwtchu** [comment]
@KarinaMendez2 before you  go,  do you think you could translate t his :eyes:

**Comment by Stackblocks** [comment]
Good news / bad news time:

**Good News:** These two folio elements are no longer in English
**Bad News:** These two folio elements aren't in Spanish either. They're missing in both local and CORGI bakes.

This will need to be resolved, but first we need to ID if this is a showstopper for the impending release of Spanish University Physics, or can it be fixed in post?

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3360e831-77d5-45a4-a08c-ba4795fb0c3e)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e3379068-faf3-4532-b0b7-d787a138daf9)

**Comment by Stackblocks** [comment]
Fixed via https://github.com/openstax/recipes/commit/b8147eb8ec36c15bcbbb4c12b15bf6fdd9cd35b6! 
![image](https://user-images.githubusercontent.com/12678235/130130803-0c668159-9533-4b94-b485-241795778d8a.png)
