### ISSUE TITLE
References in American Government 3e start on even page number in PDF

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#4004]
The PDF has a blank page between Answer Key and References that bumps References to an even page number.

<img width="828" alt="Screen Shot 2021-07-19 at 12 04 40 PM" src="https://user-images.githubusercontent.com/1895432/126199598-335af444-a34a-4a56-a185-15edd38d4f8f.png">

**Comment by lwtchu** [comment]
The desired behavior should be if it falls on an even page, insert a blank page to make it odd. And if it's on an odd page,  no change.


This should be the same behavior as the first chapter, preface, TOC and appendices

**Comment by ajluk** [comment]
@lwtchu I'd like to only confirm that the References are displaying on even page as they should.

**Comment by lwtchu** [comment]
@ajluk it should start on odd so it'll start on the right hand side. - do you know where the page break rules live? i want to take a look. i think something wasn't done right previously where someone just inserted a page vs making a break for it to start only on odd

**Comment by ajluk** [comment]
@lwtchu Thank you, I got it wrong before. The reason why it is not working is that the References selector in this book differs from the rest. It is `reference` not `references`, so the final selector after baking in the EoB is `os-eob.os-reference-container`. The page break rule was only added for the `os-eob.os-references-container` previously. All main page break rules are added in `styles/designs/common/pdf/_page-breaks.scss`. Here is how it displaus after the fix: 
![image](https://user-images.githubusercontent.com/55203598/140933210-ceee3f20-ebcc-4d7c-9e30-93fa741faf68.png)

**Comment by Stackblocks** [comment]
References now starting on 649
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8a651967-70f8-4dfc-bdb9-4a68e2d25d43)

**Comment by ajluk** [comment]
@Stackblocks I guess it is happening because the blank page before References staring page is not there now (wasn't needed anymore) because previous page is ending on the left page and References should now start on the right one:
![image](https://user-images.githubusercontent.com/55203598/141844908-4243857c-bb3c-4ada-a2ac-a728f1cdc74b.png)
![image](https://user-images.githubusercontent.com/55203598/141844533-7f04346e-bac9-4563-8ca6-c6e28d33bc34.png)

**Comment by lwtchu** [comment]
@ajluk :eyes: i thought the criteria was for it to start on the odd page/left

**Comment by ajluk** [comment]
@lwtchu Now the page displays on right page (this is after my changes): 
![image](https://user-images.githubusercontent.com/55203598/142845195-9e63ff88-5cc5-482f-826a-51fd487ab399.png)
I've got confused again here :sweat_smile: , because on the first screenshot describing the issue it is shown how it looked before (the page displayed on the left side). So I guess the goal was to reverse it and I have done it. The References page is also displaying consistently to ToC, Peface etc now.: 
![image](https://user-images.githubusercontent.com/55203598/142846349-f47bf0cf-6be1-447d-ab6d-d03b06986140.png)
![image](https://user-images.githubusercontent.com/55203598/142846296-ffce86ed-06ff-4eb6-bf83-091560614506.png)

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3fee7d16-fbf3-4058-9c53-9910bcaf4351)
