### ISSUE TITLE
OPS-0012 Composition

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4017]
In  the Introduction section, the "INTRODUCTION" word is appeared in the PDF View. But not view in the Web View. Kindly check and advise.

Web view:
![image](https://user-images.githubusercontent.com/86622862/127530263-0765a892-6dec-4f9d-ad5e-d853bd812c6b.png)

PDF view:
![image](https://user-images.githubusercontent.com/86622862/127529885-9d10fc69-6ce0-4226-8d6f-f66f1282f7ab.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us11.gitpod.io/
chapter/section: Chapter 18, Introduction
surrounding text: Chances are you already have a great deal of experience with

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
This is by design. The introduction text in the pdf is pulled from the module title as a stylistic setting but can be found at the top and in the TOC bar on webview.
![Screen Shot 2021-07-30 at 2 47 19 PM](https://user-images.githubusercontent.com/11299125/127704491-458c0269-8d93-4881-ade1-c712c50614ec.png)
