### ISSUE TITLE
OPS-00012 | Composition - Web & PDF view generated issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4035]
We have created the draft TOC as per the customer instruction. And also, we have updated the global changes Chapter, section, figure and table number duplicated issues, captions and term issues. Push content option runs the successful. But web view & PDF view didn't convert properly. The below errors screenshot shown in CORGI. We couldn't be able to find the error. Kindly check and resolve this issue.

![CORGI_Error_MSG](https://user-images.githubusercontent.com/86622862/128255499-f7ff920f-a66d-4239-b881-fe69b42cb9f1.png)

# Bug Location(s)
collection ID: osbooks-writing-guide/writing-guide
Job id: 1231
server: https://corgi.openstax.org/
chapter/section: Chapter 18
surrounding text: CORGI Issue

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by lwtchu** [comment]
@ne-newton  - I just posted this in the ce channel. :eyes:

**Comment by lwtchu** [comment]
We found two issues:
1st is in this module, there is a `<div>` tag. This is not supported in the module please remove it.
![Screen Shot 2021-08-05 at 11 56 59 AM](https://user-images.githubusercontent.com/11299125/128390650-1c745812-f8bb-4a60-9d59-55a8585dc5c6.png)

2nd there must be content inside the `<content>` tags. There should be an error that pops up with a list of acceptable content to place in the tag. I would suggest placing small placeholder text for the time being.
![Screen Shot 2021-08-05 at 11 57 15 AM](https://user-images.githubusercontent.com/11299125/128390651-a617242b-8717-4836-a927-8a438ea89c5c.png)

Once these two issues are fixed, please try again and let us know if the issue persists.

**Comment by srm-openstax** [comment]
As per your instruction, I have deleted the <div> tag and insert the placeholder text in all XML files. But, we have faced the same issues.
![CORGI_Error_MSG](https://user-images.githubusercontent.com/86622862/128404033-9090245e-8cb0-41b9-9796-74c3650067c5.png)

![Placeholder_XML](https://user-images.githubusercontent.com/86622862/128403954-178f803b-657f-4cef-8320-6dc94b979b20.png)
![CORGI_Error_MSG](https://user-images.githubusercontent.com/86622862/128403956-8b38d574-5db1-481c-961f-9e46f925829f.png)

**Comment by lwtchu** [comment]
Okay I think we found the issue.

Could you 
1. Add back the `<div/>` per the instructions in my edited comment (you might've caught the first instance of the comment where I said to delete it). 

and 

2. Go into the collection.xml and remove the Case Study Profile: What One Person Says About All chapter. Those modules are already being used and a module can only appear once within the collection structure. In the meantime I will open a card for Neil's team to build in better validation so that we can avoid this in the future. 
![Screen Shot 2021-08-05 at 2 29 11 PM](https://user-images.githubusercontent.com/11299125/128409626-47678da2-47ab-4daa-b5c9-b181b126640e.png)

**Comment by srm-openstax** [comment]
Working fine. PDF & Web view converted successfully. Thanks for your support.
