### ISSUE TITLE
finance - update timeline table design

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4050]
![Screen Shot 2021-08-06 at 4 48 55 PM](https://user-images.githubusercontent.com/11299125/128574385-9e8b96dd-0c07-4294-8857-ea88a972976c.png)

`<class="timeline-table">`

specs  stay mostly the same please make the following changes
- [x] remove top and bottom border
- [x] remove left and right border
- [x] tighten spacing - this is about 2px all around. what's the smallest we can go without exploding the style?

**Comment by ajluk** [comment]
Hi @lwtchu, welcome back! :relaxed:  I have a question about timeline tables - are they book specific (only present in finance book) or can they be spotted in different books from cardboard theme? I'm asking because we added styles for these tables within shapes created for default and fake titled tables and the shapes were used by different books. So the timeline tables styles were present in css files for other cardboard books and the books could utilize them. But during working on removing the outer borders for timeline tables I needed to create separate shape for these tables and I wanted to confirm with you if it will be ok to remove the old timeline tables styling added within default and top titled shapes and include the new styling with removed outer borders only in finance book? Or rather should I include the shape also in other cardboard books just in case they can be there and also should they have removed outer borders? Thank you!

**Comment by lwtchu** [comment]
@ajluk let's add this shape in other cardboard books as well - and keep it with the timeline-table tag. the old timeline-table style should be overridden with this one.

**Comment by ajluk** [comment]
@lwtchu Oh, ok. I will remove the old styles then. Thank you!

**Comment by ajluk** [comment]
@lwtchu the padding in the tables cells isn't 2px actually, but 0.7rem which gives 8.39px I have set it to 2px (0.16rem) now and this is how timeline tables look like then: 
![image](https://user-images.githubusercontent.com/55203598/130515369-58f10ba8-c12d-4491-9023-4297ce2fda7b.png)
![image](https://user-images.githubusercontent.com/55203598/130515387-d605ff79-fc51-4078-92dd-9c2aa67e0228.png)
![image](https://user-images.githubusercontent.com/55203598/130515748-570c6c8c-02df-4287-b7f3-3598bbc19e5b.png)
![image](https://user-images.githubusercontent.com/55203598/130515798-93f623a5-613b-4f7d-9fe0-c260b96cde91.png)
Should I keep it or make the padding a little bigger? Let me know what do you think?

**Comment by lwtchu** [comment]
We can leave it as is-- what is it now? Book specific?

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-08-31 11-59-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7ce3bfa6-a2e8-4e42-934f-f6387adf4549)![Screenshot from 2021-08-31 11-59-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e4fc4e22-b91b-481d-9644-d51985d8b604)![Screenshot from 2021-08-31 11-58-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/42094379-003c-4ae9-9fc4-e02b817de501)![Screenshot from 2021-08-31 11-58-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c4f95a4a-01f4-44e1-8911-e98fc4b4548a)
