### ISSUE TITLE
world history - eoc assessment formatting for required context

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4177]
![Screen Shot 2021-10-25 at 1 34 30 PM](https://user-images.githubusercontent.com/11299125/138750850-8764b911-b62e-4e46-a255-61d530acaf0d.png)

1. i assume the numbering will be fixed with the release this week (i think the recipe goes out?)
2. is there a way to move the requires context to AFTER the question stem? In the screenshot can we have "Figure 1.2" show up after "How did Cornelia represent..."

**Comment by ajluk** [comment]
@lwtchu I have discussed this issue with @kswanson33 while working on requested changes on my related PR and Kendra has enlightened me that there can be more `question-stems` in one `injected-exercise`, so when I will move the `exercise-context` figure reference to the `exercises-question` it could be confusing where the `exercises-contetext` is reffereing to if there will be more. So my question is if there can be more exercise `questions-stems` in one questions when there is an `exercises-context` present? And for that reason we were also wondering if moving `exercise-context` can be done in the content side instead of Kitchen? It is still possible in Kitchen if it will be problematic on the content side. Let us know what do you think?

**Comment by kswanson33** [comment]
@lwtchu to add on, this could be done in a similar way to `question-stimulus` vs `exercise-stimulus`. Right now, context is only ever created on the exercise, but it sounds like sometimes it needs to exist on the question. Creating it in the question instead of the exercise will avoid ambiguity, in the case of multi-part exercises, re: which question gets the exercise context.

On the other hand, if this feature would be too hard to add to the content side, it might not be worth doing. Will the context need to be moved on all single-part questions, and only single-part questions? If that's the case, I think we have a good way to hack this on our end without changing how the content side is set up.

**Comment by lwtchu** [comment]
@kswanson33 @ajluk i can't move anything on the content side as it's just a field in exercises.openstax.org. the assumption is that the requires context will be applicable to the entire question - so I'll have to think about this for a bit and maybe discuss with alina

**Comment by lwtchu** [comment]
@ajluk can we just make "Refer to _____" to go after 4. and then it's okay if there's a line return after it 

i think this is the issue

**Comment by ajluk** [comment]
@lwtchu The Kitchen [PR](https://github.com/openstax/kitchen/pull/432) has benn already reviewed by Kendra and merged :tada: 
As I checked there will be small changes needed in the styles make the reference and divider display inline in the problem container, so I will open a separate PR for it. 
Here are the steps from the Kitchen PR:

**Comment by lwtchu** [comment]
@ajluk thank you!

**Comment by ajluk** [comment]
@lwtchu as we discussed I have only styled inline the `context-reference` and the `divider` after it. I have left `question stem` untouched, because I was afraid if it will contain the math it could break it: 
![image](https://user-images.githubusercontent.com/55203598/141825869-9bd6db17-219d-4bf1-badf-35027dda743f.png)
PDF: 
![image](https://user-images.githubusercontent.com/55203598/141826141-d1911fda-167a-4e18-9cec-3d66c4b01411.png)

**Comment by ajluk** [comment]
@MartaSztuka To test this issue you need to checkout on `recipes` repo in the book-pipeline to `main` and also on `cnx-recipes` to `wonderous-warsaw`(both of the PRs has been already merged).

**Comment by MartaSztuka** [comment]
#### @ajluk List formatting in EoC is correct, but numbers and abc-s should be right aligned.
![Screenshot from 2021-11-16 12-33-35](https://user-images.githubusercontent.com/47241114/141978314-2d3e02a6-6ca0-4eff-9986-c1ae8c0b2f94.png)
![Screenshot from 2021-11-16 12-35-14](https://user-images.githubusercontent.com/47241114/141978450-6121a1b9-d06e-4bbd-b1ed-3cc838d0dd27.png)
![Screenshot from 2021-11-16 12-35-37](https://user-images.githubusercontent.com/47241114/141978455-0745da63-7755-44bd-a62e-f6a64105bc57.png)

**Comment by ajluk** [comment]
@MartaSztuka you can retest the answers lists in the exercises.  :slightly_smiling_face:

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2021-11-17 08-51-19](https://user-images.githubusercontent.com/47241114/142158344-3ce26afa-8345-4575-9465-943dfa1ca854.png)
