### ISSUE TITLE
contemporary math - section exercises title incorrect

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4206]
![Screen Shot 2021-11-08 at 2 50 50 PM](https://user-images.githubusercontent.com/11299125/140816429-a9ab2870-f4ee-4e23-855f-cb0893c76961.png)
Screenshot shows 1.7 module is referencing 1.6 exercises. It should match the module number

Documentation: https://github.com/openstax/cnx-recipes/issues/2463

**Comment by lwtchu** [comment]
@lwtchu needs to move content to playground for testy test

**Comment by kswanson33** [comment]
numbering is being thrown off by the lack of a `section-exercises` section in page 1.3. I wonder if this (currently unbaked) section is meant to have the `section-exercises` class instead of just `exercises`?

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/04093f57-2fec-4118-bd32-ca2230851d09)

**Comment by lwtchu** [comment]
Still happening but in chapter 2 now

**Comment by LostMojo** [comment]
It looks like all the section exercises in chapter 2 of Contemporary Math's numbers match up!

**Comment by Stackblocks** [comment]
![CleanShot 2022-06-09 at 17.54.36.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/be7f9a95-f6fb-4ce9-902c-6e04647d89f2)
