### ISSUE TITLE
writing guide - extra space in handbook header numbering

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4251]
![Screen Shot 2021-11-23 at 12 27 31 PM](https://user-images.githubusercontent.com/11299125/143082937-1e0c036f-6222-4b1f-94db-ae0df7fc9d84.png)

is it possible to remove the space between `H#` and the `.` ?

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-11-25 14-23-58](https://user-images.githubusercontent.com/47241114/143449400-8d60edca-dc95-4087-a05d-dc09edb92f90.png)

**Comment by openstaxalina** [comment]
I see this fixed in the [PDF](https://openstax-cops-artifacts.s3.amazonaws.com/writing-guide-latest-git-2685.pdf), but I don't think our fix translated to [REX](https://rex-web.herokuapp.com/books/ee7ce46b-0972-4b2c-bc6e-8998c785cd57@835f2e7/pages/handbook?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20211206.184556). This is not a showstopper so I will wait for L to get back to confirm whether we need to reopen this issue or open an issue on REX's board.
![Screen Shot 2021-12-07 at 12 36 51 PM](https://user-images.githubusercontent.com/7863733/145086875-4df3f77f-a9d2-4e8b-a268-8a3fbf8f366f.png)

**Comment by wilkus27** [comment]
@openstaxalina this problem is related with styles not recipe, so my changes didn't affect Rex. PDFs and webview are styled separately, so issue should be opened on the REX side as well.

**Comment by openstaxalina** [comment]
@wilkus27 thank you for letting me know this is styles! I will open another for REX. Thanks again.

**Comment by openstaxalina** [comment]
On second thought, I don't think this is pressing enough to open an issue for REX; it would be better to wait until REX adopts baked styles. Leaving this closed and not opening an issue for REX right now.
