### ISSUE TITLE
(RECHECK WHEN WE DO BAKED STYLES FOR WEB) HS Physics - injected exercises numbering wonky

### ISSUE THREAD

**Issue by theresamasciale** [openstax/cnx-recipes#4272]
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [x] i don't know

Numbering is wonky when generating a web preview of high school physics (both regular web preview and git web preview). Numbers are off and show up either every other question...or sometimes not at all. Larissa suspects this is an issue with injected exercises.

![Screen Shot 2021-12-01 at 10.55.09 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/6ca60aad-e470-4ed5-890d-0970e5b1aea6)![Screen Shot 2021-12-01 at 10.55.21 AM.png](https://images.zenhubusercontent.com/5c51e1f3d9d1826f38fa04cc/73f8148c-8814-41d9-b413-860aa02f32be)

# Does this happen for every instance? If no, is there a discernable pattern of occurrences?
It seems to be occurring with injected exercises.

# Sample mark up if applicable

# Acceptance Criteria
Fix numbering

# Bug Location(s)
collection ID: col12081
github openstax/osbooks- link: 
chapter/section: 2.2 "Practice Problems" and End of chapter 2 chapter review "concept items"
surrounding text: "Practice Problems" "concept items"
Link to preview: https://rex-web.herokuapp.com/books/physics@36855b7/pages/2-2-speed-and-velocity?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20211111.153520

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
github openstax/osbooks- link: 
chapter/section:
surrounding text:

**Comment by kswanson33** [comment]
When generated locally with richb-press, I can't reproduce the numbering error:

![image](https://user-images.githubusercontent.com/26280712/144465270-fad4c4ce-6fab-4023-8dbb-d870c0c4363e.png)

![image](https://user-images.githubusercontent.com/26280712/144465396-bda24ae2-3c38-4b52-969f-39c41a91ac26.png)

The styles are definitely messed up for injected exercises in "Practice Problems", but the numbering should be fine, and I can confirm that the code for numbering both types of exercise is present in the kitchen recipe.

One thing that would definitely cause this discrepancy is if the old recipe was used, instead of the kitchen recipe. It could be something else, but that's my best guess for now. It looks like it was added to `bake_root` 13 days ago, so pretty recent update.

![image](https://user-images.githubusercontent.com/26280712/144466668-9f35aa57-563d-4636-b0e1-013b9cc5d6fa.png)

**Comment by lwtchu** [comment]
oh ...maybe this new release will have the things we need? i'm gonna boop this over to regression te sting so @Stackblocks can double check.

**Comment by Stackblocks** [comment]
Generating a web preview of the collection listed above with the HS-Physics recipe, I'm seeing all of the numbering but the alignment is all over the place on both EoS and EoC questions. Probably warrants some additional investigation

![2021-12-06_15-31-24.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e9e2ed80-30fa-4017-9e49-d294ca73dd1d)

![2021-12-06_15-33-06.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3f55e9a1-34d2-4e08-8ccb-c94c9582caf1)

**Comment by lwtchu** [comment]
@Stackblocks when you're back we might need to revisit this since it kind of fell off the radar. i need to come u p with a process for us to open cards for rex and to keep track of them

**Comment by lwtchu** [comment]
![Screen Shot 2023-01-20 at 11 25 49 AM](https://user-images.githubusercontent.com/11299125/213764279-1a6341d8-c19e-4a4d-bc74-e04fce477085.png)
surprise it's fixed. prob with other cards
