### ISSUE TITLE
Enable footnotes in table captions

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#4295]
# Brief Description of Change and Screenshots
What kind of change is this? [x] recipe [ ] styles [ ] i don't know

(The text with the footnote is "Table 14.3 Calculator Steps for Finding the Relationship between Nike Stock Price and Value of S&P 500")

![Screen Shot 2021-12-07 at 4 40 27 PM](https://user-images.githubusercontent.com/7863733/145117012-39ed4850-9785-4e74-8ff2-f3855ebb70c2.png)

# Acceptance Criteria
- [ ] footnotes display on the PDF when originating from a table caption
- [ ] footnote numbering between PDF & web matches

# Content Location(s)
collection ID:
github openstax/osbooks- link: github.com/openstax/os-books/intro-finance
chapter/section: 14.1
surrounding text: see above to know where the footnote originates. the footnote should appear at the end of 14.1 after the text "routine basis".

**Comment by wilkus27** [comment]
@openstaxalina In PDFs we are displaying footnotes description on the page where footnote reference appears.

![image](https://user-images.githubusercontent.com/40228854/146553239-f9d61930-33f0-44d1-9346-c3681ce04984.png)

I believe it was done in this way because in printed version it's better for the reader to look to the bottom of the page, not going to the end of the module a few pages later. Do we want to change it?

**Comment by openstaxalina** [comment]
@wilkus27 thank you - I was not thinking clearly when I opened this card 🤦‍♀️  No, we do not want to change where we display footnotes on the PDFs. I am going to close this... @lwtchu FYI, at our next sync w/ Phil we will discuss his question about footnotes being in the "old" style. But this card is not about that issue.
