### ISSUE TITLE
0013-Philosophy Write like a philosopher section alignment issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4341]
We have received the below correction from customer, and we coded as per the tagging legend. But, write like a philosopher section elements didn't support in output. Kindly check and resolve this issue.

**Change Part II to a Write Like a Philosopher feature. Treat like a feature with icon and box.**

![Philosophy_Write_Correction](https://user-images.githubusercontent.com/86622862/148329223-0dfb73a4-1623-4ae3-87d3-f0871fca3653.png)
![Philosophy_Write_CNXML](https://user-images.githubusercontent.com/86622862/148329247-93ec26b0-7d26-4b28-9033-be9fafab0469.png)
![Philosophy_Write_Like_Philosopher](https://user-images.githubusercontent.com/86622862/148329235-57f44da0-087a-4b0e-9a3b-c6d41a1c2a50.png)

# Bug Location(s)
collection ID: col00005
github openstax/osbooks- link: https://coffee-grouse-ulafn81g.ws-us25.gitpod.io/
chapter/section: Chapter 2/Section 6
surrounding text: Use the following templates to write your own thesis statement

**Comment by lwtchu** [comment]
# Acceptance Criteria
Should be simple nested list in feature fix.

**Comment by ajluk** [comment]
@lwtchu With the unstyled and unbaked note it is a content issue. There is a typo in the note class (`write-philosopoher` instead of `write-philosopher`): 
![image](https://user-images.githubusercontent.com/55203598/149301824-07e24557-76e2-4b1a-b52a-1a3f1ceb0281.png)
This is the reason also for the list to have no left margin (there is a div missing which we add during the baking `div class="os-note-body"`) ans the list shape doesn't work properly.

**Comment by lwtchu** [comment]
@ajluk Sorry I didn't notice earlier.

**Comment by lwtchu** [comment]
@srm-openstax Can you fix the typo in the class?

**Comment by lwtchu** [comment]
Closing the issue - didn't hear back post class fixing. Please re-open if it's still an issue.
