### ISSUE TITLE
Move all recipes to one kitchen version

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4377]
PROS: should help with all book issues and in the future if there are new features, old books won't be really impacted unless specific books call upon it
CONS: we need better testing #4371 - solution could be here

ANYWAY this is a place to hold all ideas

**Comment by kswanson33** [comment]
Going in the merge repos direction 🎉 

Will need to:
- Freeze further kitchen/recipes work for the duration of the merge (not easy to import new kitchen/recipes additions into the combined repo after the merge starts); hopefully the merge itself will not take more than a day. 
- Alert CE that the pipeline should be rerouted through the new repo (name pending) instead of recipes

**Comment by kswanson33** [comment]
https://github.com/openstax/cookbook
