### ISSUE TITLE
figure without id should not get numbered - ignoring numbering for figures in embedded exercises 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4445]
This came up during a REX discussion.

TOM: there is a figure on this page with no id https://openstax.org/apps/archive/20220118.185250/contents/6c322e32-9fb0-4c4d-a1d7-20c95c5c7af2@29.1:2b6c3067-855e-4317-81b8-f5ee216d68c7.xhtml
(context: https://openstax.slack.com/archives/CH5514N57/p1643900662728899) 

The idea is to make them a part of the exercise and not number them since they do not get ID's when they are pulled in. However before we do this global change, need to see how frequent this is. Not sure how though.

**Comment by lwtchu** [comment]
Add criteria to figure method to avoid numbering no ID figures (`figure_to_number`).

**Comment by lwtchu** [comment]
Please use sifter to find these figures @kswanson33 :eyes:

**Comment by wilkus27** [comment]
To clarify, we are using two methods to bake figures: `BakeFigure` and `BakeUnnumberedFigure`. Figures without numbering should be baked as well, because they have to be wrapped into `os-figure` container and they can contain caption that also need some modifications. Most of the books have both of these methods, so now if they contain figure without id it won't be numbered but still will be baked. 

Here are books that needed some additional changes:

1. Astronomy - didn't use `figure_to_number` option for figures from Preface
2. Contemporary Math - `BakeUnnumberedFigure` was added before method that adds `unnumbered` class to figures from solutions from some sections (`div.your-turn, section.section-exercises, section.chapter-review, section.chapter-test`), so they were not baked
3. English Composition - didn't have  `BakeUnnumberedFigure` method
4. Marketing - didn't use `figure_to_number` option for figures from Appendix

**Comment by Stackblocks** [comment]
- Displays OK with updated code from eldritch.etymology & content from main.

_(Image not rendering in local xhtml output because directory pointers are funky, but the markup is correct to the best of my understanding.)_

Follow-up and additional work woud best be split off additional work into separate cards, should we choose to pursue it from here.

![CleanShot 2023-03-07 at 11.53.37.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/350c2416-b36b-49d0-9e30-7bb411d493d5)
---
![CleanShot 2023-03-07 at 11.55.54.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/da440a17-79f9-4c36-b2cd-27445a3ff613)
