### ISSUE TITLE
add special data attribute to Writing Guide Trailblazer subtitles

### ISSUE THREAD

**Issue by bethshook** [openstax/cnx-recipes#4483]
Rex needs a way to select Writing Guide Trailblazer page subtitles without affecting headings in other books. Would be great if the `h3.os-subtitle` element on those pages included `data-type="document-subtitle"`

**Comment by lwtchu** [comment]
Since we are already manipulating the content for the Trailblazer classed can it just be prompted by the `<document class="narrative-trailblazer"> <content class="narrative-trailblazer">`? And we add that data attribute to JUST that title? In case we have other cases of h3.os-subtitles later that aren't... in a trailblazer-esque feature

**Comment by bethshook** [comment]
Yeah, I think we're saying the same thing - `document-subtitle` should only be a thing on the Trailblazer pages.

**Comment by LostMojo** [comment]
Coobook changes added in [Cookbook #25](https://github.com/openstax/cookbook/pull/25)

**Comment by Stackblocks** [comment]
Class getting created properly with latest cookbook.

![2022-02-24_18-56-32.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/420215a1-d78b-49c3-86d0-ade3739f75a5)
