### ISSUE TITLE
Anatomy and Physiology - bullets in lists in Chapter Objectives not styled or indented

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4578]
# Brief Description of Scenario and Screenshots

Also, chapter level LOs in introductions are not styled/indented as they are in subsequent LOs in the chapters:

See here in the introduction the bullets are not indented and are black,
<img width="881" alt="Screen Shot 2022-03-15 at 9 44 43 AM" src="https://user-images.githubusercontent.com/5865292/158404241-2508ef91-0fe4-4e57-a6c9-6f386521a437.png">

and in the non-introcution lists they are indented and greenish,
<img width="632" alt="Screen Shot 2022-03-15 at 9 46 36 AM" src="https://user-images.githubusercontent.com/5865292/158404161-298747bc-0185-4ce5-9254-f391d4dd35f0.png">

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Appears to happen in all cases of bulleted lists within table cells

# Acceptance Criteria
bullet point placement will be adjusted so that it falls within its respective cell. 

# Sample mark up if applicable

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-anatomy-physiology
collection slug (if applicable): anatomy-and-physiology
chapter/section: 
surrounding text: After studying this chapter, you will

**Comment by wilkus27** [comment]
@lwtchu I checked and it was a regression after kitchen changes. Previously (in easebake) Chapter Objectives note wasn't baked properly, it didn't have `os-note-body`. It was fixed in kitchen, but we didn't make a correction in shape for styles. After I added component for note body, this is how it looks:

![image](https://user-images.githubusercontent.com/40228854/160091949-b0bfae2f-789f-43e7-8bbb-16ae258b7d06.png)

So this is how we styled this element at the beginning when we were working on Carnival theme. Do we want to change specs now? Should I add an indent for list? What about a first paragraph? Is it ok that it's blue and italic?

**Comment by lwtchu** [comment]
@wilkus27 can we remove the italics and blue color for the first para? to keep it in line with learning objectives and to clean it up a bit.

**Comment by wilkus27** [comment]
@lwtchu This is how it looks:

![image](https://user-images.githubusercontent.com/40228854/160643329-80334487-89d5-4fd3-a723-768d133b2bc2.png)

For para I removed color and italic font, also I set margin bottom to `0` and decrease font size from `font-scale(1)` to `font-scale(0)` as it is done in Learning Objectives. Is it ok, or should I change something?

**Comment by lwtchu** [comment]
@wilkus27 this looks great :)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-03-31 10-19-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cbc59fcf-3254-4a69-8aae-937b62b386ca)
