### ISSUE TITLE
carnival theme (A&P) - reduce font size for headers

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4591]
Summary: Reudce font-size(6) on [this file ](https://github.com/openstax/cnx-recipes/blob/516ad5039afddcf5d8799b049c2d13666a33a220/styles/designs/carnival/parts/_titles-components.scss)to font-scale(5) - please also reduce the line-height

Headers impacted:
H1s in chapter text and appendix and titles 

A&P is called out for testing purposes, but this should impact all the books in the theme.

**Comment by wilkus27** [comment]
@lwtchu I made some additional changes. I decreased font for H1, but also for `os-text` in Chapter H1 from `font-scale(4)`, to `font-scale(3)` and I made some changes for paddings and margins in these titles. 

In Anatomy it decreases page count from 1365 to 1363, but e.g. in Chemistry nothing changed. It's still 1209 pages.

This is how titles look now:

![image](https://user-images.githubusercontent.com/40228854/161023864-4e9d74d8-0249-4682-8a21-b65b8676f119.png)

![image](https://user-images.githubusercontent.com/40228854/161023974-a6de74b2-9ccd-4e79-a578-25fd33b0d40a.png)

![image](https://user-images.githubusercontent.com/40228854/161024051-858a771d-41b7-4b1c-94bb-5f3be9d6bd34.png)

![image](https://user-images.githubusercontent.com/40228854/161024223-8309059a-26ee-41fb-a192-ba55c9ab29ac.png)

![image](https://user-images.githubusercontent.com/40228854/161024302-e240469f-6597-4d2e-b555-5a1157381779.png)

**Comment by MartaSztuka** [comment]
#### PASSED
#####
#####
#####
#####
#####
#####

**Comment by MartaSztuka** [comment]
#### PASSED
##### ANATOMY AND PHYSIOLOGY
![Screenshot from 2022-04-01 15-05-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/89a4c45b-0f8f-41a0-8fb8-2a1f13d6677b) ![Screenshot from 2022-04-01 15-23-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99715218-a6a0-4d4e-8a79-216c37046bab)
##### COLLEGE PHYSICS
![Screenshot from 2022-04-01 15-13-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/924ea709-e237-4f33-b687-f931fba6459e)
##### AP PHYSICS
![Screenshot from 2022-04-01 15-18-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/eb03d4df-acde-4261-bfa4-c65de9c5cf87)
##### UNIVERSITY PHYSICS 1
![Screenshot from 2022-04-01 15-19-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/eaf0ee09-d284-42b0-ba97-e18013bc9ff5)
##### UNIVERSITY PHYSICS 2
![Screenshot from 2022-04-01 15-22-17.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5d5683ea-4246-4edd-8747-2bd77b4fc09d)
##### UNIVERSITY PHYSICS 3
![Screenshot from 2022-04-01 15-24-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f764e278-ecaf-4340-b0af-975a474f82a2)
##### BIOLOGY 2E
![Screenshot from 2022-04-01 15-26-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c5025210-73ba-4c5a-ad9b-3d1a171a34d6)
##### BIOLOGY AP COURSES
couldn't test due to content issue 
##### CHEMISTRY 2E
![Screenshot from 2022-04-01 16-10-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5be546d7-e3f4-4ea9-84dc-c5bd3d440241)
##### CHEMISTRY AF
![Screenshot from 2022-04-01 16-11-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b1bd2fca-70d7-4916-bdd1-e04a0e7c4c20)
##### MICROBIOLOGY
![Screenshot from 2022-04-01 16-11-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d9dd8731-ead4-4e8c-93ec-e4a5db049ee4)
##### ANTROPOLOGY
![Screenshot from 2022-04-01 16-13-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/423a7395-8123-402c-abef-70f4d13f4576)
FIZYKA

**Comment by MartaSztuka** [comment]
Fizyka will be tested later, Closing the issue.
