### ISSUE TITLE
Add space between solution title (h4) and images as first children in solution containers in examples - theme wide

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4661]
![image](https://user-images.githubusercontent.com/55203598/168312218-41a3b9ca-3424-4db1-9120-e54c9b84f3d4.png)
![image](https://user-images.githubusercontent.com/55203598/168312273-247c0c46-96ff-4dbb-8cc5-774c70a6b773.png)

**Comment by wilkus27** [comment]
### Information for tester
It should work for dev-math books.
I applied this change to all themes, but it might not work everywhere because a change in recipe is also needed. If you find such cases let me no, so then I'll make fixes in cookbook. Also this might not fix all places because examples have different markup in some books.

**Comment by MartaSztuka** [comment]
#### PASSED
###### ELEMENTARY ALGEBRA
![Screenshot from 2022-05-23 13-34-10.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1cff7d04-2598-4127-b290-b4c0e3cdf595)
###### PREALGEBRA
![Screenshot from 2022-05-23 14-26-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5df8a221-ca74-4474-a600-9f67fe614c1e)
###### INTERMEDIATE ALGEBRA
![Screenshot from 2022-05-23 14-53-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92880298-1337-4870-ade6-4f7a0a5ead76)
