### ISSUE TITLE
[Entire Library] Equations can cause overflow in parent container (loose math rolling around the book)

### ISSUE THREAD

**Issue by jivey** [openstax/cnx-recipes#4686]
# Brief Description of Scenario and Screenshots

In REX, when the text size of the content is increased, math equations can cause undesired overflow in the parent container, rather than overflowing the math equation container itself.

![image.png](https://images.zenhubusercontent.com/5db706861484010001787b7f/6e0dad2a-2b9f-418b-a2d3-52f17d316c8f)
![image.png](https://images.zenhubusercontent.com/5db706861484010001787b7f/90c4767b-81be-48df-bea4-cb3eb4a2e893)

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.

Only when the math is long enough to overflow.

# Acceptance Criteria

The math container scrolls horizontally when overflow occurs and does not overflow the parent container.

Create a div to  go around the equations so it can be targeted by the overflow container that Josiah created on REX.
Make sure  styles isn't impacted.

# Sample mark up if applicable

# Location(s)
github openstax/osbooks- link: 
collection slug (if applicable):
chapter/section: 
surrounding text:

**Comment by openstaxalina** [comment]
prioritization note: per @tomjw64 , Text Resizer can be launched before this is fixed.

**Comment by openstaxalina** [comment]
CE Styles' fix will likely be to put math that is not already in a container into divs

**Comment by wilkus27** [comment]
@lwtchu Previously `BakeEquation` method was added only to books that contain numbered equations, that is: `ap-physics-2e`, `ap-physics`, `calculus`, `college-physics-2e`, `college-physics`, `hs-physics`, `pl-u-physics`, `u-physics`. 

Now it should be added to each book that has any equation. I found in samples from tests that equations appear also in `chemistry`, `accounting`, `anatomy`, `astronomy`, `biology`, `contemporary-math`, `dev-math`, `economics`, `microbiology`, `pl-economics`, `precalculus`, `statistics`. Should I add equation method anywhere else?

**Comment by lwtchu** [comment]
@wilkus27 i think that should be ok - is there a way to make sure BakeEquation will add to all books with equations in the future?

**Comment by wilkus27** [comment]
@lwtchu I'm afraid not :confused: Someone who is working on a new recipe has to get an information that equations appear in a book, and then apply a needed method.

**Comment by wilkus27** [comment]
@kswanson33 I have a question about webview styles. When I open REX preview it uses styles come from less files from rex repo, not from file created in ce-styles. And there is such property added:

![image](https://user-images.githubusercontent.com/40228854/189066154-08ce88de-50d3-435b-85c6-b360514dea95.png)

But in inspector it shows up as:

![image](https://user-images.githubusercontent.com/40228854/189066797-590114ad-f66d-49d4-ae3b-eefb7dedf790.png)

Do you know how this first selector is added?

I'm asking because when I'm adding the same property to our `webview-generic.css` it's overwritten by property from `#main-content`:

![image](https://user-images.githubusercontent.com/40228854/189067307-4437dee2-b686-4d4f-8f4b-f6bedee01142.png)

It won't be if my selector be `#main-content [data-type="equation"]`.
Is it going to be added after "merging" our styles to rex repo or it's working in another way?

**Comment by kswanson33** [comment]
@wilkus27 Yeah, this is the current expected behavior. [Here](https://openstax.atlassian.net/wiki/spaces/CE/pages/2126413825/Styling+web+content#TO-PREVIEW-STYLES-CHANGES) is the documentation on previewing styles changes. There's also a section on context below. I added some info to answer the questions you ran into here

**Comment by wilkus27** [comment]
@kswanson33 Thank you for explanation :relaxed: In that case, what should be the process of testing? Should we skip it until our styles will be connected to rex?

**Comment by wilkus27** [comment]
Above I'm asking about testing webview. @lwtchu for which books we should test PDFs? These changes have an impact on all themes.

**Comment by lwtchu** [comment]
@wilkus27 where is the change located? is it in cookbook or did we also change webstyles?

**Comment by wilkus27** [comment]
@lwtchu The change is added to cookbook, PDF styles and web styles.

**Comment by lwtchu** [comment]
@wilkus27 lets do one in each theme with some math? Maybe accounting, calculus (pick a vol), university physics (pick a vol) and economics?
