### ISSUE TITLE
organic chemistry - figure and caption styling

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4735]
documentation: #1081

**Comment by Stackblocks** [comment]
I see the commit for the fix in my `git log` but when I generate the pdf the figures aren't styled. I've checked and made sure my local repo is up-to-date and I manually removed the output directory and re-generated, so I don't believe it's a local / user error. 

![CleanShot 2022-07-14 at 15.56.31.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f5ed39dd-6750-4562-b09c-0be07e3adedc)
![CleanShot 2022-07-14 at 15.56.49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7f62e84b-99d4-4d88-819f-7294f08c5aad)
![CleanShot 2022-07-14 at 15.57.59.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a532d266-1911-49b4-be46-c15c8e252106)
![CleanShot 2022-07-14 at 15.58.14.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ed9ea135-3565-46bd-8164-1db1e0a2c45f)
![CleanShot 2022-07-14 at 15.56.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1602bb14-a9a3-4d32-a12a-fda668038331
)

**Comment by Stackblocks** [comment]
I regenerated it today and it works fine in the HTML output but for some reason my PDF version doesn't want to cooperate. 

The good news is that it appears to literally be just me since it works fine on CORGI staging 😂

![CleanShot 2022-07-18 at 16.16.17.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2112b86d-074f-473b-b31f-7472eb89bf97)
