### ISSUE TITLE
anatomy and physiology 2e - diseases of the ... note title unstyled

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4747]
![Screen Shot 2022-06-28 at 12 47 00 PM](https://user-images.githubusercontent.com/11299125/176248928-8431c342-36a5-4eb3-8d4f-e6d2df42c68e.png)
#4746 - documentation

it's just missing the styling for the title and the subtitle (Heart: Myocardian Infarction)

**Comment by lwtchu** [comment]
@wilkus27 fixed the content

cc @theresamasciale we'll have to update the content version for A&P whenever this code pipeline goes out around end of august?

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![CleanShot 2022-07-26 at 16.00.40.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c37f0b3d-a748-4c68-84cf-598a19d48c44)

There _is_ one `Diseases of...` title that isn't styled buy it's nested in a `Disorders of...` note so that seems like a content issue. We can create a new card if this needs to be styled as well.

![CleanShot 2022-07-26 at 16.00.25.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e9d9aed2-ec5a-4cd9-9f42-12376730cab8)
