### ISSUE TITLE
organic chemistry - end of secion/module, end of chapter and numbering schema for assessments

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4749]
## Problems (end of module)
`class="section-exercises"`
Title: Problems
Numbering: They number continuously through the EOS sections and reset at every chapter.
![Screen Shot 2022-06-29 at 9 41 25 AM](https://user-images.githubusercontent.com/11299125/176465088-7cec7633-3848-429f-b9f1-898039575d89.png)

Is there a way to set multi part questions (MPQ) with this specific numbering in the recipe? ^

# Exercises
Can we have a subpage for the end of chapter called Exercises (done in other carnival theme books)

## Visualizing Chemistry (end of chapter)
`class="visualizing-chemistry"`
Title: Visualizing Chemistry
Numbering: Starts where the Problems (above) leaves off 

## Additional Problems (end of chapter)
`class="additional-problems"`
Title: Additional Problems
Numbering: Starts where the Visualizing Chemistry leaves off

MPQ structure applies to the whole book.

**Comment by wilkus27** [comment]
@lwtchu Since section exercises have solutions that are moved to Answer Key, we need to add section numbering to title **Problems**. Otherwise we don't know from which page these solutions are. What would be the best: **1.3 Problems**, **Section 1.3 Problems** or maybe something else?

Also, because section exercises are not in every page, but numbering in title has to be the same as page numbering (not shows the number of sections with `section-exercises` class), I have to change a way of counting. That's why I need to make sure, is there a case in any book where section exercises appear in introduction page?

**Comment by lwtchu** [comment]
@wilkus27 Let's call them `Section 1.3`

**Comment by lwtchu** [comment]
@wilkus27 actually .... i'm not sure if the author would want it there. let's leave it as the default for now `1.3 Problems`

**Comment by wilkus27** [comment]
### Information for tester

1. Title `Problems` should have also numbering, e.g `1.3 Problems`. It should appear within modules and Answer Key.
2. Multipart Questions should display as `(a) (b) (c)`.
3. H3 from section with class `section-exercises` was not styled. Not sure if it exists in other Carnival books.
4. I had to apply more specific selector for `os-problem-container`, because in Multipart Questions it appears twice and has different properties depends on where it's nested. This change has an impact on all Carnival books. Shouldn't change anything visually, but it would be good to check exercises (regular and injected) in a few books.

**Comment by MartaSztuka** [comment]
#### PASSED
###### ORGANIC CHEMISTRY
![Screenshot from 2022-07-29 15-55-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7ce4250d-b2e4-4f55-b113-db9fb5037965)
![Screenshot from 2022-07-29 15-56-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f4efd5db-bae6-462a-9fa3-601d5e476aca)
###### AP PHYSICS
![Screenshot from 2022-07-29 16-07-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/63a1075b-6095-4496-b2eb-01943aa49406)
![Screenshot from 2022-07-29 16-07-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/445e697b-b529-43e9-bad9-a722f08f0670)
###### COLLEGE PHYSICS
![Screenshot from 2022-07-29 16-08-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/127b8696-2e4c-4d35-9c24-5151afda77f7)
![Screenshot from 2022-07-29 16-09-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ef496a95-25d7-4997-b352-a2399ce9ef06)
###### FIZYKA 1
![Screenshot from 2022-07-29 16-09-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f676d73a-d082-4ac4-bd25-54d0762a7620)
![Screenshot from 2022-07-29 16-09-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3f741d71-cc41-4e60-ae98-9d405d9009cc)
