### ISSUE TITLE
ap physics 2e - phet explorations styling missing

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4762]
# Brief Description of Scenario and Screenshots
WHAT IT LOOKS LIKE 
![image](https://user-images.githubusercontent.com/11299125/177594163-dd97e9d3-8b00-4101-a24f-97ecb640ce59.png)

WHAT IT SHOULD LOOK LIKE
![image](https://user-images.githubusercontent.com/11299125/177594203-30a0742a-4eac-4d26-a534-5de6fba18035.png)
^ This screenshot is from college-physics-2e

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Yes - it's missing styling 

# Acceptance Criteria
It is styled. LIke above

# Sample mark up if applicable
`<note xmlns:m="http://www.w3.org/1998/Math/MathML" id="fs-id2006949" class="interactive"><title>Equation Grapher</title><para id="import-auto-id2044902">Learn about graphing polynomials. The shape of the curve changes as the constants are adjusted. View the curves for the individual terms (e.g. <m:math><m:mrow><m:mrow><m:mrow><m:mi>y</m:mi><m:mo stretchy="false">=</m:mo><m:mstyle fontstyle="italic"><m:mrow><m:mtext>bx</m:mtext></m:mrow></m:mstyle></m:mrow></m:mrow></m:mrow></m:math>) to see how they add to generate the polynomial curve.</para>`

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-college-physics-bundle
collection slug (if applicable): ap-physics-2e
chapter/section: it everywhere 
surrounding text: equation grapher is one of the titles for the feature

**Comment by Stackblocks** [comment]
PHET Explorations are breaking right above the link when at the end of the page. Since the link is the only thing that gets split to the next page it looks a little funky. @lwtchu what do you think?

![CleanShot 2022-07-13 at 16.09.50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fc63a0a3-0fe3-4f73-a3c5-17966cd36966)
![CleanShot 2022-07-13 at 16.09.25.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/de3211ea-88a9-4c27-91fb-dba8d60045bb)
![CleanShot 2022-07-13 at 16.08.53.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6c45b4ca-8834-4a98-98d6-2063486e3856)

**Comment by lwtchu** [comment]
Since we  don't believe the PDF has malicious intent and that it's just coincidentally breaking here, I say it's not a problem

**Comment by lwtchu** [comment]
![Screen Shot 2022-07-18 at 4.59.54 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/cac88527-ccb1-4a62-90d4-50d197a60868)
VERIFIED ON STAGING HUZZAHA
