### ISSUE TITLE
due at end of s.s. maybe - organic chemistry - anchor text for figures and tables reflect styling of labels

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4810]
# Acceptance Criteria
- cookbook can detect the label type - what is the extent? of this? can we detect equations/tables/figures/modules/etc
- the anchor text gets tagged with a class to enable styling
- styling for each anchor  text reflects the same style as the label (set at 9pt font to match surrounding text, but make font style mulish, the respective color and all caps)
blue: B5: `#0078a3` - tables
red: R1: `#C31427` - figures
- green G3 `#007A49` - others??? not sure how we can target other module links - is that possible?

## for tables
![Screen Shot 2022-08-10 at 11 28 56 AM](https://user-images.githubusercontent.com/11299125/183963790-bc02286e-4f1a-43a5-aeda-ed39c3458003.png)
![Screen Shot 2022-08-10 at 11.29.00 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/749d29b8-5a2c-4e70-aa5f-85ed7aa0edee)

## for figures
![Screen Shot 2022-08-10 at 11 17 54 AM](https://user-images.githubusercontent.com/11299125/183961372-5a29a56c-a4f1-46a5-805d-b91daf13a0d1.png)

**Comment by wilkus27** [comment]
@lwtchu I made a change for figures and tables:

![image](https://user-images.githubusercontent.com/40228854/186436075-9a873c74-93ab-4498-9e86-2a84be6e149f.png)

We can detect other elements that you mentioned. Modules as well, but link to them should be created like for tables/figures. Now text is hard coded in content.

**Comment by lwtchu** [comment]
@wilkus27 i added a  `Testing <link document="m00003"/>.` to the top of the Atomic Structure: Orbitals module for testing. Figure  and Table link looks amazing!!!!

**Comment by wilkus27** [comment]
@lwtchu That's what it looks like:

![image](https://user-images.githubusercontent.com/40228854/186625531-fe7879cb-b32c-48f0-a354-8ce40a2b721b.png)

I wasn't sure about styles, so I applied the same as for tables and figures. Should I change only color to green (don't change font and make it uppercase)? Also to make sure, green will be applied to all other elements then tables and figures or only to modules? I'm asking, because I'm not sure what selector choose, more general or specific only for modules.

Oh, and in recipe we are adding also numbering to links to modules. Is it ok for this book? Or do you want me to change that for Organic Chemistry?

**Comment by lwtchu** [comment]
@wilkus27 i think what you have there is fine - we can test it with the vendor team and such and see if they'll be on board with it.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-08-29 13-19-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/916702c8-d6fd-49f6-9dbf-4566c59fb720)
![Screenshot from 2022-08-29 13-20-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0ae22829-078a-45b0-a7d8-05b8c5b7f22b)
![Screenshot from 2022-08-29 13-20-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7b5ab510-36f2-45c9-882e-312986180c4a)
