### ISSUE TITLE
organic chemistry - mechanism figures

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4814]
![Screen Shot 2022-08-10 at 1 22 05 PM](https://user-images.githubusercontent.com/11299125/183988153-feb0cb1a-4c05-4ca3-8c7a-fa9d13ad04d0.png)

class: `<figure class="mechanism-figure">`

Move figure and figure title up to a box shaded with G4: `#C3E2C3`

Move caption to a box between the figure/title and image with a 1px width on the sides with the same color G4: `#C3E2C3`

If possible can it match the width of the figure?

The box with the  1 2 3 and graphics are an entire image.

Padding within the boxes should be v-spacing(1)? and 0 between the boxes

**Comment by lwtchu** [comment]
@lwtchu to add tag

**Comment by ajluk** [comment]
@lwtchu I have moved the caption elements over the figure via cookbook and put figure title, number and title label to separate container `os-caption-title-container`and put capation text to `os-caption-text-container`. Here is how the markup looks:
![image](https://user-images.githubusercontent.com/55203598/185442820-cd289e06-46ea-44a4-ba63-1c32fed6e248.png)
Let me know if this acceptable also for webview.
Here is how it looks styled in pdf: 
![image](https://user-images.githubusercontent.com/55203598/185443002-73c71506-1b81-40ec-964a-9c78bad9c645.png)
What I was struggling with is the small gap between the caption border and the figure itself (zoomed to 200%): 
![image](https://user-images.githubusercontent.com/55203598/185443148-eb42be39-db07-4570-a0e4-297d85bdfbd4.png)
Is that acceptable?
I have also tried with adding bottom border to caption text container and here is how it looks then:
![image](https://user-images.githubusercontent.com/55203598/185444370-b50e8d92-2ec9-4398-b576-786678a48223.png)
![image](https://user-images.githubusercontent.com/55203598/185445189-6716ff0f-7165-4a72-a0a4-597123a48798.png)
There is one more thing, the third figure is jumping to the next page, despite that I have added a page break to caption containers I have created. It is caused by the bigger image probably in this case:
![image](https://user-images.githubusercontent.com/55203598/185444527-b75dcfae-1f25-4806-be44-8fc7e2e999ca.png)
It looks better with the caption text container bottom border: 
![image](https://user-images.githubusercontent.com/55203598/185445322-03a467f8-e57e-448c-96bf-ec913c35839c.png)
Let me know what are your thoughts Larissa. :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk it might be less noticeable if we set the stroke of the box to 2px? can we try that?

**Comment by ajluk** [comment]
@lwtchu It worked! :tada: :
![image](https://user-images.githubusercontent.com/55203598/185451149-b2d371a1-59c8-48df-a47b-4f6b32f6a117.png)
Thank you for the idea!
Will the cookbook changes be fine with the webview?

**Comment by lwtchu** [comment]
@ajluk is it possible to generate a preview locally? if it's broken, we can make a separate card to fix later

**Comment by ajluk** [comment]
@lwtchu Sorry, yes it is possible. I should have generated it for you before asking. :sweat_smile:  Here is how the caption looks for such figures in rex preview (quite good actually :slightly_smiling_face: ): 
![image](https://user-images.githubusercontent.com/55203598/185607905-4c41b68f-8447-4a68-8e92-91c908c05231.png)
Are there needed some changes in styles there too or not at this moment?

**Comment by lwtchu** [comment]
@ajluk okay we might need to do some work on the webview files to at least make the figure and title bold, but we can do that later

**Comment by ajluk** [comment]
@lwtchu Should I open a separate card for webview?

**Comment by lwtchu** [comment]
@ajluk i just did :)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-02 11-52-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/328df71c-ea9f-49b6-8aac-aa3d48c57530)

![Screenshot from 2022-09-02 11-52-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/03279bc2-a019-4a80-84de-d1c6a57f2655)

![Screenshot from 2022-09-02 11-55-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1db182c5-cb4f-4cd1-9c88-3f768f134f82)

**Comment by ajluk** [comment]
Hi @lwtchu I just wanted to confirm with you if the mechanism figures look better at `max-width` set to `4.5in` and it is acceptable: 
![image](https://user-images.githubusercontent.com/55203598/188976631-4bef27f8-0a87-4757-88bb-32a49e5d5926.png)
![image](https://user-images.githubusercontent.com/55203598/188976678-e76322b5-3bae-4dc0-beaf-00054f31fb04.png)
![image](https://user-images.githubusercontent.com/55203598/188976722-59d9c940-958a-4450-ac69-401094cd8e93.png)
I couldn't decrease the width of the figures in other way in pdf.

**Comment by lwtchu** [comment]
placing notes here from our DM: will need someone to pick up as Anna will be on leave. 

i audited the book mechanism art and found some that are wider than 4.5 in. is it possible to have the div width be set by the image container? ([not sure if this would help](https://stackoverflow.com/questions/15866209/div-width-depending-on-image-width-that-is-inside-it)) but also might need to put a class on the div so it doesn't affect other figures 🤔   

let me know if it might balloon into something else. 🤔 and we can discuss scope.

**Comment by wilkus27** [comment]
@lwtchu When we don't set width property then ,by default, width of the figure container is equal to width of the biggest content inside. Because in our case all captions are long, container spread to 100% width:

![image](https://user-images.githubusercontent.com/40228854/189375323-53a051f5-d958-46ca-97f7-43f40da3026c.png)

I can align image to the center, and maybe add some background :thinking: What do you think?

Here is how it looks when image is bigger then caption (I removed text from it):

![image](https://user-images.githubusercontent.com/40228854/189375631-7b82cde2-6a84-4286-8b32-5475e1dc4877.png)

**Comment by lwtchu** [comment]
@wilkus27 so the caption can be shorter than the image, just not longer than the image 🤔 and there's no way for the caption to be the max width of the image.... I'll have to think about the design give me a day or so

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-09-14 14-08-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/91ad8fc3-01fa-4b13-9097-f5fb1bc11f33)
