### ISSUE TITLE
baked styles refactor - lists in carnival

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#4829]
DONE:
- [x] Carnival - was done with different convention. Style lists like in other themes.
- [x]  Carnival - titled lists - create separate shape for them. Make sure if it doesn't appear in other themes.
- [x]  Carnival - complete shapes with missing components

**Comment by ajluk** [comment]
Information for testing purposes: @Stackblocks based on Larissa's comment (https://github.com/openstax/cnx-recipes/issues/4694#issuecomment-1216853777) please test lists on regular pages, exercises, composite pages (e.g. Summary), appendixes, answer key, notes in _College Physics,_ _A&P,_ _Microbiology_ and _Chemistry._ Within this issue please also pay attention to the notes outer container paddings (there were changes adding top and bottom paddings in note containers where it was needed after bottom margins has been removed from lists for standardization).

**Comment by Stackblocks** [comment]
1. Spacing between back-to-back figures and between a figure and a list item doesn't match where it shows up in eoc problems, presumably due to the altered top/bottom padding, but that's a solvable problem. 

![CleanShot 2022-08-22 at 21 43 22](https://user-images.githubusercontent.com/12678235/186058256-a1104c5d-6e0a-4de0-ab39-b8ce22435f4c.png) 
_(College Physics)_

2. Equation-heavy sections of the Chem 2e answer key get a little messy, but i'm not sure that's related to list spacing.

![CleanShot 2022-08-22 at 22 09 03](https://user-images.githubusercontent.com/12678235/186061108-5f0483a6-090d-4476-bfd6-cb7d517f93b7.png)

![CleanShot 2022-08-22 at 22 08 11](https://user-images.githubusercontent.com/12678235/186061129-479a1f0a-9a4f-4794-a6a8-cd688ae3dc68.png)

The lists themselves look good across the various content types in the theme, so this can move forward and we can address any tidying up as separate issues.

**Comment by ajluk** [comment]
@Stackblocks In the first point the space between figures inside one exercise differs from space between the figure and the next exercise, because there is only margin added under the exercise (`data-type="exerecise"`) itself. Under the `os-figure` we are currently not adding a bottom margin. I guess we need to open  a separate issue for bolded exquations?

**Comment by Stackblocks** [comment]
@ajluk Thanks for clearing up the figure spacing issue for me, and i'll make a new issue for the equations if it isn't a function of the updated spacing.

**Comment by ajluk** [comment]
@Stackblocks  I have decided to check chmistry-2e also more carefully, because your question made me curious if the spacing changes we made so far can be related to it and I fetched the newest content today, baked it on `q.q` branch on ce-styles and `main` branch in cookbook and the equations look ok now :thinking: Could you check again on your side? I have updated the pipeline recently as well.

**Comment by Stackblocks** [comment]
It looks correct in my HTML output but it's still big in my PDF, so it's probably a local issue. Thanks again for double checking!
