### ISSUE TITLE
World History - Feature Box and Figure Captions not break across pages?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4884]
# Context
Is it possible to adjust spec to prevent Feature Boxes from breaking across pages?
Is it possible to adjust spec to prevent Figure Captions from breaking across pages?

# New specifications or link to documentation cards
**We would like to avoid this:**
![image](https://user-images.githubusercontent.com/89537088/193640424-bb424b2d-f33a-4911-8812-82e0a8921410.png)

**and we would like to avoid this:**
![image](https://user-images.githubusercontent.com/89537088/193641443-b6fa3d65-406a-40b2-9c56-57c343a82f03.png)

## Impact 
Impacts entire book

# Acceptance Criteria
Feature Boxes and Figure Captions do not break across pages

## Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history
- **ref/branch:**
- **chapter/section:** all chapters / feature boxes and figure captions
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax this is by design and if we disallow page breaks across features/figure captions, it could result in significant page breaks and a lot of white space on pages. if is a substantial hindrance to understanding a feature, we could explore options not to have them break across pages but for now i would recommend leaving as is.
