### ISSUE TITLE
[webview/cookbook] college physics 2e - equation numbering falling to next line

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4925]
# Brief Description of Scenario
![Screen Shot 2022-11-29 at 10 05 58 AM](https://user-images.githubusercontent.com/11299125/204581175-cb15c35e-24ee-4d55-91a7-2dff81957e79.png)

Context thread: https://openstax.slack.com/archives/CH5514N57/p1669730931490649 
Sandbox release from 11/29 disco/rex staging environment: https://release-2038.sandbox.openstax.org/books/college-physics-2e/pages/3-4-projectile-motion 

# Pattern of Occurrence 
All equation numbers.

# Acceptance Criteria
- if the divs are needed, please adjust styling in webstyles
- if the divs are not needed, please remove the divs
- if there is a secret third option, please update here
  
# Sample Mark-Up
![image](https://user-images.githubusercontent.com/11299125/204581211-ceb65644-4844-4e60-a202-4f86e851d19f.png)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-physics-bundle
- **collection slug:** college-physics-2e
- **ref/branch:** main
- **chapter/section:** 3.4 (though they're everywhere) 
- **surrounding text:**  REVIEW OF KINEMATIC EQUATIONS

**Comment by wilkus27** [comment]
Additional `div`s were added to solve this: https://github.com/openstax/cnx-recipes/issues/4686.

Current problem is caused by changing way of displaying math elements. Here is a markup from rex preview:

![image](https://user-images.githubusercontent.com/40228854/206139587-185620f1-8e2d-4be5-be43-52b97884976d.png)

There is a new `div` with class `MathJax_Display` and its properties are breaking numbered equations. We are using `display: table` to adjust its elements. We should change `block` to `table-cell` to fix that.

But, when I inject styles from `ce-styles` repo, this is what I get:

![image](https://user-images.githubusercontent.com/40228854/206141093-c5b5ab23-2635-43b5-ae75-260a6ff2540e.png)

It looks completely different. Here is a markup:

![image](https://user-images.githubusercontent.com/40228854/206142101-338c5f20-10f5-4e65-8bdb-5291bc58668c.png)

There is a new `math` tag. To fix styles we can just add these properties:

![image](https://user-images.githubusercontent.com/40228854/206142967-93280feb-fad8-414a-860f-a6910ee9fda6.png)

### Questions

- Which markup is correct?
- On which step of generating rex preview these new tags are added? They are not created by recipe.
- Do we need a fix both in `ce-styles` repo and `rex-web`?

**Comment by LostMojo** [comment]
Huh-- in the first screenshot, do you know where the display: block!important came from?

I'm not very familiar with the inner workings of rex yet, but I assume they have a version of mathify that gets run after baking, and that would add these tags.

I would assume a fix is needed in both, as both look pretty strange.

**Comment by kswanson33** [comment]
> Which markup is correct?

It seems like two different styles bugs have been introduced by the addition of the `<div>` tag. The version styled by baked styles for web is the only style within scope for our team (unless it can be fixed through recipes, which would impact both. However, that ... probably isn't a great approach if it would mean undoing a previous fix).

> On which step of generating rex preview these new tags are added? They are not created by recipe.

I'm confused by this -- I thought the new `<div>` tag was added by the recipe to solve #4686? Which tags are not added by the recipe?

[Here](https://github.com/openstax/enki/blob/main/step-config.json#L312) are the steps used in generating the book for web. Not sure what step could add a tag. To investigate further, I'd recommend looking at the source code for the post-baking web steps on `enki`, or asking ce-tech.

> Do we need to make a fix both in ce-styles repo and rex-web (or another one)?

Our team is only officially maintaining the `ce-styles` repo. That said, if you see an easy way to make the fix in rex-web too, I'm sure they wouldn't mind.

**Comment by philschatz** [comment]
I'm still catching up on the issue but this may help de-mystify some of the injected styling/markup:

REX runs MathJax in the browser to convert `<math>` tags into HTML because it adds dynamic accessibility improvements (mathify uses it too, but in NodeJS).

> Styles are injected to <head> tag, so I'm not sure where it is done (in which repo).

MathJax adds the `<style>` tag to the top of REX when it starts up.

> There was added additional wrapper to [data-type="equation"]

It might be helpful to add an attribute or comment to the empty `<div>` element for future folks to reduce confusion and better understand where it comes from

**Comment by kswanson33** [comment]
@wilkus27 after discussing with disco (rex) on a call, we got the feedback that adding a `<div>` is not preferred (shallow element nesting is better for many things, including search engine optimization)

i've investigated, and it seems like the MathJax step that phil mentioned above will convert `<math>` tags into `<div>`s anyway, which will allow `overflow: auto` to create the scroll box, no need to add an additional div wrapper.

unfortunately, the final form of MathJax HTML is only visible in production, not in `rex-preview`. i'm going to work on getting us some better previewing.

in the meantime: removing/rolling back the div wrapper in equations is preferred.

to test: i grabbed the MathJax html from production and "hacked" it into the rex-preview html

**Comment by wilkus27** [comment]
Thank you for all informations! :relaxed: It cleared it up a lot. I will make a fix in cookbook and styles in that case.

**Comment by MartaSztuka** [comment]
#### PASSED
##### COLLEGE PHYSICS
![Screenshot from 2022-12-13 14-54-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dcb1fbad-3f45-49ec-8aa0-30eefc465f85)
![Screenshot from 2022-12-13 14-54-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2e484c81-711f-4d22-be16-e18e8bc9d22b)

##### CALCULUS 1
![Screenshot from 2022-12-13 15-01-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/71fb8a41-a6c6-4cc4-ae13-db3db256d7c7)
![Screenshot from 2022-12-13 15-01-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a360ab0c-15fc-452c-a321-30012cce00b7)

##### FIZYKA 1
![Screenshot from 2022-12-13 15-07-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4a728475-089d-43e6-afc7-fcfd18033bcb)
![Screenshot from 2022-12-13 15-07-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a2027d7-2c1c-4a47-b0c0-05823d7a3dda)

##### STATISTICS
![Screenshot from 2022-12-13 15-15-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a613e43e-afc0-4fc5-b1de-40ebb656e6ae)
![Screenshot from 2022-12-13 15-14-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e195431-8057-4097-b071-a10e6a062151)

##### PRINCIPLE OF MICROECONOMICS
![Screenshot from 2022-12-13 15-56-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e3a88419-028e-4e9b-8f3a-78d5dc6ac232)
![Screenshot from 2022-12-13 15-57-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e91d0ff6-73dd-4607-9155-d28420bdf13f)

##### MARKETING
![Screenshot from 2022-12-13 16-32-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bb469191-f2cc-421d-bb1e-55d832b39f0a)![Screenshot from 2022-12-13 16-32-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a05371a4-2e50-4617-9a7d-4b59a15a81ef)
