### ISSUE TITLE
Organic Chemistry - Single Italicized Greek character as MathML or emphasis tag?

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4959]
# Context
Is it necessary to tag individual italicized Greek characters as MathML or is `<emphasis>` tag OK?
The screenshot is from OSX tagging in Ch01. module m00013, line 48
# New specifications or link to documentation cards
![image](https://user-images.githubusercontent.com/89537088/213537337-a1b82e5d-5dc9-4432-ad79-b5358543bfde.png)

## Impact 

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Chapter 01. module m00013, line 48
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax Emphasis should be fine. MathML is recommended for a lot of the math symbols or if it's part of an equation so that the screen reader will be able to see the context with the rest of the equation so that it reads the right thing. As a singular symbol, it should be okay if it's set in regular CNXML with emphasis tags.
