### ISSUE TITLE
Organic Chemistry - Can't create double long arrow character in equations

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#4964]
# Context
Some equations include double long arrows.
We can't create double long arrows in equations
We can't find an HTML entity for double long arrows and we think that one does NOT exist.
We have tried to use HTML entity x21C4 and `<m:mo stretchy="true">` but that does not work.
Some research revealed this (but for mathjax): https://github.com/mathjax/MathJax/issues/2712

![image](https://user-images.githubusercontent.com/89537088/213897098-2c15674c-2203-4e28-8fd5-4ab8705862f8.png)

## Impact 

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<equation class="unnumbered" id="eq-00001"><label/>
  <m:math display="block">
 <m:mrow>
  <m:mtext>HA</m:mtext><m:mo>+</m:mo><m:msub>
   <m:mtext>H</m:mtext>
   <m:mn>2</m:mn>
  </m:msub>
  <m:mtext>O</m:mtext><m:munder>
   <m:mo stretchy="true">&#x21C4;</m:mo>
   <m:mrow>
    <m:msub>
     <m:mi>K</m:mi>
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:**  Chapter 2 / Section 2.8 / m00025 / Line 18
- **surrounding text:**

**Comment by ww-openstax** [comment]
In addition to yellow color we need purple color.

![image](https://user-images.githubusercontent.com/89537088/213950940-b2059aa7-bb00-4766-b64a-da8849472367.png)

**Comment by caylaeagon** [comment]
There are two possible options for addressing this problem.

Option 1: Use the equilibrium symbol ⇌ (`&#8652;`) if it's an equivalent to the double arrows because it works with the stretchy attribute.
![Screen Shot 2023-01-24 at 10 21 28 AM](https://user-images.githubusercontent.com/99201272/214364881-8f5caa72-906e-4de9-8316-36a08b371057.png)
`<m:mo stretchy="true" maxsize="1em">&#8652;</m:mo>`
`<m:mo stretchy="true" maxsize=".75em">&#8652;</m:mo>`
`<m:mo stretchy="true" maxsize=".05em">&#8652;</m:mo>`

Option 2: Use two arrows (`&#x2190;` and `&#x2192;`) with the element <m:mpadded height="-.1em">. The arrows seem too long, but I couldn't make them any shorter with different heights and widths.
![Screen Shot 2023-01-24 at 10 21 39 AM](https://user-images.githubusercontent.com/99201272/214365898-0af1c1da-ab11-4699-9e39-3b863616fcb2.png)
`<m:mover><m:mo>&#x2190;</m:mo><m:mpadded height="-.1em"><m:mo>&#x2192;</m:mo></m:mpadded></m:mover>`

**Comment by ww-openstax** [comment]
For option 2: We also achieved that solution as a test -- see module m00014 line line 187. The issue with this solution is that a screen reader won't interpret those arrows correctly.

**Comment by openstaxalina** [comment]
discussed with Tom (SME) - the equilibrium symbol is fine to use. The equilibrium symbol with "fish hooks" or single-sided arrows is interchangeable with the full double arrows and they can be used interchangeably even within the same book. (This is important because the art uses the full double arrows).

Markup should use the equilibrium symbol - @lwtchu to add to tagging legend as-needed

**Comment by lwtchu** [comment]
@ww-openstax I added the instructions in row 57 of the tagging legend. You can also read [this section of the MathML documentation](https://www.w3.org/TR/REC-MathML/chap3_2.html#sec3.2.4) for more information if you are interested!
