### ISSUE TITLE
nursing-external - vertically-tight, text heavy, tight spacing tables with header row (nutrition and pharmacology only)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5007]
![Screen Shot 2023-02-07 at 3 39 05 PM](https://user-images.githubusercontent.com/11299125/217372129-53bb5fb6-793a-494d-9f8c-3052429ed071.png)

We've done something similar in Finance #4294 
`class="vertically-tight"`
Set padding to 0.16rem which is equivalent to 2px
Styling should still follow generic tables: 
Documentation #1080
Table bottom line: B2: `#0074BC` 

This will also utilize `<row class="header-row">` please make sure font is set bold like the header styling

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `nursing-external` & content from `hysterical.herbology`

Limited extended testing due to timeframe, but didn't see any regressions in targeted areas and didn't see any cause for regression outside of targeted area.
#### Nutrition
![CleanShot 2023-04-20 at 16.30.31.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/b8562b9b-95dc-4729-97b3-458ab037ac0a)
#### Pharmacology
![CleanShot 2023-04-20 at 16.41.54.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e664e45e-f10a-4f8e-9ea8-cd6525a71ae4)
