### ISSUE TITLE
college success - darken table borders

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5020]
# Brief Description of Scenario
Table borders are very light and hard to see on light backgrounds

![Screenshot 2023-02-14 at 10.26.25 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/3793cbc9-aac2-415b-8fc1-a62d1727724f)
![Screenshot 2023-02-14 at 10.25.37 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/5633d29b-1978-478e-8ecc-15ca30e1745f)

# Pattern of Occurrence 
all tables

# Acceptance Criteria
- [ ] we did something similar in #4857 - please change line color to Grey2: `#757474` - please go with transparent background within notes 
 
# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-college-success-bundle
- **collection slug:** college-success
- **ref/branch:** main
- **chapter/section:** various
- **surrounding text:** table

**Comment by wilkus27** [comment]
@lwtchu Similarly as for math books, this change has an impact on all books from Cardboard theme. Which books do we want to test?

**Comment by lwtchu** [comment]
@wilkus27 Accounting vol 1, business ethics, finance

**Comment by Stackblocks** [comment]
I'm not sure if this is by design or not, but the header row not being bordered in the table looks off with the new colors. @lwtchu does this look OK or should we open up a follow-up card?

### College Physics

![CleanShot 2023-02-21 at 14.17.22.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/49fd4316-2472-4270-95c5-f63a1fcfe26d)
---
![CleanShot 2023-02-21 at 13.56.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/336e46d7-96c8-4055-a8af-82793000b97d)
---
![CleanShot 2023-02-21 at 13.56.58.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bd7a3ef6-0d65-4a26-bb60-26077c195148)
---
Also changes the border surrounding the Estimated Completion Time, since that is also a table.

![CleanShot 2023-02-21 at 14.00.34.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/aa26cc04-122e-4806-9be5-a9126f929c28)

### Business Ethics
![CleanShot 2023-02-21 at 14.41.51.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/cfed3cc5-d233-4f9b-8bb2-c29984541c7a)

### Finance
![CleanShot 2023-02-21 at 14.53.55.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/47f2fdc7-dbde-4bbb-9b31-5abd98ddbdef)
---
![CleanShot 2023-02-21 at 14.56.08.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a755da0b-dd25-4a21-a7f3-ef8a45e259aa)
---
![CleanShot 2023-02-21 at 14.56.32.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6ee566e9-6660-42a2-97c8-d7fc09611e12)

### Financial Accounting
![CleanShot 2023-02-21 at 16.00.43.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/3ee796b3-20a6-4e92-920c-4680d037a6b3)
---
![CleanShot 2023-02-21 at 16.05.18.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c25d362a-c4c4-4842-8f22-df48b9fbba19)
