### ISSUE TITLE
Organic Chemistry - fix errors from Chemistry Matters section

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5024]
When there is no Chemistry Matters section in chapter some errors appear while baking:

```
-----+ /workspace/enki/cookbook/lib/recipes/organic-chemistry/bake -----
 36| )
 37|
 38| UseSectionTitle.v1(
 39| chapter: chapter,
 40| eoc_selector: '.os-chemistry-matters-container',
 Encountered on line 8505 in the input document on element:
 <div xmlns="http://www.w3.org/1999/xhtml" data-type="page" id="page_8583e724-fe5a-4162-8a9d-82a9a94e1af1">...</div>
```

**Comment by lwtchu** [comment]
Please test using this branch: https://github.com/openstax/osbooks-organic-chemistry/tree/test-missing-cm where one Chemistry Matters has been removed from a chapter.

**Comment by Stackblocks** [comment]
Baked without error on the test branch! (Included the input command from the history at the bottom since the scrollback to a point that referenced the branch was too far)

![CleanShot 2023-02-15 at 15.36.00@2x.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0680b283-894d-4f05-a10c-78c3b5ec5ede)
