### ISSUE TITLE
Organic Chemistry - blue-green text color needed

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5031]
# Context
A blue-green text color is needed. Please, see screenshot.

![image](https://user-images.githubusercontent.com/89537088/221593968-43ec9b76-f41a-421d-afd8-df814be419a1.png)

# Acceptance Criteria

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:**  Chapter 2 / Section 1
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax would it be ok to use the `span class= cyan-text` tagging since it's the same color as the text described in the paragraph? - B5: `#0078a3`. The other option would be to use 00819A, but it is a little too close to the original color used.

![Screenshot 2023-02-28 at 1 45 51 PM](https://user-images.githubusercontent.com/11299125/221963085-87b66f30-5e17-4acc-8274-c0bd3c8fca3c.png)
