### ISSUE TITLE
nursing-internal - figure and table captions

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5063]
documentation: #1081

**Comment by MartaSztuka** [comment]
##### There is inconsistency in line height for figure caption and table caption, is that intentional?
![Screenshot from 2023-04-03 11-53-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5940648-6a43-474d-aad4-f6435fa22c23)
![Screenshot from 2023-04-03 11-54-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9af48b55-1aa5-421e-93c7-a1aed9862efb)
![Screenshot from 2023-04-03 11-58-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ef19743b-b00d-4b3b-a81b-5d4e48b399af)

**Comment by wilkus27** [comment]
@lwtchu line height for figures was decreased within https://github.com/openstax/cnx-recipes/issues/4569. I will apply this for tables as well.

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-04-13 16-16-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9390347d-5478-4dde-8512-67c2d5a70a56)
![Screenshot from 2023-04-13 16-20-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/47956770-4af2-48ea-96ce-2e26f8d0cdcb)

![Screenshot from 2023-04-13 16-19-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/750f4c3b-b66a-4b32-b1df-d20065ece7ac)
