### ISSUE TITLE
Organic Chemistry ToC—Bad Line Break

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5154]
# Brief Description of Scenario

The ToC for O-Chem has an unfortunate line break on a long chapter title where the page number falls onto the next line by itself.

Is this worth fixing? We can manually fix for sample PDF publication on June 26, but want to consider for full book publication in September.
![Screenshot 2023-06-08 at 1.20.46 PM.png](https://images.zenhubusercontent.com/620146abc041eb48aa2fd785/706a9234-31ba-4680-b031-ad229fb20aac)

Here's an example of how it breaks with an even longer chapter title:
![Screenshot 2023-06-08 at 1.46.00 PM.png](https://images.zenhubusercontent.com/620146abc041eb48aa2fd785/3f8c8e34-dd34-4ba7-b7f2-5a00b1f85342)
# Pattern of Occurrence 

# Acceptance Criteria
- [ ] don't spend more than a day on this might not be fixable
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-organic-chemistry
- **collection slug:** organic-chemistry
- **ref/branch:**
- **chapter/section:** Table of Contents
- **surrounding text:**

**Comment by jbwilson8** [comment]
Update: A viable solution was not obtained. The following approach was taken:

**- Decrease the width of the ToC container so that the titles wrap in a way that prevents orphans.**

This fixed the lines that were previously broken (i.e. Chapter 4 & 11 titles; see screenshots below). 

<img width="483" alt="Screenshot 2023-08-14 at 9 07 10 AM" src="https://github.com/openstax/cnx-recipes/assets/26155528/18c9ab57-bdba-407e-82d6-6ff94b476362">

<img width="602" alt="Screenshot 2023-08-14 at 9 06 45 AM" src="https://github.com/openstax/cnx-recipes/assets/26155528/39661a2e-4077-4260-b050-e24d2af990a4">

However, other lines in the ToC began to break/wrap in weird places creating more orphans. Ideally, we could handle this programmatically by having knowledge of the length of a particular title. Then if the title is beyond a certain length we could simply wrap the title and the chapter number. At the time of this update this isn't easily achieved with princeXML/styles.
