### ISSUE TITLE
Organic Chemistry: Do Not Allow "Problem" and "#-#" to Break Across Pages

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#5161]
# Brief Description of Scenario
Since "Problem" and "#-#" (e.g. Problem 3-30) fall on separate lines, they are sometimes breaking across pages, resulting in a display that could confuse users:

![Screenshot 2023-06-13 at 10 13 38 AM](https://github.com/openstax/cnx-recipes/assets/7863733/08a16d03-f67c-4e11-b986-2e7cdd88af62)
![Screenshot 2023-06-13 at 10 13 09 AM](https://github.com/openstax/cnx-recipes/assets/7863733/a8666fb8-826c-4e62-8548-5ffa5b9dc50f)

# Pattern of Occurrence 
This happens at least twice -- likely more; I did not do a page-by-page -- in the first twelve chapters, due to the way content falls on the page.

Proposed approach -- could we ONLY make sure `<span class="os-label">` and `<span class="os-number"` not be broken within exercises. I do not want to apply this to the entire exercise

# Acceptance Criteria
- [ ] "Problem" text does not break from the number on the next line
- [ ] exercises can still break past the first 2 lines (word "Problem" and number)

# Location(s)
- **osbooks repo:*organic-chemistry* 
- **collection slug:*organic-chemistry*
- **ref/branch:*main*
- **chapter/section:*Chapter 3 EOC, Section 8.5* 
- **surrounding text:*See screenshots above*

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2023-06-21 17-17-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2bf4e4f4-7e8a-4051-bbd4-b2036efb7ec7)

![Screenshot from 2023-06-21 17-16-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/162ed805-bf45-41a5-8aa1-564e35225d8e)

**Comment by Stackblocks** [comment]
Still happening intermittently despite the fix being implemented; unclear if the fix isn't working or if there is something about the double-line problem numbers that doesn't want to play nice since when the fix was implemented it appeared to have stopped for a time but with new content providing new breakpoints it is happening again.

![CleanShot 2023-07-18 at 13.55.19.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a4245111-dec7-45e3-a90d-69d348af7ef5)
---
![CleanShot 2023-07-18 at 13.56.30.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/5b18eb83-a387-4063-9c16-8ee1b82afcf1)
---
![CleanShot 2023-07-18 at 13.56.50.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/63276cc9-52ac-4890-bbb6-fdb50ce5fe0e)
---
![CleanShot 2023-07-18 at 13.58.49.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/35329655-cd96-43cf-adaf-e12c40970afa)
