### ISSUE TITLE
Introduction Statistics - Unwanted page split issue in Homework Section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5191]
We have received the below corrections. We coded as per the tagging legend. But unwanted page split issue appeared in output PDF. Please check and resolve this issue.

**PDF:**
![homework_PDF](https://github.com/openstax/cnx-recipes/assets/86622862/771e68ba-d743-4f63-b1a3-a61a2966bc4c)

**CNXML:**
![homework_CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/395ea9b7-40bc-43a7-a30a-4057b8b55131)

# Acceptance Criteria
- [ ] remove the page break rule for exercises (injected and non injected)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-statistics-2e
- **ref/branch:** https://openstax-osbooksintrodu-f9nbjo819om.ws-us102.gitpod.io/
- **chapter/section:** Chapter 2/Homework Section
- **surrounding text:** Suppose that three book publishers were interested in the number of fiction paperbacks adult consumers purchase per month.

**Comment by wilkus27** [comment]
@lwtchu It acts like that because we are avoiding page breaks within exercises

![image](https://github.com/openstax/cnx-recipes/assets/40228854/117769fa-4a98-4bdf-b0dc-6c3f9911bd6c)

This change was done 3 years ago and it's applied for a whole library. I can remove it but it might cause many regressions and we might not be able to catch every each of them. 

Maybe we could add some class for long exercises, so then I can exclude them from this styles property :thinking:

**Comment by lwtchu** [comment]
@wilkus27 let's make the change to remove the `avoid` for all books. injected exercises operate in that way also. I'm scheduling this into the next sprint though.

**Comment by Stackblocks** [comment]
- Displays OK with updated code from `quiet.quinology` & content from `main`
