### ISSUE TITLE
Add a selector at the beginning of all web CSS so to scope the styles inside REX

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-recipes#5254]
# Brief Description of Scenario

REX would like to load the CSS using a `<link href="../path/to/CSS">` so that relative links to things like SVG images and fonts will resolve. But they need to be sure that the CSS in the file is scoped to just the content part of REX.

To ensure that the baked styles do not "leak" into REX, DISCO fetches the CSS file, edits it by adding a prefix selector, and then injects it into the webpage in a `<style>` tag (which breaks any relative paths that might be in the CSS).

Add a selector at the beginning of all web CSS so that the styles do not leak into REX when the CSS file is loaded.

Phil doesn't remember what the selector that identifies the element is but can ask Disco.

# Pattern of Occurrence 
Yes, all baked & generic styles need this scope selector at the beginning of all CSS statements.

# Acceptance Criteria

All web CSS files are scoped to a specific element

**Comment by TomWoodward** [comment]
i thought @philschatz intended to add a new selector to the html output (vs using something in rex or something in the content already), but i remember also discussing how it'd be nice for the css to apply to content excerpts being shown like highlights, so i'm not totally sure.

if you decide to use the rex selector it would be `[data-dynamic-style="true"]`

**Comment by philschatz** [comment]
I think that `[data-dynamic-style="true"]` sounds good! Baking just needs to add that attribute onto a root-ish element of each page so the CSS files still work in the various output formats (I'm happy to pair/help to find them all)

**Comment by TomWoodward** [comment]
if the plan is to use a selector in rex (like `[data-dynamic-style="true"]`) then it shouldn't be added to the content right? because we don't want it to come through the content into rex, rex already has it. 

for the record, when rex pulls the content from archive it extracts the document body, runs the dom tranformation on that, and then returns the innerHTML, the first child of the body is the page element, so that is what rex embeds

maybe it would be better to add a new attribute to the page elements in the content, that'll come through to rex normally, and then rex will just make sure to add that selector as a wrapper to any content excerpts?

**Comment by philschatz** [comment]
Let's go for `[data-book-content="true"]` in the selector and enki and/or cookbook will add the `data-book-content` attribute onto both the `<body>` tag for the PDF output as well as the `<body>` tag for each disassembled page. 

That way all of the outputs (PDF/web/EPUB/docx) should all have the data-book-content attribute (esp since REX will inject the contents of `<body>` into an element with the attribute

@LostMojo Do you forsee any issues with that option?

**Comment by LostMojo** [comment]
I think that should work just fine!
