### ISSUE TITLE
webview - google search console error: background and foreground colors do not have a sufficient contrast ratio

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5262]
# Brief Description of Scenario
Originally reported #2478 
The `Accessibility` report in Google search console shows the error: Background and foreground colors do not have a sufficient contrast ratio.
https://pagespeed.web.dev/analysis/https-openstax-org-books-physics-pages-8-1-linear-momentum-force-and-impulse/46b4pp1gnt?utm_source=search_console&form_factor=desktop&hl=en
![Screenshot 2023-07-05 at 2.52.02 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/514b005c-eca2-429b-bded-3081b3747dea)

For reference, these are the link colors in osweb:
```
    link-hover: #005481,
    link: #026aa1,
```

# Pattern of Occurrence 
All links in shaded bg box

# Acceptance Criteria
- colors found here https://github.com/openstax/ce-styles/blob/main/styles/design-settings/webview/_colors.scss are not accessible 
- please update the links to these colors as they pass AA
```
    link-hover: #005481,
    link: #026aa1,
```
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** 
- **collection slug:**
- **ref/branch:**
- **chapter/section:** 
- **surrounding text:**

**Comment by openstaxalina** [comment]
Tested at [this UR](https://openstax.org/books/world-history-volume-1/pages/8-3-the-age-of-empires-in-the-americas)L since Physics (in the URL above) isn't in baked styles yet.

While there are some errors, none of the ones about contrast refer to a figure link or content in a feature box. Both those items got flagged when I scanned a Physics URL. So I am confirming this particular issue is resolved when books adopt web baked styles.

![Screenshot 2023-12-11 at 3 01 21 PM](https://github.com/openstax/cnx-recipes/assets/7863733/68d60d19-78cf-49a1-b5fd-6bac429d6198)
