### ISSUE TITLE
lifespan development - end of book references (appendix)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5331]
Documentation: #3244
This is set as an appendix and will function slightly different than the documentation above. Let me know if I need to make a new documentation but wondering if we can set a reference-like style in Appendices

**Comment by wilkus27** [comment]
@lwtchu To style it like references (with indentations) we need some additional class, that will differ this appendix from other ones. And I think that it shouldn't be `reference` or `references` because we are using these for other things and I'm afraid that it might causes conflicts on webview. It's better to add something new, specific for references from appendix. But appendix still have to have `appendix` class. We need additional one.

**Comment by lwtchu** [comment]
@wilkus27 should we treat it like the glossary appendix where the document has the appendix class but the section that contains the information has a specific reference class?

**Comment by wilkus27** [comment]
@lwtchu That might work too :+1: In appendix glossary we have a class `column-container`, so here maybe we can use `indent-container` or if it's only reference specific - `reference-container`. What do you think?

**Comment by lwtchu** [comment]
@wilkus27 added `<section class="indent-container">`

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-11-29 16-45-27](https://github.com/openstax/cnx-recipes/assets/47241114/10e2d299-ba36-4c9f-a58e-79bd91874017)
![Zrzut ekranu z 2023-11-29 16-47-02](https://github.com/openstax/cnx-recipes/assets/47241114/18ca1caf-05a5-4cc5-92e3-75812c6d5b97)
