### ISSUE TITLE
data science - highlight.js application on python code

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5348]
Originally done here #3750
We should be able to reuse what we did in Computer Science. The same colors/process/etc should apply. Code snippets are tagged with the python class

**Comment by wilkus27** [comment]
@caylaeagon In the content there are classes like `green-code`, `blue-code` etc. but there is no class `python`. Would you mind to added it?

**Comment by caylaeagon** [comment]
@wilkus27 I added `class="python" lang="python"` to all the `<code>` elements that didn't already have `class="python inline-code"`. Let me know if you need any other changes.

**Comment by wilkus27** [comment]
### Important note

highlight.js previously was enabled on `step-mathify`, which doesn't exist anymore. Because of that, all logic had to be moved to `step-prebake` (https://github.com/openstax/enki/pull/325). Here is a discussion: https://katalysteducation.slack.com/archives/C0LA54Q5C/p1702380376240609

**Comment by wilkus27** [comment]
@lwtchu @caylaeagon I checked how it works for books with highlighted code, that is python, computer science and data science. A lot of content changes are needed. 

1. block and inline code have to have both attributes `class="language"` and `data-lang="language"`. Otherwise highlight.js is not enabled. Previously, we had a function in cookbook that added data-lang attribute if class existed, but because highlight.js is enabled now on `step-prebake` (so before baking) it doesn't work. `data-lang` has to be added in the content.
2. all spans with classes like `red-code`, `blue-code` etc. have to be removed, because if there are other tags within code, highlight.js is creating new block of code without them, so content in PDF is doubled

![image](https://github.com/openstax/cnx-recipes/assets/40228854/a766c7e5-3e87-4e1d-8629-4cc6ee95eff5)

**Comment by caylaeagon** [comment]
So to clarify, all `<code>` elements need the attribute `data-lang="python"` (instead of `lang="python"`)? Making all code elements look like `<code class="python" data-lang="python">`? And all `<span>` elements with color coding need to be deleted?

**Comment by wilkus27** [comment]
Hmm :thinking: Not sure how cnxml should look like. We are working on xhtml, where block code is in `<pre>` tag and inline code in `<code>` tag. `data-lang` it is also an attribute from xhtml. Probably `lang` is a proper attribute in cnxml, that is trasform later into `data-lang`. @lwtchu could you confirm? Not sure about tags. Are `pre` and `code` both just `code` in cnxml?

**Comment by lwtchu** [comment]
@wilkus27 @caylaeagon The pre and code tags are auto generated by the XSLT based on how the code snippet in CNXML is nested. Please remove the `<span>` elements! The `<code class="python" data-lang="python">` should prompt the XSLT to transform it to either a code or pre tag with the classes/data-lang attributes and highlight-js will add the remaining classes.

**Comment by caylaeagon** [comment]
Ok @wilkus27, I've removed all the `<span>` elements. The attribute `data-lang="python"` doesn't validate in POET, so I just used `lang="python"`. Let me know if there are any other changes needed.

**Comment by MartaSztuka** [comment]
#### PASSED
![Zrzut ekranu z 2023-12-14 10-07-49](https://github.com/openstax/cnx-recipes/assets/47241114/197718ae-2d4a-47b6-a7e0-8973b90ce0dd)
