### ISSUE TITLE
[LARISSA re-evaluate, close? See comments] Nursing Internal -- Add more space between feature box and module title

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5386]
# Brief Description of Scenario
Add more space between feature box and module title
In PDF only
Applies to all titles in Nursing Bundle

![image](https://github.com/openstax/cnx-recipes/assets/89537088/620413f9-73a6-4fd1-9e8e-eaf29f3b7839)

# Pattern of Occurrence 

# Acceptance Criteria
- we've done something similar in the past - this mostly relates to the last non paragraph object in a module - could there be more padding to separate feature boxes and a new module? 
  
# Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

# Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** psychiatric-mental-health
- **ref/branch:**
- **chapter/section:** Chapter 4 / Section 3
- **surrounding text:**

**Comment by openstaxalina** [comment]
@wilkus27 thank you for the analysis. What I understand is that the spacing after the last element of the section is always 0.7rem. It may _look_ like less because of the feature box line, but in fact the spacing is the same.

I do **not** think we should change the spacing for all ends of sections. I'm going to move this into the c.c. sprint and re-assign to Larissa to provide the final decision.

**Comment by lwtchu** [comment]
Will put won't fix - we can reevaluate if we embark on a major refactor in the future
