### ISSUE TITLE
make web recipe mock books to be similar to web, then put everything back

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5391]
Testing issue for part of #5304

for QA:
![Image](https://github.com/openstax/cnx-recipes/assets/26280712/fb2865e0-8dd9-4d23-95e0-924de22f77f2)

- during web baking, a step should now take place which alters page titles & metadata, then puts them back where they were. the idea is that this should be invisible from the outside. 
- pls make sure nothing weird seems to be going on with page titles on web (as seen above the main content section)
- does not affect pdf

**Comment by kswanson33** [comment]
hello! the [branch](https://github.com/openstax/cookbook/pull/322/) for testing is cookbook `web-setup-data`

**Comment by Stackblocks** [comment]
Initial testing looks good. 

Waiting on a second pass that includes a logging element to make sure that the book is the same because thing that is supposed to happen is actually happening and working fine instead of the book looking the same because the thing is not happening.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/af8b5d80-e744-4092-8423-de1a27e98b6e)

**Comment by Stackblocks** [comment]
Revision with logging also looks good!

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/0f34c3c3-4ec4-45fc-8ee9-07efb69fbe7d)
