### ISSUE TITLE
Introduction to Python Programming -  code snippets repeating in output

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5403]
# Brief Description of Scenario
Code snippets are repeating in output possibly as a result from Fixes for adding color to code from #5351

![image](https://github.com/openstax/cnx-recipes/assets/89537088/f6d40907-127c-4cad-9c86-3a4b6be47885)

# Pattern of Occurrence 
All code snippets

# Acceptance Criteria

  
# Sample Mark-Up
```
    <example id="exam-00001">
    <title>Calculating the distance between two points</title>
    <code class="python" lang="python">
    import math<newline/>
    x1 = float(input("Enter x1: "))
    y1 = float(input("Enter y1: "))
    x2 = float(input("Enter x2: "))
    y2 = float(input("Enter y2: "))<newline/>
    distance = math.sqrt((x2-x1)**2 + (y2-y1)**2)
    print("The distance is", distance)
    </code>
    </example>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Screenshot is from Chapter 2/ Section 6
- **surrounding text:**

**Comment by lwtchu** [comment]
@ww-openstax the duplicate is caused by the `<newline/>`. I think the code should register the text in a separate line as a newline so the `<newline/> `tag is redundant and unnecessary. I was able to test in CORGI job https://corgi.ce.openstax.org/#8981 for this issue and it now renders correctly.

If possible, could y'all remove the any `<newline/>` tags in code. A regular line break should suffice.

**Comment by ww-openstax** [comment]
@lwtchu the `<newline/>` is there for **extra** space. They are needed to match the source.
see [job #8523](https://rex-web-production.herokuapp.com/books/8d08a72f-5463-4856-b05c-58b0d65f5e61@aea464a/pages/1-chapter-1-statements?archive=https://openstax.org/apps/archive-preview/20231204.181510)
<img width="504" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/287dccc5-b781-4bd3-b36f-72f81de5f313">

**Comment by ww-openstax** [comment]
After consulting with Larissa, WiseWire tested out replacing `<newline/>` with regular line break to achieve formatting. Test was successful. WiseWire will replace all `<newline/>` in code blocks with regular line break

**Comment by openstaxalina** [comment]
@ww-openstax I think this can be closed - the specific instance from the root comment looks like it was fixed with the removal of `<newline/>`. 

Screenshot from PDF generated this morning:
![Screenshot 2024-01-31 at 10 32 35 AM](https://github.com/openstax/cnx-recipes/assets/7863733/07b40b29-1257-40c9-a1b2-aa08592054a1)


We will handle the repeating of code snippets due to bold/italics text as part of #5405 . 

Let me know if this matches your understanding of this issue.

**Comment by ww-openstax** [comment]
@openstaxalina Yes. Understood. Closing this card.
