### ISSUE TITLE
Introduction to Python Programming - No code color from exercises 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#5408]
# Brief Description of Scenario and Screenshots

no code color in exrecises, stem tagges as `<pre class="python">print(y, type(y))</pre>` and the distractors are only tagged wtih `<code>`

adding lang="python" did not resolve. 

<img width="281" alt="Screenshot 2024-01-05 at 1 58 12 PM" src="https://github.com/openstax/cnx-recipes/assets/5865292/14cddd6c-74a8-4a12-a242-2240aaf59f26">

# Does this happen for every instance? Is there a discernable pattern of occurrences? Please describe below.
Every instance 

# Acceptance Criteria
- not sure if it's because injected exercises get brought in before or after mathify? 
- depending on complexity, timeline, etc - we could make the decision to not enable this in exercises or distractors (alina decision) 
- also pending decision on the other highlight.js issues 

# Sample mark up if applicable
```
<pre class="python">print(y, type(y))</pre>
```

# Location(s)
github openstax/osbooks- link: https://github.com/openstax/osbooks-introduction-python-programming
collection slug (if applicable): introduction-python-programming
chapter/section: all
surrounding text: I'm using exercise 39180 to test

**Comment by wilkus27** [comment]
I'm not very familiar with Enki project, but this is what I found.

Here exercises are downloaded: https://github.com/openstax/enki/blob/4a5c573cc49f6c206d16f63bc4a99476b45d6325/dockerfiles/steps/step-prebake.bash#L103

![image](https://github.com/openstax/cnx-recipes/assets/40228854/ef7fea54-859b-4fee-a212-4d1ae9d4796f)

So it looks like it is done before highlight.js is enabled. But the comment says that command is going to "replace internet links with local resource links", so maybe at this point there is still just link not content in xhtml form :thinking:

Other thing that I noticed is that code in injected exercises doesn't have `data-type="code"` attribute. It's because it's added in neb  https://github.com/openstax/enki/blob/4a5c573cc49f6c206d16f63bc4a99476b45d6325/nebuchadnezzar/nebu/xsl/cnxml-to-html5.xsl#L533 and if I understand correctly this code doesn't have an impact on injected exercises. 

But it shouldn't matter, because we are not using this attribute for hilghlight.js. The only matchers are tags with `data-lang`. https://github.com/openstax/mathify/blob/6286c7cdf22cd1e64b56072dd105077b9c56b1ee/typeset/converter.js#L78

![image](https://github.com/openstax/cnx-recipes/assets/40228854/48e2cbc9-0194-455e-9f51-b6f0ff0dfeba)

@TylerZeroMaster would you mind take a look on that issue?

**Comment by TylerZeroMaster** [comment]
Exercises are injected in assemble which occurs prior to mathify. The sample markup is missing the `data-lang` attribute. That attribute is used to find tags that highlight.js will transform and the value of the attribute is the language highlight.js should use when highlighting.

**Comment by yblock** [comment]
In testing, we tried adding it and it didn't seem to change anything

` <code class="python" lang="python">2.0 &lt;class 'int'&gt;</code>`

**Comment by wilkus27** [comment]
@yblock is it possible to add `data-lang` attribute instead of `lang`? In regular content `lang` is changed to `data-lang` within a trasformation xml to xhtml. Injected exercises are not going through this process, so in assembled file we still have `lang`.

If it's not possible, that's ok, I will try to add support for `lang` as well.

**Comment by yblock** [comment]
I've used lang at Larissa's recommendation. Using data-lang, the tag is stripped when the exercise is saved as if it is invalid.

**Comment by Stackblocks** [comment]
I'm seeing the `<code class="python"...` with both `lang` and `data-lang` in the markup for the stem and the distractors in the baked xhtml, but no coloration. 

Is the expected result here that the attributes are getting passed through cleanly or should there be code color at this point? @wilkus27 @jbwilson8 

![CleanShot 2024-01-25 at 16 20 42](https://github.com/openstax/cnx-recipes/assets/12678235/a32c8c52-c5c6-4da9-a53e-6632417113f4)

**Comment by Stackblocks** [comment]
Aha! I had forgotten to update submodules. Thanks for that. With that error corrected the colors are showing properly.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/8f065272-9bd2-4cab-81de-f71e1581ec41)

**Comment by yblock** [comment]
ohhh shiny ✨
