### ISSUE TITLE
Introduction to Python Programming - Answer Key contains Preface output

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5422]
# Brief Description of Scenario
The Answer Key contains Preface output. Please remove Preface from Answer Key.
In Webview and PDF.

### Webview
<img width="266" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/fe69724f-0334-4b72-b844-d1bd926f1c87">

### PDF
<img width="431" alt="image" src="https://github.com/openstax/cnx-recipes/assets/89537088/df37f364-82df-4294-b1ee-1c78c6d8c4ad">

# Pattern of Occurrence 

# Acceptance Criteria

  
# Sample Mark-Up
```
<document xmlns="http://cnx.rice.edu/cnxml" class="preface">
  <title>Preface</title>
  <metadata xmlns:md="http://cnx.rice.edu/mdml">
    <md:title>Preface</md:title>
    <md:content-id>m00116</md:content-id>
    <md:uuid>32a8f534-ae2d-4c29-b64b-5263a1215e12</md:uuid>
  </metadata>
  <content class="preface">
    <section id="sect-00001">
    <title>About OpenStax</title>
```

# Location(s)
- **osbooks repo:** osbooks-introduction-python-programming
- **collection slug:** introduction-python-programming
- **ref/branch:**
- **chapter/section:** Answer Key
- **surrounding text:**

**Comment by kswanson33** [comment]
question: this is happening because it looks like at one point, python had exercises in the preface, and these had solutions which needed to go into the answer key. 

(old version -- unstyled 🫢)

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/52498119-15a6-4c1e-b902-6fd76f576c7a)

![Image](https://github.com/openstax/cnx-recipes/assets/26280712/8e5951c9-0934-4b7a-aaef-b6bfdec0b28a)

currently, the `main` branch contains a content version without any exercises in the preface. it makes the most sense for me to remove all the code to bake preface exercises as part of this fix.

would that match the plans for the future? just want to avoid a situation where i take this code out and we have to put it back in later.

**Comment by openstaxalina** [comment]
@kswanson33 thanks so much for the investigation. yes, this rings a bell - we had exercises in the "preface" when we were circulating this for external reviews. The final preface won't have any exercises. So it is OK to remove all the code that bakes exercises in the preface.

**Comment by Stackblocks** [comment]
Preface content has been removed from the answer key.

## Web
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/68f6e887-7634-424a-9c0a-dcf2f7b26b73)

## PDF
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/43561811-98e3-4274-86cc-fe8ad9c07605)
