### ISSUE TITLE
nursing-external - comm pop - section or table header term tag issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5423]
We used term tag for section title header, in WEB view perfectly taken bold format. But in PDF View shows the extra bold in respective term words compared to other words. Please check and resolve this issue.
Here with attached screenshot FYR..

**CNXML:**
![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/4a977305-bede-4cc4-952e-5cc1fbe4ee5a)
**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/9d89746d-5051-41d7-8651-534bcc12c748)
**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/6c23a0b9-1ab8-4262-89af-36032feedc53)

# Acceptance Criteria
- if a term tag is in a title, please do not apply styling bold or unbold and should mimic the styling in the title
- please also implement in web

# Content
## Sample Mark-Up
```
<!-- Please paste here if applicable. -->
```

## Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-nursing-external-bundle
- **collection slug:** community-population
- **ref/branch:** term-header
- **chapter/section:** Chapter 15/Section 3
- **surrounding text:** There are different levels of influence that can affect health behavior. Recall Deanna

**Comment by wilkus27** [comment]
@lwtchu I had an old content version and there this problem didn't appear because term had `no-emphasis` class. Is there a reason that it's removed now?

**Comment by lwtchu** [comment]
@wilkus27 they could've been trying to make the webview version - the no-emphasis likely unbolds it in web. should we try the no-emphasis approach?

**Comment by wilkus27** [comment]
@lwtchu I checked the webview and the problem is that we have two different styling approaches for webview and PDFs. That is, in PDFs we are setting bold for all terms except ones with `no-emphasis` class

![image](https://github.com/openstax/cnx-recipes/assets/40228854/f651b3b0-908b-42c0-8ca4-cecb4e5a83f9)


On webiew - we have two settings, in one we are applying bold for all terms, in second one - we are setting `font-weight` to normal for all terms with class `no emphasis`

![image](https://github.com/openstax/cnx-recipes/assets/40228854/887d932c-138c-48de-9c45-08e70d410c05)

It causes problems, because selectors in css have hierarchy. Some of them are more important then others, so they overwrite themselves. And that's the case here. Property excluded by `:not` is not so important as property added for parent, so in PDF font weight for header overwrites bold for terms without class `no-empasis`. On the other hand, setting property directly for some selector is more important then property for it's parent, that's why on webview `font-weight: normal` for `no-emphasis` class overwrites bold for header.

We should probably standardize that and apply the same approach in both places, otherwise fixing problem in one place will broke another one. The question is which approach would be better. Both of them might causes some regression.

In my opinion, in our case better solution is one from PDF. Probably in most of the cases it's ok for us that font weight from parent overwrites bold from terms, because terms are parts of sentences and we want to display entire sentence with the same style, but I'm keeping in mind, that there might be some instances where this behaviour is not desirable.

**Comment by wilkus27** [comment]
I just found an old similar issue: https://github.com/openstax/cnx-recipes/issues/5054 :smile: Even webview solution is more proper in general, I was worried there that it might remove bold from places that we don't want to. Also here we have an example where removing `no-emphasis` class doesn't fix the problem, because we don't want term to be bold. We want it to inherit font weight from parent (in this case header) which is something between normal and bold. 

So again, I think we should go with PDF solution.

**Comment by lwtchu** [comment]
@wilkus27 Can you make the change in webview? And I'll have to add the no-emphasis tag onto the term in the header right? (Just to make sure)

**Comment by wilkus27** [comment]
@lwtchu Yes, we need `no-emphasis` class back :+1:

**Comment by lwtchu** [comment]
@wilkus27 i created a separate branch called term-header

**Comment by MartaSztuka** [comment]
#### PASSED
##### PDF
![Zrzut ekranu z 2024-02-13 13-15-00](https://github.com/openstax/cnx-recipes/assets/47241114/bb2cde94-0d76-4c06-a772-16f13c79ba82)
##### Webview
![Zrzut ekranu z 2024-02-13 13-28-57](https://github.com/openstax/cnx-recipes/assets/47241114/802a5f92-7c69-4fd5-a5a1-5e29968f124a)
