### ISSUE TITLE
data science - web and pdf - answer key alignment

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5511]
# Summary & Screenshots
The detailed solutions answer in the **ANSWER KEY** part is not aligned correctly in both the PDF and WEB views.

**PDF VIEW:**
![PDF_View1](https://github.com/openstax/cnx-recipes/assets/86622862/0ef18b8b-83be-4a25-bbac-152fb9b3fc54)

**WEB VIEW:**
![WEB_View1](https://github.com/openstax/cnx-recipes/assets/86622862/476dd6a1-f5d9-4980-8f32-ddec93d75d3f)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-principles-data-science
- **collection slug:**  Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  ANSWER KEY
- **surrounding text:** tend to skew the untrimmed mean.

# Acceptance Criteria

## PDF and Web
- can we have the detailed solutions answers align - i don't think this has been enabled in other books in the past

**Comment by Stackblocks** [comment]
There still appear to be some alignment issues on Web, and I am running into issues baking the PDF where the process can't find the very real mathified linked single so it may be an issue with the baking on my machine. Will investigate further tomorrow and follow up with updates.

## Web Alignment
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/83471d93-0ca9-4c8b-87c3-e97657f21658)

## Bake Error


![Image](https://github.com/openstax/cnx-recipes/assets/12678235/a2b46291-9433-401d-890a-ed9203b8bc1f)



![Image](https://github.com/openstax/cnx-recipes/assets/12678235/d3c29caa-89f6-45dc-9b64-c724e32e2d68)

**Comment by wilkus27** [comment]
Alignment issue is caused by too long python code. It's going outside of the page. We should probably be able to scroll it. @lwtchu Should we have a separate card for that?

@Stackblocks about bake error, I had a similar problem :see_no_evil: It's because they changed a slug. They removed `of` from it. I guess you are using in command old slug. (That is what I did :wink: )

**Comment by Stackblocks** [comment]
Thanks so much @wilkus27, it looks like that was the problem. It's extra funny because the `design-chapters` branch still uses the old slug so I tripped over that `of` in both directions testing this.

@lwtchu The PDF output looks much more normal now, but I want to make sure that this is the output that we're looking for since the structure changed from being a numbered list with a 2nd tier lettered list for the detailed answers to a numbered list with the detailed answers all under the umbrella of the main number. Also some things appear to have been rearranged—e.g. the position of the `Mean...` and `See Solution Manual` lines—which makes sense if they were out of alignment.

![Image](https://github.com/openstax/cnx-recipes/assets/12678235/292d54a2-7afd-4cf2-bf12-d1d2f67105a2)

**Comment by wilkus27** [comment]
@lwtchu I looked on the issue that you posted and just noticed that these exercises are multipart questions. But they're not baked. Do you want me to do this? If yes, what numbering should be used - lower or upper alpha? It will also have an impact on solution. I need to do more changes in that case.

**Comment by lwtchu** [comment]
@wilkus27 Let's park this on Monday 🤔 Can you show me what it would look like if we went with lower alpha

**Comment by wilkus27** [comment]
@lwtchu I noticed that some of the non multipart questions have lower alpha points hardcoded in the content

![image](https://github.com/openstax/cnx-recipes/assets/40228854/053ed1b4-8188-4399-afb2-8ee56cd2902c)

So I tried an upper alpha first:

![image](https://github.com/openstax/cnx-recipes/assets/40228854/08bfd41d-8b47-4290-8408-4d42465a0662)

Let me know if I should apply lower alpha anyway.

**Comment by lwtchu** [comment]
@wilkus27 ah okay. we haven't done our first chapter review of the content yet - let's focus on the answer key alignment and we can open a separate card later. I'll alert Alina

**Comment by wilkus27** [comment]
@lwtchu The way of baking exercises has impact on answer key. My solution was made only for answers from regular exercises. Do you want me to make a change for answers from multipart questions as well?

**Comment by lwtchu** [comment]
@wilkus27 for the alignment? yes please.

**Comment by Stackblocks** [comment]
Main and multipart numbering now aligns nicely.

# PDF
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/9afd99da-5d82-48fd-a12c-430a975f4eec)

# Web
![Image](https://github.com/openstax/cnx-recipes/assets/12678235/3592f01f-311a-4bdb-9d2e-933b80ade6ad)

_(Something is off with number 4 in the Web output, but that may be the python issue you mentioned before or some other one-off or test content issue. Going to move this forward and we can revisit if necessary)_
