### ISSUE TITLE
Figure caption - Left alignment in PDF View

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5528]
We have coded the caption as per the row 29 tagging legend instruction. We were unable to control the text align in left in PDF View. Please check and confirm. But in WEB view caption text aligned left. Kindly check and resolve this issue, we need PDF Alignment same as to be WEB view.

Please find the attached screenshot for your reference.

**CNXML:**
![CNXML](https://github.com/openstax/cnx-recipes/assets/86622862/53407d33-c57d-4242-a441-0325081fc388)

**PDF VIEW:**
![PDF_View](https://github.com/openstax/cnx-recipes/assets/86622862/1b5dcce2-1076-4fbb-a5bd-407a0e852c43)

**WEB VIEW:**
![WEB_View](https://github.com/openstax/cnx-recipes/assets/86622862/689c2a9b-a73e-4313-9a6e-a30af7ecbdb9)

# Issue Occurrence(s)

 **Location**
- [ ] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:** Chapter 03/3.1
- **surrounding text:** The Output of DataFrame.describe() with the Movie Profit Dataset

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax Figure captions is a library wide setting. This isn't something we will fix as there are certain design limitations with regards to PDF and readability for varying image sizes (think a narrow, non-full page image with a left aligned image). The web can function this way as images usually more or less fill up the container space due to the resolution of the images and the size of the content space.
