### ISSUE TITLE
Index Color Issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5558]
In the index (in PDF view), there’s a color difference between the following items (“norm.cdf” and “norm,” circled in blue, appear in green vs. “DataFrame.describe” appears in black)

**PDF View:**

![image002](https://github.com/openstax/cnx-recipes/assets/86622862/6082d189-b9a8-493e-8acd-b955819dd21e)

Although all three appear in green in the chapter text (in the PDF view):

**PDF view p. 18:**
![image003](https://github.com/openstax/cnx-recipes/assets/86622862/1ab82cfa-9d3c-4db4-936b-b52882b7f2aa)

**PDF view p. 41:**
![image004](https://github.com/openstax/cnx-recipes/assets/86622862/70ac678e-b9fc-496f-84cc-dc6a2909367a)

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [ ] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  https://github.com/openstax/osbooks-principles-data-science
- **collection slug:** Principles-data-science
- **ref/branch:** https://openstax-osbooksprincip-cvay7xh0p0y.ws-us110.gitpod.io/
- **chapter/section:**  Index Section
- **surrounding text:** binomial distribution 33

# Acceptance Criteria

**Comment by lwtchu** [comment]
@srm-openstax 
The term tag needs to go **around** the `<code>` in order to carry it all to the index. 
Change 
`<code><span class="green-code"><term class="no-emphasis" id="term-00001">DataFrame.describe</term></span>()</code>`

to 
`<term class="no-emphasis" id="term-00001"><code><span class="green-code">DataFrame.describe</span>()</code> </term>`

**Comment by srm-openstax** [comment]
As per the your suggestion, index term working fine.
