### ISSUE TITLE
computer science - ALL LABS should appear at the end of the Chapter

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5571]
# Summary & Screenshots
ALL "Lab Assessments" should appear at the end of the Chapter
![ComputerSci_AssessmentLabs_issue](https://github.com/openstax/cnx-recipes/assets/89537088/90699277-004b-4875-ac15-e776f16db503)

# Sample Mark-Up
```
    <section class="labs-assessments" id="sect-00019">
    <title>Assessments: Labs</title>
    <exercise id="exer-00017">
    <problem id="prob-00017">
    <para id="para-00057"><link class="os-embed" url="#exercise/03-01-CS-LB01"/></para>
    </problem>
    </exercise>
    </section>
```

# Issue Occurrence(s)

 **Location**
- [X ] In PDF
- [X ] In Web

**Frequency**
- [X] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:**  osbooks-introduction-computer-science
- **collection slug:** introduction-computer-science
- **ref/branch:**
- **chapter/section:**  Ch 1.1 (occurs in every section)
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] Labs should be the very last EOC element. It should look like this:

![Image](https://github.com/openstax/cnx-recipes/assets/7863733/39b6a476-ec33-4459-9828-2253c06b4231)

## Web 
- [ ] Labs should be the very last EOC element

**Comment by openstaxalina** [comment]
@ww-openstax can you please put in the sample markup, check off the correct frequency, and fill in information under "Content Location(s)"?

**Comment by ww-openstax** [comment]
@openstaxalina - Hi - Sorry about that. Your requested information has been added. Amanda

**Comment by openstaxalina** [comment]
thank you @ww-openstax -- I updated the Acceptance Criteria to indicate Labs should be the very last EOC piece, per the [original designs](https://drive.google.com/file/d/1KAYqs-YThVNw9uGrMbUW1NPflsnERDHF/view). If Labs should NOT be the very last EOC element please indicate where in the order it should go.

We will start work on this next week so need any further information before that time.

**Comment by openstaxalina** [comment]
likely cookbook only issue

**Comment by kswanson33** [comment]
most of this has already been implemented, except for the `lab-assessments` class instead of `labs-assessments`. I've fixed the typo everywhere it occurs. 

Additionally, the SVGs are not showing up as per spec for any EOC title, not just Labs. I will fix that as part of this issue. Bumping the points

**Comment by kswanson33** [comment]
actually @openstaxalina , upon more investigation, the structure seems to have changed from the original design. instead of EOC sections appearing separately, they're all under the Chapter Review composite chapter, which means that the headers are not H2s but H3s. there does not seem to be a precedent for H3s with SVGs.

should i add in the SVGs? if so, should these headers keep the H3 styles or should they be changed to look more like H2s?

**Comment by kswanson33** [comment]
[here](https://github.com/openstax/cnx-recipes/issues/4011) is the issue that requested this change

**Comment by kswanson33** [comment]
hello QA, this can be tested on branch `cs-labs-eoc` on ce-styles

**Comment by omehes** [comment]
testing: cs-labs-eoc on ce-styles and computer-science-labs on cookbook

./enki --command all-pdf --data-dir ./data7/icspdf --repo osbooks-introduction-computer-science --ref main --book-slug introduction-computer-science --clear-data

retested with cookbook on correct branch: pdf and web-preview - OK


![Image](https://github.com/user-attachments/assets/74c90272-3374-41cf-89f1-3384a82a6106)

**Comment by omehes** [comment]
tested in corgi - ok
