### ISSUE TITLE
Computer Science: Learning Objectives" header appears to be the same as the H2 header

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5573]
# Summary & Screenshots
""Learning Objectives" header appears to be the same as the H2 header below it. This hierarchy could potentially be confusing for students -- please review."

![Screenshot 2024-06-24 084219](https://github.com/openstax/cnx-recipes/assets/89537088/2f88a747-56d0-4d19-b2e9-d248c57c1ca3)

# Sample Mark-Up
```
<title>Introduction to Data Structures and Algorithms</title>
  <metadata xmlns:md="http://cnx.rice.edu/mdml">
    <md:title>Introduction to Data Structures and Algorithms</md:title>
    <md:content-id>m00002</md:content-id>
    <md:uuid>e8bc2004-f3d7-4718-9784-6b5d6edf766f</md:uuid>
  </metadata>
  <content>
    <section class="learning-objectives" id="sect-00001">
    <title>Learning Objectives</title>
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [ ] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-introduction-computer-science
- **collection slug:** introduction-computer-science
- **ref/branch:**
- **chapter/section:** Ch 1.1
- **surrounding text:** 

# Acceptance Criteria

## PDF
- [ ] update Learning Objectives header to follow #2711:
class: learning-objectives
title: Learning Objectives
title font: noto sans
title color: header color
title weight: bold, 700
title size: font-scale(1): 10.8pt, 14.4px, 1.2rem

(compare to [h2 for Cardboard here](https://github.com/openstax/cnx-recipes/issues/2644) - Learning Objective and h2 headers should not be the same)

**Comment by kswanson33** [comment]
Investigation:

![image](https://github.com/openstax/cnx-recipes/assets/26280712/68052633-5c0b-474c-a2cd-378dc84dcd85)


Learning Objectives, Introduction to Algorithms, Understanding Data Structures, etc are `h3`s with specs:

- `font-family: Noto Sans, StixGeneral`
- `font-size: 1.44rem`
- `line-height: 1.5rem`

Section titles like 3.1 are `h2`s with specs:

- `font-family: Roboto Condensed, StixGeneral`
- `font-size: 1.728rem`
- `line-height: 1.728rem`

Everything for Learning Objectives is to spec, except the font-size, which is set with `font-scale(1)` as per the specs, but this function has a different output than the specs claim it should (1.44rem instead of 1.2rem). Not sure what's up with the discrepancy, but it'll be consistent everywhere `font-scale(1)` is used.

@openstaxalina What new specs are needed here? Should I update the font size?

**Comment by openstaxalina** [comment]
@kswanson33 yes, that's it -- thank you!

**Comment by kswanson33** [comment]
QA: please test on ce-styles branch `cs-lo-header`

**Comment by omehes** [comment]
verified as per instructions. looks good

used:
./enki --command all-pdf --data-dir ./data6/CS --repo osbooks-introduction-computer-science --ref main --book-slug introduction-computer-science --clear-data
 and 
ce-styles branch cs-lo-header
and updated enki

**Comment by omehes** [comment]
tested in corgi - ok
