### ISSUE TITLE
Numbering of headers

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#716]
Headers in **Review Exercises** should be numbered:

https://katalyst01.cnx.org/contents/CImQfPDv@3.15:ZqmjWn9P@3.15/Exercises
![rev ex_web](https://user-images.githubusercontent.com/40228854/48558363-6daedb00-e8e9-11e8-8134-02dba17d169f.JPG)

PDF:

![rev ex_subtitle](https://user-images.githubusercontent.com/40228854/48558420-89b27c80-e8e9-11e8-92c2-39b242c9fd0b.JPG)

Sometimes numbering occurs, but it should be removed in content by https://github.com/Connexions/content-managers/issues/463 

![rev ex2_web](https://user-images.githubusercontent.com/40228854/48558975-e6626700-e8ea-11e8-8143-f21818e1cfc5.JPG)

**Comment by brittany-johnson** [comment]
In the last screenshot with the title "Section 2.1 ~" is being numbered by the content

**Comment by helenemccarron** [comment]
It looks like the template is adding a target counter to the title in the end of section:
`target-counter(attr(href), chapter) "." target-counter(attr(href), section)`, in order to achieve the same in the recipes, we need to modify the existing titles (probably after the EOS has been composed and assembled).

**Comment by helenemccarron** [comment]
@openstaxalina, upon further investigation: the titles are in the raw content. The PDF numbers them. I think this is because `review-exercises` are all at the end of the chapter, thus making it impossible to retrieve the module title the would normally come from. The only solution for numbering those titles is to retrieve the titles of each module and replace those titles. This would a very ad-hoc option, that would need to be applied to this recipe specifically, we currently do not support this type of functionality.

**Comment by openstaxalina** [comment]
@helenemccarron in this case, I propose that we do **not** have numbering on the headers.  The lack of numbering is acceptable because the headers are also links, so the user can click to the sectin if they really need to know the section number.

If you agree, feel free to close this issue.
cc @lwtchu
