### ISSUE TITLE
Clinical Focus in Introduction

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#811]
On katalyst01 (https://katalyst01.cnx.org/contents/5CvTdmJL@5.8:ZQbykX_f@3/Introduction) note **Clinical Focus** appears in section Introduction. It should be placed in section 17.1 right after Learning Objectives:

![intro](https://user-images.githubusercontent.com/40228854/51997050-43b39080-24b6-11e9-8c9d-c6173b9c1e58.JPG)

**Comment by Adrianltd** [comment]
Similar to https://github.com/openstax/cnx-recipes/issues/812
`Clinical Focus` in this case is inside the `Introduction` page in the RAW file.

cc: @openstaxalina

**Comment by lwtchu** [comment]
<img width="604" alt="screen shot 2019-02-07 at 9 10 34 am" src="https://user-images.githubusercontent.com/11299125/52420736-3f8c0200-2ab8-11e9-900e-f07ff4135de5.png">
Appears in 17.1 in the PDF - I think this is because the last line of the intro pushed the clinical focus and the PDF design snapped it to the bottom of this page...therefore it was never corrected. Will move to the CM repo.

**Comment by lwtchu** [comment]
Issue moved to [openstax/content-managers #605](https://github.com/openstax/content-managers/issues/605) via [**ZenHub**](https://www.zenhub.com/)
