### ISSUE TITLE
Different figures captions

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#848]
In PDF there is ex. Figure 2 and caption is aligned, in webview there is Figure 1.2 and caption to the left

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:0KhpF2RH@23/1-1-Real-Numbers-Algebra-Essentials

There is:
![fig](https://user-images.githubusercontent.com/47241114/52799893-05ec6580-307b-11e9-9a81-ede856bd1334.png)

Should be:
![fig pdf](https://user-images.githubusercontent.com/47241114/52799900-0ab11980-307b-11e9-9f75-68437eddc55f.png)

Caption Figure 1.2 in webview needs to be replaced with caption Figure 2 an aligne as in PDF.

**Comment by openstaxalina** [comment]
The Precalculus trio (_Precalculus_, _College Algebra_, _Algebra & Trigonometry_) PDFs were created using a different software, and now I realize that they use a different numbering scheme ("Figure 1 instead of 1.1, etc.).

Are we going to be able to replicate this in the Assignable Webview?  This will be a different numbering schema than other recipes.

All of the above also applies to **table** numbering in these books.

**Comment by helenemccarron** [comment]
Yes, I believe we can alter numbering schemes for both figures and tables at the book level using 
```$Config_PartType_Table_CaptionContent: (os-title-label: "Table ", os-number: counter(table), os-divider: ' ');```
and 
```$Config_PartType_Figure_CaptionContent: (os-title-label: "Figure ", os-number: counter(figure), os-divider: ' ');``` 

We should make a note that we decided to align ourselves with the XYZ templates, these books will stand out from regular Openstax books and we might forget why when looking at them in Webview.

**Comment by Adrianltd** [comment]
I will mention that in the Bookmap.

**Comment by Adrianltd** [comment]
Should be fixed in https://github.com/openstax/cnx-recipes/pull/836/commits/68e9ff69f8b9add6f84290b2fff41c280a04fe22
