### ISSUE TITLE
03/12/2019 Release Epic

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#849]

**Comment by pumazi** [comment]
This release will have database migrations.

**Comment by pumazi** [comment]
At this time... releasable packages include

- `cnx-transforms==1.0.1` (new, required by cnx-archive, cnx-db and nebuchadnezzar)
- `cnx-cssselect2==0.2.3` (may be required by cnx-recipes, otherwise no need to release)
- `cnx-db==3.1.0` (has database migrations)
- `cnx-archive==4.11.0`
- `cnx-easybake` (changes made, but only to tests, no release needed)
- `Products.RhaptosCollection==0.85` (re-release of last sprints work, which had a release number collision) ("egg" needs created) ([cnx-deploy version update](https://github.com/openstax/cnx-deploy/pull/1025))
