### ISSUE TITLE
Numbering in Answer Key

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#857]
In PDF Answer Key (aka Try it answer) answers are devided like this:
1. Chapters (1-13)
-- Section (1.1, 1.2, 1.3 etc)
----Examples (1,2,3...)
2. Odd Answers
Chapter 1 (Sections 1-57)
--Review exercise
--Practice Test

![screenshot from 2019-02-18 16-01-00](https://user-images.githubusercontent.com/47241114/52963570-70194900-33a0-11e9-8543-1fc87789ad22.png)

In webview:
Chapter 1 (1.1 - 1.60)
Sections (1,3,5...472)

![screenshot from 2019-02-18 15-47-54](https://user-images.githubusercontent.com/47241114/52963591-80c9bf00-33a0-11e9-8ddf-faf638200cc4.png)

https://katalyst01.cnx.org/contents/E6wQevFf@11.1:wjawyj79@11.1/Chapter-1

Numbering issue needs to be unified in all meth books, Thanks!

**Comment by openstaxalina** [comment]
@MartaSztuka I have the following notes regarding the Precal trio (taken from the [Answer Key Analysis Doc](https://docs.google.com/spreadsheets/d/1mxjUDohm0sSHnSFi76e_8MpInUPl9r5bpVDpLxJhG1A))

Answer Key contains: **ALL Try It Answers, then only ODDS**.

Can you confirm this is the behavior you see in the PDF in the three Precal books (_College Algebra_, _Precalculus_, _Algebra & Trigonometry_)?

If so, I suggest filing only one issue about the webview Answer Key, since these books share a recipe.  There is already an issue open for _College Alegbra_: https://github.com/openstax/cnx-recipes/issues/855.

**Comment by MartaSztuka** [comment]
@openstaxalina Thanks, thats correct, there's Try it then oddsin all three. I'll keep it in mind
