### ISSUE TITLE
Tables numbering

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#906]
In PDF Tables numbers reset every subsection, in webview - every chapter.
https://katalyst01.cnx.org/contents/mwjClAV_@8.1:Sc8taR03@9/1-5-Factoring-Polynomials

![tab](https://user-images.githubusercontent.com/47241114/54028432-408e7d00-41a5-11e9-9d07-06b9cbb45e04.jpeg)

https://katalyst01.cnx.org/contents/E6wQevFf@11.1:kIiWytsm@6/10-6-Parametric-Equations

https://katalyst01.cnx.org/contents/_VPq4foj@8.1:N_3EIhjl@8/2-3-Modeling-with-Linear-Functions

**Comment by MartaSztuka** [comment]
Issue is fixed.
![Screenshot from 2019-03-29 14-37-08](https://user-images.githubusercontent.com/47241114/55236558-82549580-5230-11e9-9842-b777034489ce.png)
![Screenshot from 2019-03-29 14-38-37](https://user-images.githubusercontent.com/47241114/55236570-8680b300-5230-11e9-8f16-deeb9b042297.png)
![Screenshot from 2019-03-29 14-39-11](https://user-images.githubusercontent.com/47241114/55236573-8aacd080-5230-11e9-9bca-3f09872062c5.png)

**Comment by uskka** [comment]
Fixed in all of the books. Tested on katalyst01.

<img width="706" alt="Screenshot 2019-04-05 at 17 33 02" src="https://user-images.githubusercontent.com/40228918/55639491-cebc4a00-57c9-11e9-832d-59b240070f21.png">
<img width="556" alt="Screenshot 2019-04-05 at 17 32 53" src="https://user-images.githubusercontent.com/40228918/55639493-cf54e080-57c9-11e9-96b6-6ea15074102f.png">
